### ISSUE TITLE
Confusion about unet's decoder section.

### ISSUE THREAD

**Issue by ysssgdhr** [qubvel/segmentation_models.pytorch#112]
Hello author. I read your code and find the decoder part of Unet is really confusing.
For example, when we use Unet as a segmentation backbone of EfficientNet-B4, for which '_stage_idxs' is [6,10,22]. And the features extracted from it need to append the head, and the skip-connection will be extracted from   [5th block, 9th block, 21st block, last block].

I understand that it is hard to balance the number of channels between decoder and encoder like origin Unet did when out_channels of encoders like EfficientNet are not doubled step by step.

But if you follow your code, in the case of depth set to 5, only 2 skip-connection will be built, which I think is very insufficient. 

<img width="812" alt="image" src="https://user-images.githubusercontent.com/24486813/69930403-48920800-14fe-11ea-9b5e-876e262083c9.png">

At the same time, I don't understand the meaning of "#remove first skip with the same spatial resolution" and not use first-layer for skip-connection.
I hope you can see my question and give your rely, that will be so much appreciated. :)

Your implementation of UnetDecoder:
<img width="911" alt="image" src="https://user-images.githubusercontent.com/24486813/69930425-5a73ab00-14fe-11ea-8d58-d7c50becffee.png">

**Comment by qubvel** [comment]
Hi, look in `forward` method of `efficientnet` encoder. All encoders retrun list of 6 tensors (features). We remove only first skip connection with same sapatial resolution as input (because usually first conv layer already have strides for image downsampling and we are not able to get features of original spatial size).
