### ISSUE TITLE
Mask format for catalyst

### ISSUE THREAD

**Issue by PiotrowskiD** [qubvel/segmentation_models.pytorch#114]
Hi, I am trying to do segmentation of kidneys and tumors. Right now my mask are [512, 512, 3] with two colours for two classes ([255, 0, 0] and [0, 255, 0]). The classes can overlap. I do not have separate class for background.

Right now when I run modified example with :
``` model = smp.Unet(encoder_name="resnext50_32x4d", classes=2, activation='sigmoid') ```

I get following error

intersection = torch.sum(targets * outputs)
RuntimeError: The size of tensor a (3) must match the size of tensor b (224) at non-singleton dimension 4

Do I understand correctly that I the mask should have another dimension for classes? Also should they be binary then?

**Comment by PiotrowskiD** [comment]
I still got the error (probably need to swap the dimensions) but I got how the mask for multiclass is supposed to look like from the first example. So if anyone is wondering it is binary, and [h, w, num_classes]

**Comment by qubvel** [comment]
Check model output have n_channels = 2 and dataloder output have target n_channels = 2
