### ISSUE TITLE
How to use the legendary Unet?

### ISSUE THREAD

**Issue by Legolas970424** [qubvel/segmentation_models.pytorch#116]
Hello, first of all thanks for an awesome library.
I'm confused when I want to use the legendary Unet. 
The default encoder_name of class 'smp.Unet'  is "resnet34", which means when i create model use 'smp.Unet()', the backbone will be resnest34. So how can i create the legendary Unet model?

![image](https://user-images.githubusercontent.com/22142026/70602200-cf499200-1c2e-11ea-81ad-9c769c92b02e.png)

**Comment by qubvel** [comment]
Hi @Legolas970424 
I used "legendary" just to emphasize that Unet is used everywhere to solve numerous number of problems.
