### ISSUE TITLE
AttributeError: Can't pickle local object 'get_preprocessing_fn.<locals>._preprocess_input’

### ISSUE THREAD

**Issue by cocozfz** [qubvel/segmentation_models.pytorch#12]
When I run "cars segmentation (camvid).ipynb", there was an error： AttributeError: Can't pickle local object 'get_preprocessing_fn.<locals>._preprocess_input'
This error is in the "train model for 40 epochs"
Thanks

**Comment by qubvel** [comment]
Hi, its look like you are trying to pickle preprocessing function (maybe it is a multiprocesiing in dataloader), what is your python version and how many workers is set in dataloader?

**Comment by cocozfz** [comment]
> Hi, its look like you are trying to pickle preprocessing function (maybe it is a multiprocesiing in dataloader), what is your python version and how many workers is set in dataloader?

My python version is 3.6.5， and I just use the demo of yours (named cars segmentation (camvid).ipynb).
And the num_workers=12 in train_loader, the num workers=4 in valid_loader.

Thanks for your reply！^_^

**Comment by qubvel** [comment]
What is your os? I test it with:
Ubuntu 18.04
Python 3.6  

And it works fine...

**Comment by cocozfz** [comment]
> What is your os? I test it with:
> Ubuntu 18.04
> Python 3.6
> 
> And it works fine...
My os is:
Windows Server 2016
Python 3.6

**Comment by cocozfz** [comment]
> Check is the fix works with updated package:
> 
> ```shell
> $ pip install -U git+https://github.com/qubvel/segmentation_models.pytorch@fix/pickling-preprocess-input
> ```
> 
> And let me know, I dont have a windows machine to check it by myself. Thanks.

I first used the pip instruction, which prompted an ERROR ：BrokenPipeError: [Errno 32] Broken pipe. And then I set numwork=0 in the dataloader, and it  works! 
This problem is caused by multithreading under Windows and is related to the DataLoader class.
the details here : https://github.com/pytorch/pytorch/pull/5585
 
Thank you very much! Have a good day^_^

**Comment by qubvel** [comment]
#15
