### ISSUE TITLE
Efficientnet cant be exported as onnx

### ISSUE THREAD

**Issue by Vozf** [qubvel/segmentation_models.pytorch#122]
When trying to export model to onnx 
`torch.onnx.export(model, dummy_input, train_path + 'model.onnx')`
Error is raised 
`RuntimeError: ONNX export failed: Couldn't export Python operator SwishImplementation`
Maybe we need an option to use relu instead of swish which can be exported to onnx

**Comment by qubvel** [comment]
Use `model.encoder.set_swish(memory_efficient=False)` before export model with efficientnet encoder.

**Comment by Vozf** [comment]
Thanks. That works
