### ISSUE TITLE
c++ libtorch

### ISSUE THREAD

**Issue by hhhh0** [qubvel/segmentation_models.pytorch#124]
I have successfully loaded the traced model in c ++ with vs2019, but the program reports an error during prediction.

**Comment by qubvel** [comment]
Hi, what is an error?

**Comment by hhhh0** [comment]
I recompiled the program and the problem was resolved. thank you for your help.

**Comment by AlessandroSaviolo** [comment]
Hi! I'm trying to load the models in C++ too, but I'm having multiple problems. I use `torchscipt` to save the model as `.ph` file, but when I load it in the C++ script it returns an error. Can you share the code for saving the model and then loading it?
Thank you!
