### ISSUE TITLE
train more class in example

### ISSUE THREAD

**Issue by yumulinfeng1** [qubvel/segmentation_models.pytorch#127]
Hi
I want to train more class in example,not just car.
how can i do that?
for eaxmple, when i want to train road and car.
`# Lets look at data we have

dataset = Dataset(x_train_dir, y_train_dir, classes=['road','car'])
print(len(dataset))

image, mask = dataset[2] # get some sample
visualize(
    image=image, 
    cars_mask=mask.squeeze(),
)

print(mask.shape)`

the code above is wrong

**Comment by qubvel** [comment]
visualization function works with 1- or 3-channels images, you have to conver one-hot mask to RGB mask or grayscale mask.
