### ISSUE TITLE
ImportError: cannot import name 'url_map' from efficientnet_pytorch.utils

### ISSUE THREAD

**Issue by suhaspsr** [qubvel/segmentation_models.pytorch#131]
I am getting an import error while trying to create an Unet Model. Here is the full message. I checked with "efficientnet_pytorch.utils" after the 23rd Jan update they have removed 'url_map' function. How to work around it? 

Thanks.

ImportError:
/usr/local/lib/python3.6/dist-packages/segmentation_models_pytorch/unet/__init__.py in <module>()
----> 1 from .model import Unet

/usr/local/lib/python3.6/dist-packages/segmentation_models_pytorch/unet/model.py in <module>()
      1 from typing import Optional, Union, List
      2 from .decoder import UnetDecoder
----> 3 from ..encoders import get_encoder
      4 from ..base import SegmentationModel
      5 from ..base import SegmentationHead, ClassificationHead

/usr/local/lib/python3.6/dist-packages/segmentation_models_pytorch/encoders/__init__.py in <module>()
      9 from .inceptionresnetv2 import inceptionresnetv2_encoders
     10 from .inceptionv4 import inceptionv4_encoders
---> 11 from .efficientnet import efficient_net_encoders
     12 from .mobilenet import mobilenet_encoders
     13 from .xception import xception_encoders

/usr/local/lib/python3.6/dist-packages/segmentation_models_pytorch/encoders/efficientnet.py in <module>()
     25 
     26 from efficientnet_pytorch import EfficientNet
---> 27 from efficientnet_pytorch.utils import url_map, get_model_params
     28 
     29 from ._base import EncoderMixin

ImportError: cannot import name 'url_map'

**Comment by qubvel** [comment]
Hi, Install efficientnet version specified in requirements (but not last), I will fix it, thanks for report.
