### ISSUE TITLE
AttributeError: 'EfficientNetEncoder' object has no attribute 'make_dilated'

### ISSUE THREAD

**Issue by splinter21** [qubvel/segmentation_models.pytorch#132]
model=smp.PAN('efficientnet-b4'......)

**Comment by LSnyd** [comment]
@splinter21 Did you figure out how to solve the Error? I get the same for DeepLabV3 and the VGG backbones.

**Comment by ZhongYupei** [comment]
hi, did u solve it? I met the same issue
