### ISSUE TITLE
AttributeError: 'list' object has no attribute 'size'

### ISSUE THREAD

**Issue by mobassir94** [qubvel/segmentation_models.pytorch#137]
i used the same code below,just replaced se_resnext50_32x4d with vgg11/vgg16  and i can get the model summary for unet with vgg11/vgg16 but whenever i try to get model summary of FPN with se_resnext50_32x4d i get error :  AttributeError: 'list' object has no attribute 'size'

for any encoder with FPN decoder i get this error but i don't get this error with unet decoder,any solution please?

model = smp.Unet('se_resnext50_32x4d', encoder_weights="imagenet")

!pip install torchsummary
from torchsummary import summary
!pip install git+https://github.com/qubvel/segmentation_models.pytorch > /dev/null 2>&1 
import segmentation_models_pytorch as smp
model = smp.Unet('se_resnext50_32x4d', encoder_weights="imagenet")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
summary(model, (3, 512, 512))

**Comment by AlexanderSlav** [comment]
Hi,@mobassir94, try to use something like
`from torchsummaryX import summary`
`arch = summary(model, torch.rand((1, 3, 256, 256)))`
it might help.

**Comment by BugKid** [comment]
> Hi,@mobassir94, try to use something like
> `from torchsummaryX import summary`
> `arch = summary(model, torch.rand((1, 3, 256, 256)))`
> it might help.

Thanks, it really works and help me a lot!

**Comment by Ahme1994** [comment]
Hello ,can someone helps me ,when I run my code I got this error 
AttributeError: 'list' object has no attribute 'size'
#rpm
for epoch in range(300):
    for x,y in enumerate(train_loader):
        y = torch.zeros(y.size(0),4).scatter_(1,y.view(-1,1),1.)
        x,y = x.to(device),y.to(device)
        output,_ = rpm_nn(x,y)              # cnn output
        loss = loss_func(output)   # cross entropy loss# clear gradients for this training step
        optimizer_rpm.zero_grad()
        loss.backward()
        optimizer_rpm.step()
    test_out,_=rpm_nn(test_x,test_y)
    pred_z=torch.max(test_out,1)[1].cpu().data.numpy()
    accuracy = float((pred_z == test_z.cpu().numpy()).astype(int).sum()) / float(test_y.size(0)) 
    print('Epoch: ', epoch, '| train loss: %.4f' % loss.cpu().data.numpy(), '| test accuracy: %.2f' % accuracy)

**Comment by ajithkumarmcw** [comment]
`!pip install torch-summary==1.4.4` This command solved for me
