### ISSUE TITLE
Weighted BCEDiceLoss 

### ISSUE THREAD

**Issue by luistelmocosta** [qubvel/segmentation_models.pytorch#139]
Hello, did anyone implement a weighted version of BCEDiceLoss? Imagine that my weights are [0.1, 0.9] (pos, neg), and I want to apply it to my Dice Loss / BCEDiceLoss, what is the best way to do that? 
I could not find any implementation of this using this library; any help would be highly appreciated. 

Regards

**Comment by bonlime** [comment]
Weighted BCEDice Loss is actually called `Tversky loss` you can google more information and implementations

**Comment by luistelmocosta** [comment]
I will check that. 
Any chance that anyone used that loss with this library?

**Comment by bonlime** [comment]
There is no way to magically turn DIce into Tversky loss you have to write the loss function yourself. It should be pretty easy

**Comment by luistelmocosta** [comment]
I am a newbie in this topic, don't think it will be pretty easy for me. And I was using the built-in loss functions from this repository, don't know how to adapt my current DiceLoss to Tversky

**Comment by luistelmocosta** [comment]
Well, I tried to implement the trevsky loss (might be a good addition to this project if functional) but I am having an error that probably happened before.

from segmentation_models_pytorch.utils.base import Activation

tverky loss class:

```
class tverkyLoss(smp.utils.base.Loss):
    def __init__(self, alpha, beta, eps=1, activation=None, **kwargs):
        super().__init__(**kwargs)
        self.eps = eps
        self.alpha = alpha
        self.beta = beta
        self.activation = Activation(activation)
    
    def forward(self, y_pr, y_gt):
        y_pr = self.activation(y_pr)
        return tversky_loss(y_gt, y_pr, alpha=self.alpha, beta = self.beta, eps=self.eps)
```

The tversky loss function:

```
def tversky_loss(true, logits, alpha, beta, eps=1e-7):
    num_classes = logits.shape[1]
    if num_classes == 1:
        true_1_hot = torch.eye(num_classes + 1)[true.squeeze(1)]
        true_1_hot = true_1_hot.permute(0, 3, 1, 2).float()
        true_1_hot_f = true_1_hot[:, 0:1, :, :]
        true_1_hot_s = true_1_hot[:, 1:2, :, :]
        true_1_hot = torch.cat([true_1_hot_s, true_1_hot_f], dim=1)
        pos_prob = torch.sigmoid(logits)
        neg_prob = 1 - pos_prob
        probas = torch.cat([pos_prob, neg_prob], dim=1)
    else:
        true_1_hot = torch.eye(num_classes)[true.squeeze(1)]
        true_1_hot = true_1_hot.permute(0, 3, 1, 2).float()
        probas = F.softmax(logits, dim=1)
    true_1_hot = true_1_hot.type(logits.type())
    dims = (0,) + tuple(range(2, true.ndimension()))
    intersection = torch.sum(probas * true_1_hot, dims)
    fps = torch.sum(probas * (1 - true_1_hot), dims)
    fns = torch.sum((1 - probas) * true_1_hot, dims)
    num = intersection
    denom = intersection + (alpha * fps) + (beta * fns)
    tversky_loss = (num / (denom + eps)).mean()
    return (1 - tversky_loss)
```
```
loss = tverkyLoss

train_epoch = smp.utils.train.TrainEpoch(
    model, 
    loss=loss, 
    metrics=metrics_train, 
    optimizer=optimizer,
    device=DEVICE,
    verbose=True,
)

valid_epoch = smp.utils.train.ValidEpoch(
    model, 
    loss=loss, 
    metrics=metrics, 
    device=DEVICE,
    verbose=True,
)
```

However, I am getting the following error:

> 
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-86-5e830269856b> in <module>
>       7     optimizer=optimizer,
>       8     device=DEVICE,
> ----> 9     verbose=True,
>      10 )
>      11 
> 
> /usr/local/lib/python3.6/dist-packages/segmentation_models_pytorch/utils/train.py in __init__(self, model, loss, metrics, optimizer, device, verbose)
>      76             stage_name='train',
>      77             device=device,
> ---> 78             verbose=verbose,
>      79         )
>      80         self.optimizer = optimizer
> 
> /usr/local/lib/python3.6/dist-packages/segmentation_models_pytorch/utils/train.py in __init__(self, model, loss, metrics, stage_name, device, verbose)
>      15         self.device = device
>      16 
> ---> 17         self._to_device()
>      18 
>      19     def _to_device(self):
> 
> /usr/local/lib/python3.6/dist-packages/segmentation_models_pytorch/utils/train.py in _to_device(self)
>      19     def _to_device(self):
>      20         self.model.to(self.device)
> ---> 21         self.loss.to(self.device)
>      22         for metric in self.metrics:
>      23             metric.to(self.device)
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in to(self, *args, **kwargs)
>     424             return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
>     425 
> --> 426         return self._apply(convert)
>     427 
>     428     def register_backward_hook(self, hook):
> 
> AttributeError: 'str' object has no attribute '_apply'


Any idea what is wrong?
