### ISSUE TITLE
[Question] Why do you use kernel_size=3 in Unet Segmentation head

### ISSUE THREAD

**Issue by bonlime** [qubvel/segmentation_models.pytorch#140]
Hi,
I've noticed that in your Unet implementation head uses `kernel_size=3`
https://github.com/qubvel/segmentation_models.pytorch/blob/81dd6a4c9108a56d46bdfb1c9a926217c06406ad/segmentation_models_pytorch/unet/model.py#L79
while all other models do use `kernel_size=1` which makes more sense. Is there any reason why you used `kernel_size=3` or it's just a personal implementation choice?

**Comment by qubvel** [comment]
It just works better for me ;)

**Comment by bonlime** [comment]
Got it
