### ISSUE TITLE
URLError when loading pretrained weights.

### ISSUE THREAD

**Issue by Soo95** [qubvel/segmentation_models.pytorch#144]
> URLError                                  Traceback (most recent call last)
> <ipython-input-5-69b1bd6f752f> in <module>
>       1 model_path = root_dir / 'checkpoints/UNet50_fold0.pth'
>       2 
> ----> 3 model = unet.Unet(encoder_name='resnet50', encoder_weights='imagenet',decoder_use_batchnorm=True, decoder_channels=(256, 128, 64, 32, 16),decoder_attention_type='scse',classes=3,activation=None)
>       4 device = 'cuda:0'
>       5 
> 
> /opt/conda/lib/python3.6/site-packages/segmentation_models_pytorch/unet/model.py in __init__(self, encoder_name, encoder_depth, encoder_weights, decoder_use_batchnorm, decoder_channels, decoder_attention_type, in_channels, classes, activation, aux_params)
>      61             in_channels=in_channels,
>      62             depth=encoder_depth,
> ---> 63             weights=encoder_weights,
>      64         )
>      65 
> 
> /opt/conda/lib/python3.6/site-packages/segmentation_models_pytorch/encoders/__init__.py in get_encoder(name, in_channels, depth, weights)
>      37     if weights is not None:
>      38         settings = encoders[name]["pretrained_settings"][weights]
> ---> 39         encoder.load_state_dict(model_zoo.load_url(settings["url"]))
>      40 
>      41     encoder.set_in_channels(in_channels)
> 
> /opt/conda/lib/python3.6/site-packages/torch/hub.py in load_state_dict_from_url(url, model_dir, map_location, progress, check_hash)
>     490         sys.stderr.write('Downloading: "{}" to {}\n'.format(url, cached_file))
>     491         hash_prefix = HASH_REGEX.search(filename).group(1) if check_hash else None
> --> 492         download_url_to_file(url, cached_file, hash_prefix, progress=progress)
>     493 
>     494     # Note: extractall() defaults to overwrite file if exists. No need to clean up beforehand.
> 
> /opt/conda/lib/python3.6/site-packages/torch/hub.py in download_url_to_file(url, dst, hash_prefix, progress)
>     389     # We use a different API for python2 since urllib(2) doesn't recognize the CA
>     390     # certificates in older Python
> --> 391     u = urlopen(url)
>     392     meta = u.info()
>     393     if hasattr(meta, 'getheaders'):
> 
> /opt/conda/lib/python3.6/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
>     221     else:
>     222         opener = _opener
> --> 223     return opener.open(url, data, timeout)
>     224 
>     225 def install_opener(opener):
> 
> /opt/conda/lib/python3.6/urllib/request.py in open(self, fullurl, data, timeout)
>     524             req = meth(req)
>     525 
> --> 526         response = self._open(req, data)
>     527 
>     528         # post-process response
> 
> /opt/conda/lib/python3.6/urllib/request.py in _open(self, req, data)
>     542         protocol = req.type
>     543         result = self._call_chain(self.handle_open, protocol, protocol +
> --> 544                                   '_open', req)
>     545         if result:
>     546             return result
> 
> /opt/conda/lib/python3.6/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
>     502         for handler in handlers:
>     503             func = getattr(handler, meth_name)
> --> 504             result = func(*args)
>     505             if result is not None:
>     506                 return result
> 
> /opt/conda/lib/python3.6/urllib/request.py in https_open(self, req)
>    1359         def https_open(self, req):
>    1360             return self.do_open(http.client.HTTPSConnection, req,
> -> 1361                 context=self._context, check_hostname=self._check_hostname)
>    1362 
>    1363         https_request = AbstractHTTPHandler.do_request_
> 
> /opt/conda/lib/python3.6/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
>    1318                           encode_chunked=req.has_header('Transfer-encoding'))
>    1319             except OSError as err: # timeout error
> -> 1320                 raise URLError(err)
>    1321             r = h.getresponse()
>    1322         except:
> 
> URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>

Hi, thanks for your work. I appreciate it.
Yesterday, it works perfect, but url error is occured today.
I think loading pretrain weights is a problem, so may I fix url link of pretrained weight?

**Comment by Soo95** [comment]
I think SSL suddenly gives me an issue.
```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```
It solved the problem.

**Comment by khozaimi** [comment]
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000)> for densenet201
