### ISSUE TITLE
Hard Negative Mining

### ISSUE THREAD

**Issue by luistelmocosta** [qubvel/segmentation_models.pytorch#145]
First, I want to thank for this amazing library, I have been using it for a few months and I am completely amazed. I am using Unet and the results are pretty good. However, since I am having some issues with false positives I would like to know if anyone implemented some kind of hard negative mining. It would be really handy and I think it would also be useful for everyone.

Regards

**Comment by bluesky314** [comment]
I use focal loss and tversky loss you come across anything else?

**Comment by FrontierQ** [comment]
> I use focal loss and tversky loss you come across anything else?

Hi,i found that this code has not implemented the focal loss ,Could you please share me the focal loss code?
