### ISSUE TITLE
when I try the example.I used my own data set with a resolution of 720 * 960. During training, I changed the batchsize due to video memory overflow, but I got the following error, what should I do?

### ISSUE THREAD

**Issue by siyangbing** [qubvel/segmentation_models.pytorch#146]
RuntimeError: The size of tensor a (46) must match the size of tensor b (45) at non-singleton dimension 3

please help me

**Comment by siyangbing** [comment]
Epoch: 0

train:   0%|          | 0/45 [00:00<?, ?it/s]
---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-33-917fad5ee646> in <module>
      6 
      7     print('\nEpoch: {}'.format(i))
----> 8     train_logs = train_epoch.run(train_loader)
      9     valid_logs = valid_epoch.run(valid_loader)
     10 

~/PycharmProjects/segmentation_models.pytorch/segmentation_models_pytorch/utils/train.py in run(self, dataloader)
     45             for x, y in iterator:
     46                 x, y = x.to(self.device), y.to(self.device)
---> 47                 loss, y_pred = self.batch_update(x, y)
     48 
     49                 # update loss logs

~/PycharmProjects/segmentation_models.pytorch/segmentation_models_pytorch/utils/train.py in batch_update(self, x, y)
     85     def batch_update(self, x, y):
     86         self.optimizer.zero_grad()
---> 87         prediction = self.model.forward(x)
     88         loss = self.loss(prediction, y)
     89         loss.backward()

~/PycharmProjects/segmentation_models.pytorch/segmentation_models_pytorch/base/model.py in forward(self, x)
     14         """Sequentially pass `x` trough model`s encoder, decoder and heads"""
     15         features = self.encoder(x)
---> 16         decoder_output = self.decoder(*features)
     17 
     18         masks = self.segmentation_head(decoder_output)

~/.conda/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

~/PycharmProjects/segmentation_models.pytorch/segmentation_models_pytorch/fpn/decoder.py in forward(self, *features)
    109 
    110         p5 = self.p5(c5)
--> 111         p4 = self.p4(p5, c4)
    112         p3 = self.p3(p4, c3)
    113         p2 = self.p2(p3, c2)

~/.conda/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

~/PycharmProjects/segmentation_models.pytorch/segmentation_models_pytorch/fpn/decoder.py in forward(self, x, skip)
     31         x = F.interpolate(x, scale_factor=2, mode="nearest")
     32         skip = self.skip_conv(skip)
---> 33         x = x + skip
     34         return x
     35 

RuntimeError: The size of tensor a (46) must match the size of tensor b (45) at non-singleton

**Comment by qubvel** [comment]
Input Image height and width should be divisible by 32, pad or resize it.
