### ISSUE TITLE
How to modify the sample code for multiple classifications. I have modified it according to the readme file, but the result after training is a single classification, and the masks of other categories are empty.

### ISSUE THREAD

**Issue by siyangbing** [qubvel/segmentation_models.pytorch#147]
Thank you very much for any help, your code is so cool!
Hi, I am using the segmentation code from the example. I use my own data set to perfectly segment individual categories. But when I tried to split images of multiple categories, I still just split one category. The image I split includes three categories and a background. What I have done is ACTIVATION = 'softmax2d'
I changed the category to 4 (including background)
The current result is that the output of the training output is 4 masks, but only one class and one background class are included, and the other two classes are empty.
Thank you again!

**Comment by siyangbing** [comment]
The proportion of my four categories in each picture is relatively large, may this be the reason why I cannot train?

**Comment by siyangbing** [comment]
I modified the proportion of different classes of masks in the loss function! The result is good, I can segment the small and large objects I need smoothly

**Comment by pvthuy** [comment]
@siyangbing 
Sorry, how do you visualize test predictions for two classes or more?

**Comment by siyangbing** [comment]
You only need to show the prediction results in the form of pictures. In my case, I have four types of background. The inferred result is [1,4, x, x]. Then I visualized these 4 pictures. I wonder if this framework supports instance splitting.＠pvthuy

**Comment by pvthuy** [comment]
@siyangbing Thanks for your reply.

You meant you visualized for each CLASS one by one? E.g., if you have 4 classes (excluding the background), then you visualized for these 4 classes separately?

I tried with the CamVid dataset for multi-class segmentation, adn modified the code with:

`CLASSES = ['sky', 'building', 'pole', 'road', 'pavement', 
			   'tree', 'signsymbol', 'fence', 'car', 
			   'pedestrian', 'bicyclist', 'unlabelled']`

I also changed this: `ACTIVATION = 'softmax2d'`

I was able to train the defaul FPN model in the code, however when I used this code to visualize for **car**:

`# test dataset without transformations for image visualization
test_dataset_vis = Dataset(
	x_test_dir, y_test_dir, 
	classes=['car'],
)

for i in range(5):
	n = np.random.choice(len(test_dataset))
	
	image_vis = test_dataset_vis[n][0].astype('uint8')
	image, gt_mask = test_dataset[n]
	
	gt_mask = gt_mask.squeeze()
	
	x_tensor = torch.from_numpy(image).to(DEVICE).unsqueeze(0)
	pr_mask = best_model.predict(x_tensor)
	pr_mask = (pr_mask.squeeze().cpu().numpy().round())
		
	visualize(
		image=image_vis, 
		ground_truth_mask=gt_mask, 
		predicted_mask=pr_mask
	)
`

, I got the following error:

**    raise TypeError("Invalid dimensions for image data")
TypeError: Invalid dimensions for image data**
in the function `def visualize(**images)`

Do you know the solution or do you have any implementation for this multi-class segmenation issue?
I appreciate if you can share it? Thanks in advance!

**Comment by siyangbing** [comment]
According to the error message, you have a high probability that the image format is incorrect, the shape may be incorrect, or the pixel data type is incorrect. You can debug and try

**Comment by gireeshkbogu** [comment]
Is this issue solved @siyangbing

**Comment by gireeshkbogu** [comment]
Is this issue solved? @pvthuy 

> TypeError: Invalid dimensions for image data

**Comment by gireeshkbogu** [comment]
> I modified the proportion of different classes of masks in the loss function! The result is good, I can segment the small and large objects I need smoothly

How did you do it?

**Comment by pvthuy** [comment]
@gireeshkbogu 
I tried with the CamVid dataset for multi-class segmentation, and modified the code with:

CLASSES = ['sky', 'building', 'pole', 'road', 'pavement', 'tree', 'signsymbol', 'fence', 'car', 'pedestrian', 'bicyclist', 'unlabelled']

I also changed this: ACTIVATION = 'softmax2d'

**Comment by gireeshkbogu** [comment]
How did you visualize the results? I'm having the same errors as yours 

`for i in range(5):
    n = np.random.choice(len(test_dataset))
    
    image_vis = test_dataset_vis[n][0].astype('uint8')
    image, gt_mask = test_dataset[n]
    
    gt_mask = gt_mask.squeeze()
    
    x_tensor = torch.from_numpy(image).to(DEVICE).unsqueeze(0)
    pr_mask = model.predict(x_tensor)
    pr_mask = (pr_mask.squeeze().cpu().numpy().round())
        
    visualize(
        image=denormalize(image_vis.squeeze()),
        gt_mask=gt_mask.squeeze(),
        pr_mask=pr_mask.squeeze()
    )`

`/root/.local/lib/python3.6/site-packages/segmentation_models_pytorch/base/modules.py:89: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self.activation(x)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-88-deb54cdad8de> in <module>()
     14         image=denormalize(image_vis.squeeze()),
     15         gt_mask=gt_mask.squeeze(),
---> 16         pr_mask=pr_mask.squeeze()
     17     )

6 frames
/usr/local/lib/python3.6/dist-packages/matplotlib/image.py in set_data(self, A)
    697                 or self._A.ndim == 3 and self._A.shape[-1] in [3, 4]):
    698             raise TypeError("Invalid shape {} for image data"
--> 699                             .format(self._A.shape))
    700 
    701         if self._A.ndim == 3:

TypeError: Invalid shape (2, 384, 480) for image data`

**Comment by gireeshkbogu** [comment]
I figured it out. thanks anyway.

```
    visualize(
        image=denormalize(image_vis.squeeze()),
        gt_mask=gt_mask[1].squeeze(),
        pr_mask=pr_mask[1].squeeze()
    )
```

**Comment by Pratyma** [comment]
@siyangbing  I am also having the same problem. I have 8 classes, but the predicted mask has only 2 classes, background and the last class in my list, the remaining are empty. How did you modify the proportion of classes in the loss function? I am using the loss function as below:
`loss = smp.utils.losses.DiceLoss()`

I tried using something like this:

`loss = smp.utils.losses.DiceLoss(class_weights=np.array([0.5, 2,2,2,2,2,2,2]))`

but it did not work, I got an error 

**TypeError: __init__() got an unexpected keyword argument 'class_weights'**

**Comment by geomags3** [comment]
Leave Sigmoid for segmentation in this example, because the multi-class mask is split into different layers.
E.g. (384, 480, N) if you've chosen N classes.

```python
ENCODER = 'se_resnext50_32x4d'
ENCODER_WEIGHTS = 'imagenet'
CLASSES = ['road', 'car', 'bicyclist']
ACTIVATION = 'sigmoid' # Leave Sigmoid for segmentation in this example
DEVICE = 'cuda'


# create segmentation model with pretrained encoder
model = smp.FPN(
    encoder_name=ENCODER, 
    encoder_weights=ENCODER_WEIGHTS, 
    classes=len(CLASSES), 
    activation=ACTIVATION
)

preprocessing_fn = smp.encoders.get_preprocessing_fn(ENCODER, ENCODER_WEIGHTS)
```
---
And  here visualization:
```python
dataset = Dataset(x_train_dir, y_train_dir, classes=['road', 'car', 'bicyclist'])

image, mask = random.choice(dataset) # get random sample
print(image.shape)
print(mask.shape)
visualize(
    image=image, 
    road_mask=mask[:, :, 0].squeeze(),
    cars_mask=mask[:, :, 1].squeeze(),
    bicyclist_mask=mask[:, :, 2].squeeze()
)
```

**Comment by geomags3** [comment]
Visualization after training:

```python
def combine_masks(masks):
  # masks should be size (channels, w, h)
  output_mask = np.zeros(masks[0].shape, dtype=np.uint8)

  for i, mask in enumerate(masks):
    output_mask[mask==1] = i + 1

  return output_mask
```

```python
for i in range(5):
    n = np.random.choice(len(test_dataset))
    
    image_vis = test_dataset_vis[n][0].astype('uint8')
    image, gt_mask = test_dataset[n]
    
    gt_mask = gt_mask.squeeze()
    
    x_tensor = torch.from_numpy(image).to(DEVICE).unsqueeze(0)
    pr_mask = best_model.predict(x_tensor)
    pr_mask = (pr_mask.squeeze().cpu().numpy().round())
        
    visualize(
        image=image_vis, 
        ground_truth_mask=combine_masks(gt_mask), 
        predicted_mask=combine_masks(pr_mask)
    )
```

**Comment by davodogster** [comment]
@geomags3 thanks for the code! it works well
