### ISSUE TITLE
Attention Gated Unet

### ISSUE THREAD

**Issue by luistelmocosta** [qubvel/segmentation_models.pytorch#153]
Hello, did anyone implement a version of Attention Gated Unet for this library? I would love to test this architecture on my segmentation problem. I think it would be a great addition to this project and I am considering trying to develop this if there isn't out of the box implementation

**Comment by qubvel** [comment]
Hi, you can use `attention_type` parameter in unet to upgrade it

**Comment by qubvel** [comment]
https://github.com/qubvel/segmentation_models.pytorch/blob/985ad71581441b6f955600d3c2cbc7ba2f0102d4/segmentation_models_pytorch/unet/model.py#L23

**Comment by luistelmocosta** [comment]
Oh, my bad then. Thank you.
It adds a scSE attention module for what I read. I was reading [this](https://arxiv.org/pdf/1804.03999.pdf) and the architecture is pretty different. Trying to figure out how different they are. Since you're more experienced than me, what are the major differences?

Thank you once again!

**Comment by luistelmocosta** [comment]
And one last question: I am using `resnext50_32x4d` as encoder. If I want to use the attention model, do I need to change to `se_resnext50_32x4d` ?
