### ISSUE TITLE
Not able to import deeplabv3

### ISSUE THREAD

**Issue by asdspal** [qubvel/segmentation_models.pytorch#155]
I'm getting an error `AttributeError: module  has no attribute 'DeepLabV3'`.
I've tried both pypi and latest source code available from github. Can please someone help me?

**Comment by qubvel** [comment]
Use `-U` flag while installing from source. PyPI package haven't released yet.

**Comment by asdspal** [comment]
It is working now. I had to uninstall and then install again from the github latest source. Thanks.
