### ISSUE TITLE
When trying to dload efficientnet encoder: HTTP Error 403: The specified account is disabled.

### ISSUE THREAD

**Issue by suitre77** [qubvel/segmentation_models.pytorch#156]
Hello qubvel and guys,

when I try to load any efficientnet encoder I get the specified HTTP error.
With other encoders this problem doesn't appear. 

Kind regards

---------------------------------------------------------------------------
ENCODER = 'efficientnet-b4'
ENCODER_WEIGHTS = 'imagenet'

preprocessing_fn = smp.encoders.get_preprocessing_fn(ENCODER, ENCODER_WEIGHTS)

Downloading: "https://publicmodels.blob.core.windows.net/container/aa/efficientnet-b4-6ed6700e.pth" to /dev/.../.cache/torch/checkpoints/efficientnet-b4-6ed6700e.pth

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-15-1f08010ce4b4> in <module>
     10     encoder_weights=ENCODER_WEIGHTS,
     11     classes=len(CLASSES),
---> 12     activation=ACTIVATION,
     13 )
     14 

~/.local/lib/python3.6/site-packages/segmentation_models_pytorch/fpn/model.py in __init__(self, encoder_name, encoder_depth, encoder_weights, decoder_pyramid_channels, decoder_segmentation_channels, decoder_merge_policy, decoder_dropout, in_channels, classes, activation, upsampling, aux_params)
     62             in_channels=in_channels,
     63             depth=encoder_depth,
---> 64             weights=encoder_weights,
     65         )
     66 

~/.local/lib/python3.6/site-packages/segmentation_models_pytorch/encoders/__init__.py in get_encoder(name, in_channels, depth, weights)
     37     if weights is not None:
     38         settings = encoders[name]["pretrained_settings"][weights]
---> 39         encoder.load_state_dict(model_zoo.load_url(settings["url"]))
     40 
     41     encoder.set_in_channels(in_channels)

~/.local/lib/python3.6/site-packages/torch/hub.py in load_state_dict_from_url(url, model_dir, map_location, progress, check_hash)
    490         sys.stderr.write('Downloading: "{}" to {}\n'.format(url, cached_file))
    491         hash_prefix = HASH_REGEX.search(filename).group(1) if check_hash else None
--> 492         download_url_to_file(url, cached_file, hash_prefix, progress=progress)
    493 
    494     # Note: extractall() defaults to overwrite file if exists. No need to clean up beforehand.

~/.local/lib/python3.6/site-packages/torch/hub.py in download_url_to_file(url, dst, hash_prefix, progress)
    389     # We use a different API for python2 since urllib(2) doesn't recognize the CA
    390     # certificates in older Python
--> 391     u = urlopen(url)
    392     meta = u.info()
    393     if hasattr(meta, 'getheaders'):

/usr/lib/python3.6/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    221     else:
    222         opener = _opener
--> 223     return opener.open(url, data, timeout)
    224 
    225 def install_opener(opener):

/usr/lib/python3.6/urllib/request.py in open(self, fullurl, data, timeout)
    530         for processor in self.process_response.get(protocol, []):
    531             meth = getattr(processor, meth_name)
--> 532             response = meth(req, response)
    533 
    534         return response

/usr/lib/python3.6/urllib/request.py in http_response(self, request, response)
    640         if not (200 <= code < 300):
    641             response = self.parent.error(
--> 642                 'http', request, response, code, msg, hdrs)
    643 
    644         return response

/usr/lib/python3.6/urllib/request.py in error(self, proto, *args)
    568         if http_err:
    569             args = (dict, 'default', 'http_error_default') + orig_args
--> 570             return self._call_chain(*args)
    571 
    572 # XXX probably also want an abstract factory that knows when it makes

/usr/lib/python3.6/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    502         for handler in handlers:
    503             func = getattr(handler, meth_name)
--> 504             result = func(*args)
    505             if result is not None:
    506                 return result

/usr/lib/python3.6/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    648 class HTTPDefaultErrorHandler(BaseHandler):
    649     def http_error_default(self, req, fp, code, msg, hdrs):
--> 650         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    651 
    652 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 403: The specified account is disabled.

**Comment by qubvel** [comment]
Update efficientnet-pytorch to latest version

**Comment by suitre77** [comment]
ah didn't see that update there. Thank you
