### ISSUE TITLE
incompatible when TorchVison update to 0.3

### ISSUE THREAD

**Issue by seefun** [qubvel/segmentation_models.pytorch#16]
When I update the torchvison lib to version 0.3, I meet this problem:

ImportError: cannot import name 'cfg' from 'torchvision.models.vgg' 
 
And [torchvision 0.3](https://pytorch.org/blog/torchvision03/) add some pretrained segmentation models, can them be added into smp APIs?

**Comment by seefun** [comment]
And In training, loss and metric are accumulated rather than mean value after I update torchvision to version0.3.

**Comment by qubvel** [comment]
Ok, will try to add it)

**Comment by lebionick** [comment]
@qubvel btw this `ImportError` can be fixed just by renaming `cfg` to `cfgs` :)

**Comment by qubvel** [comment]
fixed
