### ISSUE TITLE
Anyone have examples of training classification head?

### ISSUE THREAD

**Issue by gjbit** [qubvel/segmentation_models.pytorch#162]
I know how to create the auxiliary classification head. But how to train it along with segmentation head? I am lost in how to define the loss...
Could anyone give me a example code of training the classification head?

**Comment by gjbit** [comment]
It seems that I should modify the TrainEpoch class to add loss for classification... should I?

**Comment by AlexanderSlav** [comment]
Hi, @gjbit , any progress ?

**Comment by gizemtanriver** [comment]
Hi, I am also trying to add the auxiliary classification head but when I run train I get the following error. So it seems that the loss needs to be modified? For segmentation I have been using DiceLoss. Did you figure out how to fix? Thanks!

```
Epoch: 0
train:   0%|          | 0/61 [00:03<?, ?it/s]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-160a3b6d3663> in <module>()
     10 
     11     print('\nEpoch: {}'.format(i))
---> 12     train_logs = train_epoch.run(train_loader)
     13     valid_logs = valid_epoch.run(valid_loader)
     14 

4 frames
/usr/local/lib/python3.6/dist-packages/segmentation_models_pytorch/utils/functional.py in f_score(pr, gt, beta, eps, threshold, ignore_channels)
     55     pr, gt = _take_channels(pr, gt, ignore_channels=ignore_channels)
     56 
---> 57     tp = torch.sum(gt * pr)
     58     fp = torch.sum(pr) - tp
     59     fn = torch.sum(gt) - tp

TypeError: only integer tensors of a single element can be converted to an index
```

**Comment by anmol4210** [comment]
I'm also facing the same issue. Does anyone has a solution for this?

**Comment by zsc1104** [comment]
I'm also facing the same issue. Does anyone has a solution for this?
