### ISSUE TITLE
Removed layers are still trained

### ISSUE THREAD

**Issue by JulienMaille** [qubvel/segmentation_models.pytorch#171]
I've been working on a Resnet with only 3 layers and noticed pth size and training size did not change much.
The reason is layer4 and layer5 of the encoder are still trained.
We need a dynamic way to do this:
```
self.layer3.requires_grad = False
self.layer4.requires_grad = False
```
or
```
del self.layer3
del self.layer4
```

**Comment by qubvel** [comment]
Еhank you for your comment, I will correct it

**Comment by JulienMaille** [comment]
I've done something to handle this in my fork (not sure if it is the cleanest way, I'm very new to Python) https://github.com/JulienMaille/segmentation_models.pytorch/commit/fd4b610726538212316af93af5e84206aef37500
