### ISSUE TITLE
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm) ??

### ISSUE THREAD

**Issue by edwardcho** [qubvel/segmentation_models.pytorch#172]
I tested your sample code.

source code :
https://github.com/qubvel/segmentation_models/blob/master/examples/multiclass%20segmentation%20(camvid).ipynb

I met this error.
..
Epoch: 0
train:   2%|██▋                                                                                                                        | 1/46 [00:01<01:10,  1.56s/it, dice_loss - 0.9637, iou_score - 0.01636]ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
...

I couln't find the reason.....

**Comment by TimbusCalin** [comment]
This is because of the Docker .... ensure you specify the parameter shm_size
