### ISSUE TITLE
I want to save pretrained-model in local-directory.

### ISSUE THREAD

**Issue by edwardcho** [qubvel/segmentation_models.pytorch#179]
Hello Sir,

I tested your sample code. (car_segmentation)

At first, when I run your code,

Downloading: "http://data.lip6.fr/cadene/pretrainedmodels/se_resnext50_32x4d-a260b3a4.pth" to /home/itsme/.cache/torch/checkpoints/se_resnext50_32x4d-a260b3a4.pth

I want to save this files on my local directory and I want to use this saved-file at next-time.
How to operate it??

Thanks.

**Comment by qubvel** [comment]
use
```python
model = smp.FPN(encoder_name="se_resnext50_32x4d", encoder_weights=None)
model.encoder.load_sate_dict("/home/itsme/.cache/torch/checkpoints/se_resnext50_32x4d-a260b3a4.pth")
```
