### ISSUE TITLE
Integration with pytorch_image_models?

### ISSUE THREAD

**Issue by AlbuquerqueRafael** [qubvel/segmentation_models.pytorch#182]
There's an easy / fast way to integrate / substitute EfficientNet Models from  [pytorch_image_models](https://github.com/rwightman/pytorch-image-models) in Segmentation Models EfficientNetEncoder?

If so. How should I do that? 

Anyway, I think that an integration with the pytorch_image_models library would be a nice improvement for SMP Library.

Thanks in advance. ^^

**Comment by qubvel** [comment]
Hi @AlbuquerqueRafael 
Not sure the way is simple, but it is definitely exists. You can look at another encoders in repo and try to integrate this one. If you succeeded, PR would be very appreciated :smile:

**Comment by qubvel** [comment]
merged in master #189
