### ISSUE TITLE
Extracting feature maps of FPN

### ISSUE THREAD

**Issue by tharindurmt** [qubvel/segmentation_models.pytorch#191]
Hi,
Can anyone please let me know whether I can use this repo to extract the feature map outputs of the FPN layers (namely the bottom most FPN layer with relatively high resolution)? Do I have to register a hook for that layer or are there any other methods of achieving this?

Thanks.

**Comment by howard-mahe** [comment]
Hello,

You are interested in extracting the `p5, p4, p3, p2` features of the FPNDecoder (see [fpn/decoder.py#L110-113](https://github.com/qubvel/segmentation_models.pytorch/blob/master/segmentation_models_pytorch/fpn/decoder.py#L110-L113)). You cannot immediately extract these features using the `FPN` class which inherits from `SegmentationModel`.

Feel free to define your own custom `FPN` class and corresponding custom `FPNDecoder` class. Here follows what you would have done:
```python
# add this line in `segmentation_models_pytorch/__init__.py`
from .myfpn import MyFPN
```
```python
# segmentation_models_pytorch/myfpn/__init__.py
from .model import MyFPN
```
```python
# segmentation_models_pytorch/myfpn/fpnfeatures.py
from ..fpn import FPN


class FPNFeatures(FPN):
    def __init__(
            self,
            encoder_channels,
            encoder_depth=5,
            pyramid_channels=256,
    ):
        super().__init__(encoder_channels, encoder_depth, pyramid_channels)
        del self.seg_blocks, self.merge, self.dropout

    def forward(self, *features):
        c2, c3, c4, c5 = features[-4:]

        p5 = self.p5(c5)
        p4 = self.p4(p5, c4)
        p3 = self.p3(p4, c3)
        p2 = self.p2(p3, c2)

        return p2, p3, p4, p5
```
```python
# segmentation_models_pytorch/myfpn/model.py
import torch.nn as nn
from typing import Optional
from .fpnfeatures import FPNFeatures
from ..encoders import get_encoder
from ..base import initialization as init


class MyFPN(nn.Module):

    def __init__(
        self,
        encoder_name: str = "resnet34",
        encoder_depth: int = 5,
        encoder_weights: Optional[str] = "imagenet",
        pyramid_channels: int = 256,
        in_channels: int = 3,
    ):
        super().__init__()

        self.encoder = get_encoder(
            encoder_name,
            in_channels=in_channels,
            depth=encoder_depth,
            weights=encoder_weights,
        )

        self.fpn = FPNFeatures(
            encoder_channels=self.encoder.out_channels,
            encoder_depth=encoder_depth,
            pyramid_channels=fpn_pyramid_channels,
        )

        self.name = "fpn-{}".format(encoder_name)
        self.initialize()

    def initialize(self):
        init.initialize_decoder(self.fpn)

    def forward(self, x):
        """Sequentially pass `x` trough model`s encoder and FPN"""
        features = self.encoder(x)
        fpn_features = self.fpn(*features)

        return fpn_features

    def predict(self, x):
        """Inference method. Switch model to `eval` mode, call `.forward(x)` with `torch.no_grad()`
        Args:
            x: 4D torch tensor with shape (batch_size, channels, height, width)
        Return:
            prediction: 4D torch tensor with shape (batch_size, classes, height, width)
        """
        if self.training:
            self.eval()

        with torch.no_grad()
            x = self.forward()

        return x
```

**Comment by rmtr** [comment]
@howard-mahe Thank you very much for the elaborate and quick response. I will implement this and see how it goes. Thanks again!

**Comment by rmtr** [comment]
Hi @howard-mahe ,

Since the GPU servers were offline I could not test the solution until today. I had to do couple of minor changes to the code as it was not working straightaway. So, here are the changes I did:

In 
```# segmentation_models_pytorch/myfpn/model.py```
Changed the FPNFeatures constructor as follows since it gave me key errors.

```
self.fpn = FPNFeatures(
            encoder_name = encoder_name, # Added
            encoder_weights = encoder_weights, # Added
            encoder_channels=self.encoder.out_channels,
            encoder_depth=encoder_depth,
            pyramid_channels=pyramid_channels,#Changed from fpn_pyramid_channels,
        )
```

Then changed the constructor in 
``` segmentation_models_pytorch/myfpn/fpnfeatures.py ``` 
accordingly as follows:
 ```super().__init__(encoder_channels, encoder_depth, pyramid_channels) ``` 
to
```super().__init__(encoder_name, encoder_channels, encoder_weights, encoder_depth, pyramid_channels)``` 


Now it gives me an error in concatenation
``` 
File "************/lib/python3.7/site-packages/segmentation_models_pytorch/encoders/_base.py", line 18, in out_channels
    return self._out_channels[: self._depth + 1]
TypeError: can only concatenate tuple (not "int") to tuple
``` 

I feel I am heading towards the wrong direction here. Being relatively new with both deep learning and python, I was wondering whether you could help me to figure this out. 

Thank you.
