### ISSUE TITLE
RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'target' in call to _thnn_nll_loss2d_forward

### ISSUE THREAD

**Issue by qianjinhao** [qubvel/segmentation_models.pytorch#197]
when i change the example code loss from DiceLoss to CrossEntropyLoss：
loss = smp.utils.losses.DiceLoss()
loss = smp.utils.losses.CrossEntropyLoss()
i got this error:
Traceback (most recent call last):
  File "train.py", line 131, in <module>
    train_logs = train_epoch.run(train_loader)
  File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/segmentation_models_pytorch/utils/train.py", line 47, in run
    loss, y_pred = self.batch_update(x, y)
  File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/segmentation_models_pytorch/utils/train.py", line 88, in batch_update
    loss = self.loss(prediction, y)
  File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py", line 2021, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py", line 1840, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'target' in call to _thnn_nll_loss2d_forward

**Comment by kevinYitshak** [comment]
During data loading, the target should be of type Long for cross-entropy loss.
In the dataloader set:
target = target.to(dtype=torch.long) 
Whereas, in case Dice, BCEloss, or BCEWithLogitsLoss target should of type Float.
For more details: Check this link [https://discuss.pytorch.org/t/runtimeerror-expected-object-of-scalar-type-long-but-got-scalar-type-float-when-using-crossentropyloss/30542](https://discuss.pytorch.org/t/runtimeerror-expected-object-of-scalar-type-long-but-got-scalar-type-float-when-using-crossentropyloss/30542)

**Comment by KnifeDing** [comment]
> During data loading, the target should be of type Long for cross-entropy loss.
> In the dataloader set:
> target = target.to(dtype=torch.long)
> Whereas, in case of Dice, BCEloss, or BCEWithLogitsLoss target should of type Float.
> For more details: Check this link https://discuss.pytorch.org/t/runtimeerror-expected-object-of-scalar-type-long-but-got-scalar-type-float-when-using-crossentropyloss/30542

how to solve this problem based on the tutorial code?

**Comment by KnifeDing** [comment]
> when i change the example code loss from DiceLoss to CrossEntropyLoss：
> loss = smp.utils.losses.DiceLoss()
> loss = smp.utils.losses.CrossEntropyLoss()
> i got this error:
> Traceback (most recent call last):
> File "train.py", line 131, in
> train_logs = train_epoch.run(train_loader)
> File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/segmentation_models_pytorch/utils/train.py", line 47, in run
> loss, y_pred = self.batch_update(x, y)
> File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/segmentation_models_pytorch/utils/train.py", line 88, in batch_update
> loss = self.loss(prediction, y)
> File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 916, in forward
> ignore_index=self.ignore_index, reduction=self.reduction)
> File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py", line 2021, in cross_entropy
> return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
> File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py", line 1840, in nll_loss
> ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
> RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'target' in call to _thnn_nll_loss2d_forward

how to solve this problem based on the tutorial code?
