### ISSUE TITLE
New ResNeSt encoder?

### ISSUE THREAD

**Issue by iliailmer** [qubvel/segmentation_models.pytorch#200]
Would it be useful to add a new architecture to the encoder collection of the package? [Here](https://arxiv.org/abs/2004.08955) is the paper.

It seems promising and goes well with already established frameworks of Resnets.

**Comment by qubvel** [comment]
Hi, it is already added, but not merged in master yet, see resnest branch

**Comment by iliailmer** [comment]
@qubvel Ah, makes perfect sense! Thanks.
