### ISSUE TITLE
Predictions are all black

### ISSUE THREAD

**Issue by talatccan** [qubvel/segmentation_models.pytorch#211]
Hi,

I've trained two different custom dataset with tutorial in example. First dataset results are very good. But i get black predictions with another dataset. I didnt change anything on tutorial. How can i fix this problem?

![40_epoch_results_lesion_crop](https://user-images.githubusercontent.com/10474206/82402703-c8d50700-9a65-11ea-942c-e07b7adfa533.png)

Update
----------------------------------------

Train, Test, Val images and masks sizes are (h=256, w=512) but predictions and saved masks sizes are (h=384, w=512). They changed suddenly. It didnt happen like this with my first train which trained another dataset.

![image](https://user-images.githubusercontent.com/10474206/82406807-3c7c1180-9a70-11ea-9203-4289894ba4e0.png)

Update 2
----------------------------------------
I've solved problem. I used UNET instead of FPN and predictions are very promising.

**Comment by Jo-Pan** [comment]
I am using FPN and having the same issue. After switching to UNet, all is fine. But still try to figure out how to implement UNet.
