### ISSUE TITLE
Preprocessing for single channel images

### ISSUE THREAD

**Issue by ckolluru** [qubvel/segmentation_models.pytorch#215]
Hi,

I'm looking for a pre-processing function for single channel images. Is there one available in this repository? 

Thanks,
Chaitanya

**Comment by ramarlina** [comment]
Hi Chaitanya,

You can use set_in_channels:

> model.encoder.set_in_channels(1)
model.forward(torch.rand(1,1,256,256))

Mendrika

**Comment by ckolluru** [comment]
Hi Mendrika,

Using the set_in_channels seems to modify the kernel weights for the first convolution based on the number of channels. I'm looking for the right way to pre-process my images prior to training, and how that should be done if my images are not 3 channels.

**Comment by ramarlina** [comment]
I see what you're saying. I don't know of one "right" way to pre-process multi-channel input data. It depends on a lot of things. One question is what do the extra channels represent?

The way I would approach it would be to cross-validate different approaches, then decide what works best for you based on the results. 

This might help, I ran an experiment on different strategies of integrating RGB + Elevation for aerial imagery segmentation:
https://www.slideshare.net/MendrikaRamarlina/exploring-fused-convolutional-neural-networks-for-aerial-imagery-segmentation

My 4th channel was elevation data. In that scenario, adding a 4-to-3 convolution before the input layer of the network yielded the best results.

- Mendrika
