### ISSUE TITLE
Can a standard model (e.g. resnet) pretrained on another dataset be used as a backbone?

### ISSUE THREAD

**Issue by catweis** [qubvel/segmentation_models.pytorch#229]
Thank you very much for this great work. Is it possible to use a standard model (e.g. resnet) as a backbone that is pre-trained on another classification task? As far as I can see, I can only use the imagenet weights? For instance, I have a well-performing resnet (for a classification task) that I want to use for a segmentation task.
Thank you very much in advance for your answer.

**Comment by qubvel** [comment]
Hi, you can load your own weights using `model.encoder.load_state_dict(...)` if you use same model for classification task training as backbone

**Comment by catweis** [comment]
Hi, thank you very much for your fast answer. I will use that. With kind regards.
