### ISSUE TITLE
Does this framework support 3D images?

### ISSUE THREAD

**Issue by MA-Aaron** [qubvel/segmentation_models.pytorch#230]
For example, MRi images which is 3D.

**Comment by Optimox** [comment]
I would be interested to know how we can use 3D images as well!

**Comment by kotete** [comment]
I'm also trying to train MRI images! Have you tried 3D images on the framework successfully?

**Comment by Optimox** [comment]
You can try this : https://github.com/wolny/pytorch-3dunet

**Comment by shijianjian** [comment]
Any plans on this?

**Comment by sushant097** [comment]
Does this support medical imaging segmentation which is 3D? Anyone pls?
