### ISSUE TITLE
How to get size of dataset after augmentation?

### ISSUE THREAD

**Issue by talatccan** [qubvel/segmentation_models.pytorch#231]
Hi,

I'm trying to get size of dataset after applied augmentation. In this context I have printed sizes of dataset before and after augmentation. But both are same. Where did i do wrong?

PS: Orijinal size of dataset is 157.

![image](https://user-images.githubusercontent.com/10474206/87063338-e5482100-c216-11ea-84bc-e4030c842a2a.png)

**Comment by JulienMaille** [comment]
Augmentations are random, on-the-fly transformations applied on the dataset images
