### ISSUE TITLE
Model zoo validation strategy.

### ISSUE THREAD

**Issue by AllentDan** [qubvel/segmentation_models.pytorch#232]
Hi, qubvel. Thank you for the great job you have done, it helped me a lot. But I am a little confused that in your model zoo for Pascal VOC segmentation, you preserved aspect ratio of test image. However, for deeplabv3+, it gives me error that for "torch.cat([aspp_features, high_res_features], dim=1)". So, have you croped the image or implemented other operation after resizing while keeping aspect ratio?

**Comment by vaishali-77** [comment]
Hey AllentDan,
I would like to use deeplabv3, but I keep getting error keyword error. Since you have used it, could you help me out here? Thanks in advance.
In the code, I change the following
model = smp.FPN
model =smp.DeepLabV3

**Comment by AllentDan** [comment]
Hi, @vaishali-77 . I didn't quite get your meaning. But when I just use the code like "model = smp.FPN()
model = smp.DeepLabV3()", it works fine. Actually, it seems that FPN and DeepLab are independant. Maybe you could change the code inside the api if you want to do something special.

**Comment by vaishali-77** [comment]
Hey @AllentDan ,
I want to use DeepLabV3 instead of the FPN model in my code. But like you said,when I do
model = smp.DeepLabV3() I get the following error

AttributeError: module 'segmentation_models_pytorch' has no attribute 'DeepLabV3'

**Comment by AllentDan** [comment]
@vaishali-77 It could be the installation problem. You can also try this: "model = smp.deeplabv3.DeepLabV3()".

**Comment by vaishali-77** [comment]
@AllentDan 
thanks again,
I still continue to have the same error, I even tried segmentation models from source again but still doesn't work
