### ISSUE TITLE
dice_loss - -ve, iou_score - -ve

### ISSUE THREAD

**Issue by PareshKamble** [qubvel/segmentation_models.pytorch#234]
Dear @qubvel 
Thank you for this amazing library.

I tried to build a UNet model with ResNet152 as a backbone and 1 class 'person'.
I used input images of 512x512 as input and corresponding binary masks.
I used your sample code of CamVid notebook as a base and did some tuning in the same to make it work for my dataset.
However, I am getting dice loss and iou score as negative. 
`dice_loss - -10.63, iou_score - -1.209`
Have you ever come across such an issue?
Can you suggest some solution for this?

**Comment by suitre77** [comment]
Just got the same problem, currently no idea what the reason is....

**Comment by qubvel** [comment]
Make sure your mask is scaled to [0, 1] values, not 0 and 255.

**Comment by Interstell** [comment]
Check if your mask tensor has shape (1, N, M), not (N, M), it worked for me.

**Comment by suitre77** [comment]
Yeah, I also had am alterring tensor shape

**Comment by junjun1023** [comment]
Just met the same problem, dice-loss becoming negative and iou becoming more than 1
I have checked the following points:
1. Shape of input image/mask tensor
2. Scaled value to [0, 1]
3. Use activation function for model or losses, instead of both

But the problem still exists...

**Comment by junjun1023** [comment]
I resolved my problem. It turns out that the shape of my groundtruth is [batch, 3, N, M] while my prediction's is [batch, 1, N, M].
