### ISSUE TITLE
how to use timm-efficientnet models?

### ISSUE THREAD

**Issue by mobassir94** [qubvel/segmentation_models.pytorch#237]
i tried : model = smp.Unet('timm-efficientnet-b4', encoder_weights="imagenet", activation=None)

and  i get : 

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-36-213637e76cc6> in <module>()
----> 1 model = smp.Unet('timm-efficientnet-b4', encoder_weights="imagenet", activation=None)

1 frames
/usr/local/lib/python3.6/dist-packages/segmentation_models_pytorch/unet/model.py in __init__(self, encoder_name, encoder_depth, encoder_weights, decoder_use_batchnorm, decoder_channels, decoder_attention_type, in_channels, classes, activation, aux_params)
     61             in_channels=in_channels,
     62             depth=encoder_depth,
---> 63             weights=encoder_weights,
     64         )
     65 

/usr/local/lib/python3.6/dist-packages/segmentation_models_pytorch/encoders/__init__.py in get_encoder(name, in_channels, depth, weights)
     30 
     31 def get_encoder(name, in_channels=3, depth=5, weights=None):
---> 32     Encoder = encoders[name]["encoder"]
     33     params = encoders[name]["params"]
     34     params.update(depth=depth)

KeyError: 'timm-efficientnet-b4'

**Comment by jaewooklee93** [comment]
I've got the same problem.

Try below,

```Python
pip uninstall segmentation-models-pytorch

pip install git+https://github.com/qubvel/segmentation_models.pytorch
```

**Comment by mobassir94** [comment]
it works,thank you @jaewooklee93
