### ISSUE TITLE
DeeplabV3plus

### ISSUE THREAD

**Issue by jing-tian-2019** [qubvel/segmentation_models.pytorch#238]
Is there anyway I could use XceptionEncoder in DeeplabV3plus?
I am stopped by the error "Xception encoder does not support dilated mode due to pooling operation for downsampling!"

**Comment by wangshihuang** [comment]
Hi, Have you solved it。

**Comment by simon-hoon** [comment]
this problem still remains.

**Comment by tudragon154203** [comment]
Same problem with DeeplabV3

**Comment by maorong-wang** [comment]
Same issue. Any solutions?

**Comment by cengizhunter** [comment]
same here

**Comment by qubvel** [comment]
Try to install latest version from source and use xception from timm, some versions support dilation

**Comment by danushv07** [comment]
This issue is not solved so opening it again.

**Comment by danushv07** [comment]
There seems to be a solution here (https://github.com/qubvel/segmentation_models.pytorch/issues/730)

**Comment by redeemme** [comment]
this problem still remains.
