### ISSUE TITLE
unet training error

### ISSUE THREAD

**Issue by janetwise** [qubvel/segmentation_models.pytorch#239]
Modified the car seg ipynb file with unet:
model = smp.Unet() and commented out the original model
#model = smp.Unet('resnet34', classes=3, activation='softmax') and the preprocessing as I want to train from scratch.
Got errors runing the training epoch: 
RuntimeError: Given groups=1, weight of size 64 3 7 7, expected input[8, 320, 320, 3] to have 3 channels, but got 320 channels instead

Can anyone help? Thanks in advance.

**Comment by sinistro25** [comment]
Input shape should be (n_samples,n_channels,height,width), the convention is channels first in [pytorch conv2D](https://pytorch.org/docs/master/generated/torch.nn.Conv2d.html).

**Comment by sainatarajan** [comment]
@janetwise Take a look at torch.permute() operation and then change the order from current one to [num_batch, num_channels, height, width].
