### ISSUE TITLE
How to write and use custom loss functions in this library?

### ISSUE THREAD

**Issue by PareshKamble** [qubvel/segmentation_models.pytorch#244]
Hi @qubvel,
I am working on [Deep Image Matting](https://arxiv.org/abs/1703.03872). 
I want to use alpha prediction loss and composition loss for the same. 
However, in your repository, I could not find a way to write/use a custom loss functions for these two losses.
I could only find dice and jaccard losses.
Can you please provide me a solution to do the same using this amazing library or a suitable alternative?
Thanking you in anticipation!

**Comment by azkalot1** [comment]
You can use https://github.com/BloodAxe/pytorch-toolbelt JointLoss . Will work for almost any loss function.

**Comment by PareshKamble** [comment]
@azkalot1 
Thank you for your response.
I shall give it a try for sure.

**Comment by TimbusCalin** [comment]
I want to use jaccard_loss and binary_crossentropy for binary segmentation.

`focal_jaccard = L.JointLoss(L.FocalLoss(), L.JaccardLoss(mode='binary'))`

But this is throwing the error : 
ValueError: Target size (torch.Size([4, 1, 360, 640])) must be the same as input size (torch.Size([4, 360, 640]))
