### ISSUE TITLE
How to load a trained model for training again?

### ISSUE THREAD

**Issue by PareshKamble** [qubvel/segmentation_models.pytorch#252]
Hi @qubvel 
I trained a UNet+Xception (backbone) pre-trained on ImageNet for 250 epochs on a custom person dataset.
It took me 6 long days to train it on my 2080Ti GPU.
I tweaked your code and introduced Dropout in the last 2 layers of Decoder network of the model.
The model is working well and segmenting wisely but can be improved further.

However, now I want to train the saved model further on a still bigger dataset but don't want to train it from scratch to save time. 
How can I do this using smp? I mean, any provision for this?

I tried loading the model using `torch.load` and tried training it further, but got the following error:
`AttributeError: 'DecoderBlock' object has no attribute 'Drop'`

Can you suggest a solution for this issue?

Thanking you in anticipation!

**Comment by SravanChittupalli** [comment]
use this command to save weights
`torch.save(model.state_dict() , "<path where you want to store weightsl> ")`

next, do 
1) `checkpoint = torch.load( "<path to the saved model> " )`
2) Then create an object of your model. `model = MODEL_CLASS_NAME()`. 
3) model.load_state_dict()

This will load all the weights and then you can continue with your training loop

**Comment by purijs** [comment]
> 3\. model.load_state_dict()

How is this using the `checkpoint`?

**Comment by aliab3d** [comment]
@purijs: the third step is more precisely: 3. model.load_state_dict(checkpoint)
