### ISSUE TITLE
Can we use pre trained segmentation models available in this repo directly for inference?  i.e without any further training

### ISSUE THREAD

**Issue by shubh1608** [qubvel/segmentation_models.pytorch#258]
I am looking for Pre-trained segmentation models and I don't want to train them. I am looking to use them directly for inference.
Is there any way to use models available in this repo directly for inference? if not do you mind guiding me to resource where I can get pre-trained segmentation models directly for inference.

Image classification and Detection pre-trained models are comparatively easy to get, but i am finding it hard to collect image segmentation pre-trained, models.

**Comment by sainatarajan** [comment]
You could use the pre-trained models if the classes you want, match the classes on which the model was trained on.
