### ISSUE TITLE
How to use fwiou metrics?

### ISSUE THREAD

**Issue by skyqwe123** [qubvel/segmentation_models.pytorch#259]
Thanks @qubvel . I learned a lot from this project. But I am not understand how to calculcate the fwiou based on iou in this work(confusion_matrix is not used)

**Comment by sainatarajan** [comment]
You can explore [this](https://github.com/martinkersner/py_img_seg_eval) repo.

**Comment by skyqwe123** [comment]
Thanks for your reply! I learned a lot.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "sainatarajan"<notifications@github.com&gt;; 
发送时间: 2020年9月26日(星期六) 凌晨0:16
收件人: "qubvel/segmentation_models.pytorch"<segmentation_models.pytorch@noreply.github.com&gt;; 
抄送: "李慧敏"<372952556@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [qubvel/segmentation_models.pytorch] How to use fwiou metrics? (#259)





 
You can explore this repo.
