### ISSUE TITLE
How to PSPNET train with single channels input?

### ISSUE THREAD

**Issue by parulML** [qubvel/segmentation_models.pytorch#26]
First of all, amazing work in both of your segmentation libraries. It saved me a lot of time.
I want to train PSPNET using single channel grayscale image but not able to figure out how to do it. In your keras documentation you have already mentioned the same. It will be really helpful if you could suggest the same here.
Thanks

**Comment by qubvel** [comment]
Hi @parulML 
1) You can convert grayscale to RGB (e.g. by duplicating grayscale 3 times)
2) You can replace first model conv layer
