### ISSUE TITLE
EfficientNet versioning issue

### ISSUE THREAD

**Issue by mfernezir** [qubvel/segmentation_models.pytorch#260]
Hi!

I have a model trained by using the current 0.1.0 version of this library.

Later on, I loaded the model checkpoint in the new environment that also uses the 0.1.0 version. Model performance downgraded substantially.

The reason is that your `requirements.txt` mentions `efficientnet-pytorch>=0.6.3`. My old training environment used the 0.6.3 version. However, the current one from Aug 25 is 0.7.0. So, when I specified 0.1.0 as a requirement, it wasn't the same thing.

0.1.0 with 0.6.3 is a breaking difference when compared to 0.1.0 and 0.7.0.

Maybe it should be `efficientnet-pytorch==0.6.3` if still staying at 0.1.0?

**Comment by qubvel** [comment]
Thanks
