### ISSUE TITLE
DeepLab missing from latest pip version

### ISSUE THREAD

**Issue by agaldran** [qubvel/segmentation_models.pytorch#261]
Hi,

For some reason the DeepLab encoder has disappeared from the library? If I install following the instructions in your readme, and try to import it, it says it does not exist. After installing, this are the contents of the file `__init__.py`:

```
from .unet import Unet
from .linknet import Linknet
from .fpn import FPN
from .pspnet import PSPNet

from . import encoders
from . import utils

from .__version__ import __version__
```

It also seems that PAN is missing. Is there any work-around to get them back?

Thanks for your library!

**Comment by qubvel** [comment]
fixed in 0.1.1
