### ISSUE TITLE
No py.typed file

### ISSUE THREAD

**Issue by Vozf** [qubvel/segmentation_models.pytorch#275]
With the introduction of type stubs (thanks again for those!), smp should include a blank file called "py.typed", as stated in PEP 561.

This indicates to 'mypy' and other static type checkers that it should use the stubs included in the package. WIthout it, mypy will simply report that it 
'inference.py:10: error: Skipping analyzing 'segmentation_models_pytorch': found module but no type hints or library stubs''

**Comment by qubvel** [comment]
Hi @Vozf 
Could you recommend some article about type annotations in python and mypy? To clearly understand how to organize type hinting and for which methods it should be done.

**Comment by Vozf** [comment]
I believe it's easier to just start running mypy on some file and see what erros it produces and adjust based on it(either fixing errors or simplifying config)
I'd start with this https://breadcrumbscollector.tech/mypy-how-to-use-it-in-my-project/
And took quite a restrictive config from here https://stackoverflow.com/questions/55944201/python-type-hinting-how-do-i-enforce-that-project-wide
Based on your vision of annotation level lift some of the rules, because the config above is really restrictive

**Comment by Vozf** [comment]
In any case this is the way for a full mypy support. For start for the existing annotations to work when importing smp you just need to add py.typed in the source folder and add to the bundle
