### ISSUE TITLE
fscore value range

### ISSUE THREAD

**Issue by mamemo** [qubvel/segmentation_models.pytorch#276]
Hi, I was following the example you provide in your github. Currently, I'm trying to train a UNet with my own dataset. I had an error when I tried to tensor the masks using:

`
def to_tensor(x, **kwargs):
    return x.transpose(2, 0, 1).astype('float32')
`

Because the masks were read in grayscale and the shape was (256,256) and of course the to_tensor function expected (256, 256, 1). So I added a new axis like this:

`
# Open Image
image = cv2.imread(id_img)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
# Open Annotation
mask = cv2.imread(id_mask, 0)
mask = np.expand_dims(mask, axis=-1)
`

And after that, the example worked like a charm. However, my issue is with the fscore value when it gives a value higher than 1:
`
Epoch 1
train: 100%|█| 85/85 [04:02<00:00,  2.86s/it, dice_loss - -0.5808, iou_score - 11.41, fscore - 1.76, accuracy - 0.4015, recall - 0.9249, precisvalid: 100%|█| 12/12 [00:19<00:00,  1.59s/it, dice_loss - -0.8149, iou_score - 17.6, fscore - 1.887, accuracy - 0.6437, recall - 0.9787, precisEpoch 2
train: 100%|█| 85/85 [03:48<00:00,  2.69s/it, dice_loss - -0.8872, iou_score - 27.62, fscore - 1.926, accuracy - 0.6265, recall - 0.9941, precivalid: 100%|█| 12/12 [00:18<00:00,  1.52s/it, dice_loss - -0.8926, iou_score - 29.45, fscore - 1.931, accuracy - 0.7294, recall - 0.9929, preciEpoch 3
train: 100%|█| 85/85 [03:46<00:00,  2.67s/it, dice_loss - -0.9107, iou_score - 33.98, fscore - 1.941, accuracy - 0.69, recall - 0.9963, precisivalid: 100%|█| 12/12 [00:18<00:00,  1.54s/it, dice_loss - -0.9059, iou_score - 33.74, fscore - 1.938, accuracy - 0.7514, recall - 0.9944, preciEpoch 4
train: 100%|█| 85/85 [03:47<00:00,  2.68s/it, dice_loss - -0.9209, iou_score - 38.45, fscore - 1.947, accuracy - 0.7142, recall - 0.9966, precivalid: 100%|█| 12/12 [00:18<00:00,  1.58s/it, dice_loss - -0.916, iou_score - 38.82, fscore - 1.944, accuracy - 0.7789, recall - 0.9948, precis
`

I'm doing something wrong, or is the fscore a percentage? I just want to understand what is being calculated.

**Comment by Progern** [comment]
Actually, wondering as well, but about the iou_score. Mine goes more than 400, so I am not sure whether it's something wrong in the framework, or I messed up (probably)?
