### ISSUE TITLE
How to use the weights after trainning?

### ISSUE THREAD

**Issue by jianyin2016** [qubvel/segmentation_models.pytorch#28]
It seems like the model should not be initialized the way the same as  trainning process when testing,I tried comment the train_log in the trainning for-loop expecting testing will be done without trainning, but the visualisition results shows 0,1 inference. I guess maybe the initializition of model of ENCODER may cover the trainned weights or somehow. so how to use the trainned weights in the right way?

sincerely!

**Comment by qubvel** [comment]
Hi @jianyin2016 
Try this way
1) initialize model `model = smp.Unet(...)`
2) load state dict `model.load_state_dict(state_dict)`

**Comment by jianyin2016** [comment]
Hi @qubvel 
Thanks for you prompt reply & your nice work,

Actually, I found the reason why testing being not good as expecting is that I use the initialized model to inference other than the trainned model, after I finally understand the logic of code, it is all clear!

Besides, for multi-class task, the visualize function seems not compatible，though make few importance.

what bothers me most is about the evaluation metrics, Do F-score still suitable for multi-class segmentation task?and should Iou change to m-IoU when it comes to multi-class situation?

**Comment by hust-kevin** [comment]
@jianyin2016  @qubvel  I load the train weight,but meet this error

![image](https://user-images.githubusercontent.com/23699630/61184324-fa7b8580-a67e-11e9-9fc4-90ab1b4cf937.png)
