### ISSUE TITLE
can fit twice less workers since pytorch 1.7.0

### ISSUE THREAD

**Issue by JulienMaille** [qubvel/segmentation_models.pytorch#282]
Am I the only one with that issue? I tried both 1.7.0+cu11.0 and 1.7.0+cu10.2 and I can only run half the number of workers I used to be able to fit with 1.6.0 on my 2080Ti on Win10
I've not found anything related on torch tracker except maybe this issue: https://github.com/pytorch/pytorch/issues/47056

**Comment by lijunzh** [comment]
Do you mean that the optimal number of workers to load data halfed from 1.6 to 1.7? As I understand, you can use as many workers as wanted using PyTorch DataLoader class but it loads slower after you pass a threshold of workers.

**Comment by JulienMaille** [comment]
No, I mean the maximum number of workers I can fit in my RAM.

**Comment by lijunzh** [comment]
I am not sure about CPU RAM usage, but I noticed increased GPU RAM usage upgrading from PyTorch 1.6 to 1.7 on the same training program.

**Comment by JulienMaille** [comment]
Sorry if it wasn't clear, I'm talking about GPU RAM from the beginning.

**Comment by JulienMaille** [comment]
I gave 1.7.1 a try and it is still slower to train than 1.6 on a GTX 2080 Ti
