### ISSUE TITLE
Could you support Focal Loss? 

### ISSUE THREAD

**Issue by zhongqiu1245** [qubvel/segmentation_models.pytorch#291]
Thank you for your amazing job!
Could you support Focal Loss? 
It will be so perfect for this amazing job if support  Focal Loss.
Thank you!

**Comment by azkalot1** [comment]
model and loss are independent, you can take any pytorch version of focal loss and use it. Shouldn't be a problem. 
For example, I used https://github.com/clcarwin/focal_loss_pytorch and it worked OK.

**Comment by zhongqiu1245** [comment]
Thank you for your reply. @azkalot1 
Can the focal loss you mentioned be used for multiclass?

**Comment by azkalot1** [comment]
Yes

**Comment by zhongqiu1245** [comment]
Thank you very much!
