### ISSUE TITLE
FPN wrong smooth layer

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [qubvel/segmentation_models.pytorch#292]
Dear all,

First of all thank you for the amazing library. I believe the implementation of FPN is wrong, or at least is not the one proposed in the paper. 

In your implementation the *smooth* layers (3x3 convs) appended after each feature in the top-down path should not be upsampled at all. In your implementation you iteratevely upsample each feature map (p_5,...p_2) in order to match the target input resolution (e.g. 224x224) so you can sum up and then pass the resulting feature map to a classification head.

However, this is wrong. In the original implementation each feature map (p_i) has the same spatial resolution of the corresponding stage in the encoder (c_i). 

So, I was wondering why you are doing this because I see the problem, you need to have one single feature vector to pass it to the head to perform classification.

Thank you in advance :)

Best Regards,

Francesco

**Comment by qubvel** [comment]
Hi @FrancescoSaverioZuppichini 
My implementation based on this paper https://arxiv.org/abs/1901.02446 (same FPN authors, but published later)

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @qubvel , thank a lot! I was not aware of the follow up paper. So, just to be sure I got it. They upsample iteratevely until they reach 1/4 of the original resolution (e.g. for 224x224 inputs they upsample to 56x56), then they sum up and finally they do a  4 x unsampled followed by a 3x3 conv.  

To recap, while the original PFN output was 4 features of 128-d but with different size, the output of this version is one feature with 128-d with some size.

Something is missing. In your implementation your upsample target goal is the input size, while in the paper is 1/4 of the input size. Is p_2 the output of the first ResNet layer (so with dims 64x112x112) or the third (128 x 56 x 56)? If the second is the correct one I see why they upsample to 1/4 (56) of the input size (224) because that is the feature size of p_2. 

Any help? :)

Thank you

**Comment by qubvel** [comment]
No, in my implementaion the goal for FPN is 1/4 size, than FPN output upsampled by 4 to reach target size.

**Comment by FrancescoSaverioZuppichini** [comment]
Thank you for the quick answer, I hope I am not bothering you too much! So the output from FPN (https://github.com/qubvel/segmentation_models.pytorch/blob/2cd9c5bc46ac8188446560320f5fffb949332ecb/segmentation_models_pytorch/fpn/decoder.py#L119) is a vector with w,h of 1/4 size (56x56 in resnet case)?

**Comment by qubvel** [comment]
Yes, then `x` goes to `segmentation_head` for final upsampling and channels reduction

**Comment by FrancescoSaverioZuppichini** [comment]
Thank you :)

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @qubvel, I hope you are doing great. I was wondering, with standard FPN that outputs a vector of features `p_0, ... p_i` of different spatial size, how do you perform pixel-wise segmentation? You still need to output one single tensor in the end. How would you proceed in that case? Thank you
