### ISSUE TITLE
Does Unet++ and Deeplabv3 need certain input shape? (same width-length ratio) 

### ISSUE THREAD

**Issue by leocd91** [qubvel/segmentation_models.pytorch#293]
I have an input shape (1000,130), it works with others like PANet and FPN. But error when using Unet++ and Deeplabv3.

**Comment by JulienMaille** [comment]
I usually pad input to multiple of 2^d with d equal to the depth of the encoder (5 by default)

**Comment by leocd91** [comment]
I tried it and didn't work, somehow solved by resizing it to (1024,128)
