### ISSUE TITLE
Use concatenation for feature pyramid aggregation?

### ISSUE THREAD

**Issue by hyc-xyz** [qubvel/segmentation_models.pytorch#30]
Hi! Thanks for repo owner's contribution! This repository is useful and benefits lots of people!

I would like to discuss the implementation of FPN in this repo with the people watching on this repo.
According to this [document](http://presentations.cocodataset.org/COCO17-Stuff-FAIR.pdf), I think page 25 suggesting that we should use concatenation instead of summation if I did not misunderstand the page.

https://github.com/qubvel/segmentation_models.pytorch/blob/02ef0e6ec4351cec9c707d0c3984941867e8a4d8/segmentation_models_pytorch/fpn/decoder.py#L102

```

    def forward(self, x):
        c5, c4, c3, c2, _ = x

        p5 = self.conv1(c5)
        p4 = self.p4([p5, c4])
        p3 = self.p3([p4, c3])
        p2 = self.p2([p3, c2])

        s5 = self.s5(p5)
        s4 = self.s4(p4)
        s3 = self.s3(p3)
        s2 = self.s2(p2)
       
        # use concatenation instead of summation?
        # x = s5 + s4 + s3 + s2
        x = torch.cat([s5, s4, s3, s2], dim=1)

        x = self.dropout(x)
        x = self.final_conv(x)

        x = F.interpolate(x, scale_factor=4, mode='bilinear', align_corners=True)
        return x
```

**Comment by qubvel** [comment]
Hi @hyc-xyz 
Yes you are right, I did not update reference for FPN
Implemented according to this [paper](https://arxiv.org/pdf/1901.02446.pdf) (page 4, Figure 3) of the same authors.

**Comment by HuangQinJian** [comment]
> x = torch.cat([s5, s4, s3, s2], dim=1)

But  when I modify it, the error arise:

```
RuntimeError: Given groups=1, weight of size 4 128 1 1, expected input[8, 512, 128, 128] to have 128 channels, but got 512 channels instead
```

```
x = s5 + s4 + s3 + s2
```

is  ok!

**Comment by qubvel** [comment]
You also have to modify number of input channels in next `final_conv` layer
https://github.com/qubvel/segmentation_models.pytorch/blob/02ef0e6ec4351cec9c707d0c3984941867e8a4d8/segmentation_models_pytorch/fpn/decoder.py#L85
Set `segmentation_channels * 4`
