### ISSUE TITLE
how to initialize the first layer of encoders?

### ISSUE THREAD

**Issue by somebodyus** [qubvel/segmentation_models.pytorch#303]
How to initialize the first layer of encoders?
My input has 6 channels. I want to average the pre-trained weight of the first layer. Then, initialize the first layer using the averaged weight.

**Comment by JulienMaille** [comment]
@qubvel I was wondering if it would make sense to always initialize like this: (as long as `in_channel != 3`)
```python
        weight = weight.sum(1, keepdim=True) / in_channels
        weight = weight.repeat(1, in_channels, 1, 1)
```
