### ISSUE TITLE
Feeding encoder input into decoder

### ISSUE THREAD

**Issue by ShairozS** [qubvel/segmentation_models.pytorch#311]
There is an error being thrown when feeding encoder output directly into the decoder - this is for the same model (Unet) so I'm not sure what the issue is as this seems intuitively correct. I need the encoding separately as I'm applying multi-level self-attention before feeding it into the decoder. Here's a small reproducible example

import torch
import segmentation_models_pytorch as smp

in_tensor = torch.rand((5,3,128,128))

unet = smp.Unet()
encoded_in_tensor = unet.encoder(in_tensor)
decoded_in_tensor = unet.decoder(encoded_in_tensor)

The decoder is throwing the error:
IndexError: tuple index out of range

**Comment by azkalot1** [comment]
try  unpacking `decoded_in_tensor = unet.decoder(*encoded_in_tensor)`

**Comment by ShairozS** [comment]
@azkalot1 thank you that solved it. Might be wise to add that into the documentation. As I take it now:

unet(in_tensor) 

is equivalent to:

unet.segmentation_head(unet.decoder(*unet.encoder(in_tensor)))

**Comment by azkalot1** [comment]
Passing a tensor separately to an encoder and then to a decoder is an interesting case. Any specific reason you prefer that to just `unet(tensor_)`?

**Comment by ShairozS** [comment]
I'm updating the encoded tensors utilizing a multi-level self attention
