### ISSUE TITLE
[Feature request] Add tanh as an activation function.

### ISSUE THREAD

**Issue by ternaus** [qubvel/segmentation_models.pytorch#313]
It would be nice to add it for pix2pix models.

**Comment by JulienMaille** [comment]
BTW @qubvel there are two `Activation` classes
https://github.com/qubvel/segmentation_models.pytorch/blob/7a9d4c5dde8d519d6f31be7388d108388614c8c1/segmentation_models_pytorch/base/modules.py#L76
https://github.com/qubvel/segmentation_models.pytorch/blob/6b79c831fa3d8df17a5c4e207ebf304bbf42c094/segmentation_models_pytorch/utils/base.py#L7
