### ISSUE TITLE
confusion with the train and valid operations

### ISSUE THREAD

**Issue by ipScore** [qubvel/segmentation_models.pytorch#32]
Hello, thanks for sharing the code, it's rather convenient to deal with the segmentation tasks.
When I use it for training my model, I have a confusion with the train and valid operations.
As the following said, 
```
train_logs = train_epoch.run(train_loader)
 valid_logs = valid_epoch.run(valid_loader)
```
since the train_epoch and valid epoch are created from smp.utils.train.ValidEpoch and smp.utils.train.TrainEpoch separately, however, the valid_epoch instance could use the weights obtained by train_epoch instance for validation. Maybe I ignore some key points. 

So how do they share the model weight with each other? 

Warm Regard.

**Comment by kannidekan** [comment]
![image](https://user-images.githubusercontent.com/22550160/61771915-96498600-ae23-11e9-8620-de4323d05795.png)
Hey, you can see this. They use the same model. When training, param will bp. It won't when validation.
