### ISSUE TITLE
UNet++ is not working PyTorch =:  module 'segmentation_models_pytorch' has no attribute 'UnetPlusPlus'

### ISSUE THREAD

**Issue by m-aliabbas** [qubvel/segmentation_models.pytorch#320]
AttributeError                            Traceback (most recent call last)
<ipython-input-16-3477a66792b8> in <module>()
      2 
      3 # We will use Feature Pyramid Network with pre-trained ResNeXt50 backbone
----> 4 net = smp.UnetPlusPlus(
      5     encoder_name="resnet18",        # choose encoder, e.g. mobilenet_v2 or efficientnet-b7
      6     encoder_weights="imagenet",     # use `imagenet` pretrained weights for encoder initialization

AttributeError: module 'segmentation_models_pytorch' has no attribute 'UnetPlusPlus'

**Comment by JulienMaille** [comment]
you probably need to update smp

**Comment by m-aliabbas** [comment]
I did update but same error

**Comment by m-aliabbas** [comment]
`!pip install -U git+https://github.com/qubvel/segmentation_models.pytorch`

I use this to install the latest version

**Comment by azkalot1** [comment]
It means you have a problem with the system python\python you use  - pip installs it to the wrong path.
