### ISSUE TITLE
Dice Loss for multiclass not working

### ISSUE THREAD

**Issue by MrRss** [qubvel/segmentation_models.pytorch#323]
Apparently, there is a problem when using Dice loss with multiclass: 

 File "C:\Miniconda3\envs\sm_py37\lib\site-packages\segmentation_models_pytorch\losses\dice.py", line 82, in forward
    y_true = F.one_hot(y_true, num_classes)  # N,H*W -> N,H*W, C
RuntimeError: one_hot is only applicable to index tensor.

However, it looks like the problem was just fixed in the originial repo: https://github.com/BloodAxe/pytorch-toolbelt/commit/8cbe16a17f2d1ade402b4c95b2a66e293ddab6e9

Could one please integrate the fixe? Thanks!

**Comment by colindecourt** [comment]
Hi @MrRss 

What is the format of you label ? Is it N,C, H, W or N, H, W ?

**Comment by MrRss** [comment]
Hi @colindecourt 

N,H,W

**Comment by colindecourt** [comment]
Hi, @MrRss,
It is weird your Dice loss doesn't work.  In my case I define the loss function as follow:
`loss = smp.losses.DiceLoss(mode='multiclass')`
Then in my training loop I did the following: 
`for inputs, labels in tqdm(train_loader):
        [...]
        prediction = model(inputs) #There is no activation function used here
        
        loss_train = loss(prediction, labels) #The activation function is directly applied here`

And it works. The output of my model has shape NxCxHxW and my labels has shape NxHxH (value from 0 to N_CLASSES).

Hope it will help you.

**Comment by MrRss** [comment]
Thanks, @colindecourt. I think, I found the problem. Did some refactoring and change stuff. But I think the problem came from the point that I used kornia for augmenting and that the mask tensor had to be converted to long first.

**Comment by wwjwy** [comment]
> Thanks, @colindecourt. I think, I found the problem. Did some refactoring and change stuff. But I think the problem came from the point that I used kornia for augmenting and that the mask tensor had to be converted to long first.

can you tell me how did you convert the mask tensor to long?
