### ISSUE TITLE
Add mean IOU metrics 

### ISSUE THREAD

**Issue by DeepSegmtn** [qubvel/segmentation_models.pytorch#325]
Hello qubvel,
I hope you are doing well.
Can you please add the mean IOU metric for the segmentation. Although there is IOU metric but I am not able to calculate mean IOU. I would be really thankful to you for the kind help. Many thanks

**Comment by MCvin** [comment]
This would be great I agree

**Comment by ramchandracheke** [comment]
Hi, 

I found solution as, Once the instance of train_epoch is created then we can change name as per below mentioned code.

```python
train_epoch = smp.utils.train.TrainEpoch(
    model, 
    loss=loss, 
    metrics=metrics, 
    optimizer=optimizer,
    device=DEVICE,
    verbose=True,
)

train_epoch.metrics[0].__name__="IoU_Class0"
train_epoch.metrics[1].__name__="IoU_Class1"
train_epoch.metrics[2].__name__="IoU_Class2"
```

This will be helpful to create IoU score at class level.
