### ISSUE TITLE
Some encoder without shape, how to deal with this?

### ISSUE THREAD

**Issue by MiaoRain** [qubvel/segmentation_models.pytorch#328]
when building the encoder, it will always need the encode. shape, see figure 1. But some encode doesn't have it, like mobilenet and efficientnet, shown in figure 2.  result in the error, see figure 3. How to deal with this problem? Thanks!
![image](https://user-images.githubusercontent.com/47746159/103497143-9274bc80-4e7b-11eb-9cd8-815d48d089d9.png)
![image](https://user-images.githubusercontent.com/47746159/103497404-6148bc00-4e7c-11eb-90c4-b01970aca0e5.png)
![image](https://user-images.githubusercontent.com/47746159/103497426-73c2f580-4e7c-11eb-968a-f8d94df94c2f.png)

**Comment by qubvel** [comment]
Parameter renamed to out_channels

**Comment by MiaoRain** [comment]
> Parameter renamed to out_channels
Thanks, problem solved.
