### ISSUE TITLE
a strange train question

### ISSUE THREAD

**Issue by yu-Mas** [qubvel/segmentation_models.pytorch#329]
![image](https://user-images.githubusercontent.com/66811152/103845838-dcf27500-50d7-11eb-9090-b06d1e3ffa36.png)
Though Epoch0 can get a normal score,Epcoh1(or bigger Epoch) will always cant get normal score(e.g.2.917e-13).
Have anyone met this?
Is it a bug?

**Comment by azkalot1** [comment]
1. Overfit your model using a single train batch  - it is easier to debug this way
2. Visualize predictions after epochs 0 and 1 to see what is the difference. 
3. LR may be too high, try 100 times lower

**Comment by yu-Mas** [comment]
您好，邮件已收到，我会尽快处理，谢谢。
