### ISSUE TITLE
Why batchsize influence test performance?

### ISSUE THREAD

**Issue by justina-1015** [qubvel/segmentation_models.pytorch#331]
this one is batchsize = 1
![image](https://user-images.githubusercontent.com/56578216/104160045-63d28500-542b-11eb-8ae6-a7983104624c.png)
 
and this one is batchsize = 8
![image](https://user-images.githubusercontent.com/56578216/104160109-86649e00-542b-11eb-9f78-ff758ea84db1.png)

Why there are different performance between different batchsize?
Thanks

**Comment by wangshaonian666** [comment]
I also encountered the same problem. Have you figured it out? thanks
