### ISSUE TITLE
Jaccard loss at multiple places

### ISSUE THREAD

**Issue by FatPandao** [qubvel/segmentation_models.pytorch#338]
I find Jaccard loss in two different places:

https://github.com/qubvel/segmentation_models.pytorch/blob/e55b2da9f844066cddd4894ce95bcacc5def1d54/segmentation_models_pytorch/utils/losses.py

https://github.com/qubvel/segmentation_models.pytorch/blob/e55b2da9f844066cddd4894ce95bcacc5def1d54/segmentation_models_pytorch/losses/jaccard.py

It seems that they are doing the same stuff, and why you have them distributed in different places and implement twice? I'm also wondering which one should I use?

**Comment by JulienMaille** [comment]
I think qubvel is transitioning from the first one to the other
