### ISSUE TITLE
how to use multi-gpu?

### ISSUE THREAD

**Issue by hust-kevin** [qubvel/segmentation_models.pytorch#34]

**Comment by oysteijo** [comment]
Let me just guess, that you do it in the same way as with any other pytorch model. (Correct me if I'm wrong).

    model = smp.Unet(
        encoder_name=ENCODER, 
        encoder_weights=ENCODER_WEIGHTS, 
        classes=len(CLASSES), 
        activation=ACTIVATION,
    )
    model = nn.DataParallel(model)

... and it should be ok.

**Comment by hust-kevin** [comment]
hi, @oysteijo ,thanks for your reply, but this occur an error, because I use the diffierent lr like below
```python
optimizer = torch.optim.Adam([
        {'params': model.decoder.parameters(), 'lr': 1e-4}, 
        {'params': model.encoder.parameters(), 'lr': 1e-6}])
```
so when I use `model = nn.DataParallel(model)`
this will make an error 
`AttributeError: 'DataParallel' object has no attribute 'decoder'`

**Comment by oysteijo** [comment]
May I ask what was wrong when you got: `AttributeError: 'DataParallel' object has no attribute 'decoder'` ?

**Comment by hust-kevin** [comment]
if use multi-gpu,should change 
`model.decoder.parameters()` to `model.module.decoder.parameters()`

but I find another question, I use a 2080ti to train my data, one epoch need 16 minutes,
when I use nn.DataParallel(model), 4 2080ti train one epoch need 12minutes, It's seems strange

**Comment by qubvel** [comment]
>but I find another question, I use a 2080ti to train my data, one epoch need 16 minutes,
when I use nn.DataParallel(model), 4 2080ti train one epoch need 12minutes, It's seems strange

may be loss functions is calculated on a single gpu, did you look at `nvidia-smi`? what about gpu utilization?

**Comment by hust-kevin** [comment]
@qubvel gpu memory is almost used,but gpu-util is low, only ~30%

**Comment by HuangQinJian** [comment]
> if use multi-gpu,should change
> `model.decoder.parameters()` to `model.module.decoder.parameters()`
> 
> but I find another question, I use a 2080ti to train my data, one epoch need 16 minutes,
> when I use nn.DataParallel(model), 4 2080ti train one epoch need 12minutes, It's seems strange

When I  use the code ,the code stuck and did not run.But also do not go wrong,why?

**Comment by HuangQinJian** [comment]
> May I ask what was wrong when you got: `AttributeError: 'DataParallel' object has no attribute 'decoder'` ?

When I  use the code ,the code stuck and did not run.But also do not go wrong,why?

**Comment by hust-kevin** [comment]
@HuangQinJian , do you use multi-gpu? do you try deeplabv3 ?https://github.com/jfzhang95/pytorch-deeplab-xception
when I use multi-gpu,the code stuck and did not run. and the gpu-ulti is 0

|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:02:00.0  On |                  N/A |
| 29%   51C    P2    79W / 250W |  10977MiB / 10988MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:03:00.0 Off |                  N/A |
| 22%   39C    P8    21W / 250W |  10146MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by HuangQinJian** [comment]
> @HuangQinJian , do you use multi-gpu? do you try deeplabv3 ?https://github.com/jfzhang95/pytorch-deeplab-xception
> when I use multi-gpu,the code stuck and did not run. and the gpu-ulti is 0

I use multi-gpu,gpu-ulti is 100,but the code stuck and did not run

**Comment by hust-kevin** [comment]
@HuangQinJian Would you like to be my friend， my wechat is 15172413005
