### ISSUE TITLE
Proper scale or pretrained weight for channels<3

### ISSUE THREAD

**Issue by JulienMaille** [qubvel/segmentation_models.pytorch#341]
Dear @qubvel I would like to confirm it makes more sense
- to divide summed weight by 3 when training on 1 channel
- to sum and divide by 2 instead of keeping [:, :2] for 2 channels

https://github.com/qubvel/segmentation_models.pytorch/blob/176f2777cbfc4101abf9b10d1339c7a3e93f06f2/segmentation_models_pytorch/encoders/_utils.py#L22-L25

changed to
```python
    if in_channels == 1:
        weight = weight.sum(1, keepdim=True) * 1/3
    elif in_channels == 2:
        weight = weight.sum(1, keepdim=True) / in_channels
        weight = weight.repeat(1, in_channels, 1, 1)
```
what do you think? Shall I issue a PR?

**Comment by qubvel** [comment]
Hi, lets assume we have

Image    Weights
R 0.50    0.15
G 0.40    0.20
B 0.55    0.17

The result of this "convolution" would be 
0.50 *0.15 + 0.40*0.20 + 0.55*0.17 = 0.2485

No lets convert image from RGB to grayscale by simple average (image would have one channel with 0.48 value)

1) sum weights 
0.48 * (0.15 + 0.20 + 0.17) = 0.2496
2) average weights
0.48 * (0.15 + 0.20 + 0.17) / 3 = 0.0832

As you can see in first case we preserve "signal" scale, that is why you should not divide weights.

**Comment by JulienMaille** [comment]
Thanks for the details explanation. this makes sense.
