### ISSUE TITLE
Expected more than 1 value per channel when training when using PAN, other architecture works fine

### ISSUE THREAD

**Issue by leocd91** [qubvel/segmentation_models.pytorch#342]
```
model = smp.PAN(
    encoder_name="efficientnet-b3",        
    encoder_weights=None,     
    in_channels=1,                  
    classes=num_classes,  
    activation= None                    
)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)
test = torch.rand(1, 1, 128, 128).cuda()
out = model(test)
out.shape
```

Got this error when running the code above :
`ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 32, 1, 1])`

the code works fine if you change PAN to another architecture..

**Comment by qubvel** [comment]
*Currently works with shape of input tensor >= [B x C x 128 x 128] for pytorch <= 1.1.0 and with shape of input tensor >= [B x C x 256 x 256] for pytorch == 1.3.1*

Try to increase spatial resolution

**Comment by leocd91** [comment]
changing to 
`test = torch.rand(1, 1, 256, 256).cuda()`
and
`test = torch.rand(1, 1, 800, 320).cuda()`


still got the same result

**Comment by JurijsNazarovs** [comment]
Seems like the issue is raised by batch size equals 1. I suppose it happens because of the batch_norm module somewhere inside the model. You can try to increase batch size, or if this is during testing, then do model.eval().

**Comment by leocd91** [comment]
you are right! Thanks.

**Comment by ArtemSivtsov** [comment]
In some cases increasing batch_size may not work. Make sure that dataset length is devisible by batch size without a remainder. This remainder could be a root of the problem, so use drop_last=True in Dataloader to avoid this problem
