### ISSUE TITLE
RuntimeError: Tried to access to nonexistent attribute filt. 

### ISSUE THREAD

**Issue by Hamid-Sarraf** [qubvel/segmentation_models.pytorch#348]
**I'm trying to implement the torch version.
I got the following error:**
RuntimeError:
Tried to access to nonexistent attribute filt. Did you forget to initialize it in init()?:
def call(self, input: torch.Tensor): input_pad = F.pad(input, (1, 1, 1, 1), 'reflect')
filt = self.filt.get(str(input.device), self._create_filter(input)) ~~~~~~~~~ <--- HERE
return F.conv2d(input_pad, filt, stride=2, padding=0, groups=input.shape[1])

**this came when I ran:**
import segmentation_models_pytorch as smp
**any idea what is wrong?**
**This the error from running the example jupyter.
Thanks in advance.**

**Comment by junjun1023** [comment]
Met the same issue. I updated version of PyTorch then the problem solved.

**Comment by Hamid-Sarraf** [comment]
Thanks,
Did you just update it to the latest version or a certain version?
