### ISSUE TITLE
Accessing layers of model

### ISSUE THREAD

**Issue by isNeil** [qubvel/segmentation_models.pytorch#357]
Hi, how can I access individual layers of the Unet model, like with standard pytorch models?
After creating the model in the demonstrated way: 
model = Unet( "resnet34","imagenet",3,3)
normally I would be able to do model[i] to get the i layer. 
Here I get TypeError: 'Unet' object is not subscriptable

I've been going through the source code but I'd like some help. 

What is the best way to access individual layers of the model?

**Comment by Nachimak28** [comment]
@isNeil I'm not sure what your end goal is, but there are multiple ways you can access individual layers of each of the model. 
This SMP library follows a general pattern that the the encoder_name we enter becomes the encoder and the Unet class builds the decoder above it with its default options. The Unet model build has 2 sub-modules and I think this applies to all the models built using this library - `model.encoder` and `model.decoder`. Now these encoder and decoder submodules too have nn.Sequential based submodules. So you might need to view the entire architecture then access some particular layer in a chained fashion as follows:

```python
# building the model
model = smp.Unet(
    encoder_name='resnet34',
    encoder_weights='imagenet',
    classes=3,
    activation='softmax2d'
)

print(model.encoder.layer1[1])
```
The output shall be 
```
BasicBlock(
  (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)
```
To go further deeper you can do something like this:
```python
list(model.encoder.layer1[1].named_children())[0]
```
Output:
```python
('conv1',
 Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False))
```

One more way I found that pytorch recursively lays the layers in a list is by doing the following:
```python
list_of_layers = list(model.modules())
```
This shall give you all the layers by recursively iterating over all submodules until it reaches a single indivisible layer. You might need to be careful if you get confused while retrieving the layer of your choice by indexing.

There are other ways too to access the layers of models such as:
```python
children = list(model.encoder.children())
# this will output a list
# or
children = list(model.encoder.named_children()) 
# this will output a tuple with name as first element and nn.Module or layer as the second element of the tuple
```
OR 
```python
od = dict(model._modules.items())
# this will output a dictionary
```
Hope this helps
