### ISSUE TITLE
'FocalLoss' object has no attribute '__name__'

### ISSUE THREAD

**Issue by Indhujamari** [qubvel/segmentation_models.pytorch#358]
I am trying to use Focalloss for my multiclass segmentation model but it gives the error as

**ModuleAttributeError: 'FocalLoss' object has no attribute '__name__'**

Even I tried to reload the module but it gives the same error.

can anyone help me?
Thanks in advance.

**Comment by Nachimak28** [comment]
@Indhujamari
you can do it as follows:

`import segmentation_models_pytorch as smp`
`loss = smp.losses.FocalLoss(mode='multiclass')`
`loss.__name__ = 'focal_loss'`

This should hopefully solve the issue

**Comment by FrontierQ** [comment]
Hi,i found that this code has not implemented the focal loss ,Could you please share me the focal loss code?

**Comment by xiaoyanLi629** [comment]
The same for Diceloss.
The code below works.
`loss = smp.losses.DiceLoss("multilabel")
loss.__name__ = 'Dice_loss'`
