### ISSUE TITLE
Achitecture and Encoder combinations that are used in parers don't work.

### ISSUE THREAD

**Issue by seba-eng** [qubvel/segmentation_models.pytorch#362]
In the original DeepLabV3+ paper (https://arxiv.org/pdf/1802.02611.pdf), they used (among others) an Xception model as encoder. The other way around, Resnest doesn't work as a backbone for DeepLabV3, but was used in the Resnest paper (https://arxiv.org/pdf/2004.08955.pdf). Both combinations result in an error here (connected to `make_dilated`). 
It would be really great if those combinations would work here as well, as they seem to be state of the art models for segmentation.

**Comment by OneDirection67** [comment]
Have you solve the error? I met the same problem.
