### ISSUE TITLE
`smooth_factor` in `SoftCrossEntropyLoss` is by default None which leads to unsupported division

### ISSUE THREAD

**Issue by Many98** [qubvel/segmentation_models.pytorch#372]
When I used default attributes:
 ```
criterion = segmentation_models_pytorch.losses.SoftCrossEntropyLoss(reduction='mean', smooth_factor=None, 
                 ignore_index=0, dim=1)
```
which leads to error:

File ".../anaconda3/.../lib/python3.8/site-packages/segmentation_models_pytorch/losses/soft_ce.py", line 41, in forward
    return label_smoothed_nll_loss(
  File ".../anaconda3/.../lib/python3.8/site-packages/segmentation_models_pytorch/losses/_functional.py", line 252, in label_smoothed_nll_loss
    eps_i = epsilon / lprobs.size(dim)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

I think that `smooth_factor` should be by default 0.0

**Comment by GrigoriiTarasov** [comment]
For ones who got in same trouble: use smooth_factor=0 for no smoothing.
This argument shoulnd't be 'Optional' due to no handling of its 'default' 'None'.
