### ISSUE TITLE
AttributeError: module 'segmentation_models_pytorch.losses' has no attribute 'FocalLoss'

### ISSUE THREAD

**Issue by ghltshubh** [qubvel/segmentation_models.pytorch#381]
Why does `loss = smp.utils.losses.DiceLoss()` work however `loss = smp.losses.DiceLoss()` or `loss = smp.losses.FocalLoss()` doesn't?

**Comment by samwulol** [comment]
https://github.com/qubvel/segmentation_models.pytorch/issues/361#issuecomment-800352382

**Comment by DeepKnowledge1** [comment]
the losses moved out of utils
for instance, DiceLoss, needs to identify the mode

`loss = smp.losses.DiceLoss('binary')`

**Comment by martinurbieta** [comment]
I had to implement as suggested in by [xiaoyanLi629](https://github.com/xiaoyanLi629) in the [post ](https://github.com/qubvel/segmentation_models.pytorch/issues/358#issuecomment-1008076726) the loss.__name__
due to `AttributeError: 'DiceLoss' object has no attribute '__name__' `

```
loss = smp.losses.DiceLoss("multilabel")
loss.__name__ = 'Dice_loss'
```

> the losses moved out of utils for instance, DiceLoss, needs to identify the mode
> 
> `loss = smp.losses.DiceLoss('binary')`
