### ISSUE TITLE
how to transfer a standard pretrained resnet model to 4-channel in your code?

### ISSUE THREAD

**Issue by SonwYang** [qubvel/segmentation_models.pytorch#39]
In Remote sensing, the image usually has more than three channels. For example, the image has NIR ,R ,G and B. I want to leveraged on the pretrained weights for a standard ResNet50 and transferred them to a 4-channel input version by copying RGB weights + the NIR weight as equivalent to the red channel.I have solve this in my code, but I have no idea about this. How to solve it in your code?Thank you!
Here is my solution in my code:
`model = models.resnet50(pretrained=True)
weight = model.conv1.weight.clone()
model.conv1 = nn.Conv2d(4, 64, kernel_size=7, stride=2, padding=3, bias=False)
with torch.no_grad():
    model.conv1.weight[:, :3] = weight
    model.conv1.weight[:, 3] = model.conv1.weight[:, 0]
    
x = torch.randn(10, 4, 224, 224)
output = model(x)`

**Comment by qubvel** [comment]
Hi @yangpeng1995 you can do it the same way
model.encoder.conv1 ...

**Comment by yangpeng1995** [comment]
@qubvel ，hi, thank you for your reply. I have no idea to add it to where, can you give me some suggestion about this in detail?adding it to train.py or  model.py?

**Comment by LitvinchukAndrey** [comment]
@yangpeng1995 You can do it in your code manually. You need to initialize a model, for example
`import segmentation_models_pytorch as smp`
`model = smp.Unet('resnet34', encoder_weights='imagenet')`
`model.encoder.conv1= nn.Conv2d(4, 64, kernel_size=7, stride=2, padding=3, bias=False)`
Don't know if this code is working, but i hope you got an idea

**Comment by yangpeng1995** [comment]
@LitvinchukAndrey .I have tried it in your suggestion but it didn't work.I got this:
`RuntimeError: Given groups=1, weight of size 64 3 7 7, expected input[8, 4, 256, 256] to have 3 channels, but got 4 channels instead
`

**Comment by yangpeng1995** [comment]
@LitvinchukAndrey .I tried it but it didn't work.I got this:
`  File "train4c2.py", line 174, in main
    optimizer = Adam(net.parameters(), lr=args.lr)
  File "/root/anaconda3/envs/yp/lib/python3.6/site-packages/torch/optim/adam.py", line 42, in __init__
    super(Adam, self).__init__(params, defaults)
  File "/root/anaconda3/envs/yp/lib/python3.6/site-packages/torch/optim/optimizer.py", line 50, in __init__
    self.add_param_group(param_group)
  File "/root/anaconda3/envs/yp/lib/python3.6/site-packages/torch/optim/optimizer.py", line 201, in add_param_group
    raise ValueError("can't optimize a non-leaf Tensor")
ValueError: can't optimize a non-leaf Tensor
`

**Comment by Luan-Zhaoliang** [comment]
@SonwYang Hi, I have the same problem as you.  Specifically, I need to use resnet34 model to 4-channel in my code, but when I implemented it with your solution, it doesn't work for me. Could you give me more code about your solution, then I can check the problem of my code

**Comment by qubvel** [comment]
Did you try to use `in_channels=4`?

**Comment by Luan-Zhaoliang** [comment]
> Did you try to use `in_channels=4`?

Yes, I have tried to do it, but with some problems in my code. Did you also use the in_channel=4?

**Comment by MARABOTTO** [comment]
Using in_channels=4, this issue become a pretraining issue since we can't use encoder_weights=None. Could you fix that ? It should let us train from scratch a network on 4 channels data. Thanks!
