### ISSUE TITLE
Why is the result of single test picture different from that of training？It's the same picture。

### ISSUE THREAD

**Issue by wenwu2021** [qubvel/segmentation_models.pytorch#393]
test_transform = albu.Compose([
    albu.PadIfNeeded(320, 640),
    albu.RandomCrop(height=320, width=640, always_apply=True),
])
def TestOneImage1(model,image,num_classes):
    
    model.eval()
    with torch.no_grad():
        image_np = np.asarray(image)
        image_test =test_transform(image=image_np)['image']

        print(image_test.shape)
        image_test=image_test.transpose([2, 0, 1]).astype('float32')
        print(image_test.shape)
        x_tensor = torch.from_numpy(image_test).to(DEVICE).unsqueeze(0)
        print(x_tensor.shape)
        pr_mask = model.predict(x_tensor)
        print(pr_mask.shape)
        pr_mask = (pr_mask.squeeze().cpu().numpy().round())
        print(pr_mask.shape)
        visualize(image=image,predicted_mask=pr_mask[0,:,:])

train_images_path = "D:/pytorch/dataset/pill/train/Images/pill_ginseng_contamination_116.png"   # 图片存放目录
#image = Image.open(images_path)
image = cv2.imread(train_images_path)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
TestOneImage1(best_model,image,3)

TestOneImage
![image](https://user-images.githubusercontent.com/83483787/116784749-82d35080-aac8-11eb-84e0-a1f3893c9013.png)

trainImage
![image](https://user-images.githubusercontent.com/83483787/116784769-954d8a00-aac8-11eb-949f-a5365b848b47.png)

**Comment by ChrisMasafu** [comment]
Kindly share your full code and I'll be happy to help.

**Comment by ChrisMasafu** [comment]
> test_transform = albu.Compose([ albu.PadIfNeeded(320, 640), albu.RandomCrop(height=320, width=640, always_apply=True), ]) def TestOneImage1(model,image,num_classes):
> 
> ```
> model.eval()
> with torch.no_grad():
>     image_np = np.asarray(image)
>     image_test =test_transform(image=image_np)['image']
> 
>     print(image_test.shape)
>     image_test=image_test.transpose([2, 0, 1]).astype('float32')
>     print(image_test.shape)
>     x_tensor = torch.from_numpy(image_test).to(DEVICE).unsqueeze(0)
>     print(x_tensor.shape)
>     pr_mask = model.predict(x_tensor)
>     print(pr_mask.shape)
>     pr_mask = (pr_mask.squeeze().cpu().numpy().round())
>     print(pr_mask.shape)
>     visualize(image=image,predicted_mask=pr_mask[0,:,:])
> ```
> 
> train_images_path = "D:/pytorch/dataset/pill/train/Images/pill_ginseng_contamination_116.png" # 图片存放目录 #image = Image.open(images_path) image = cv2.imread(train_images_path) image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) TestOneImage1(best_model,image,3)
> 
> TestOneImage ![image](https://user-images.githubusercontent.com/83483787/116784749-82d35080-aac8-11eb-84e0-a1f3893c9013.png)
> 
> trainImage ![image](https://user-images.githubusercontent.com/83483787/116784769-954d8a00-aac8-11eb-949f-a5365b848b47.png)

Kindly share your full code and I'll be happy to help.
