### ISSUE TITLE
DeepLab v3+ concat tensor size mismatch

### ISSUE THREAD

**Issue by Praful932** [qubvel/segmentation_models.pytorch#397]
I'm using the [DeepLab v3+](https://smp.readthedocs.io/en/latest/models.html#segmentation_models_pytorch.DeepLabV3Plus) model to train a semantic segmentation model using [AIRS Dataset](https://www.airs-dataset.com/).
The input image shape is `(600, 600, 3)` and mask - `(600, 600)`.
I'm getting a tensor size mismatch error when I'm trying to train the model
![image](https://user-images.githubusercontent.com/45713796/117543386-380e8700-b03a-11eb-8fe2-b8296cc28d79.png)

**Comment by hisasu00** [comment]
I'm in the same situation.

**Comment by backdoorbreaker** [comment]
I encountered similar issues. I think the input image shape needs to be in the form `(c, h, w)`, and asfaict, the image needs to be square. i.e. `h = w`

**Comment by backdoorbreaker** [comment]
Apologies, I mispoke in my earlier comment (edited now). 

I believe the tensor size mismatch error is happening in your case bc of the input image height and weight. For each layer in the encoder depth, the encoder will output a feature map where the `hw` dimensions will be reduced by 2 from the previous layer. (see the docs on encoder [forward](https://github.com/qubvel/segmentation_models.pytorch/blob/a6e1123983548be55d4d1320e0a2f5fd9174d4ac/segmentation_models_pytorch/encoders/mobilenet.py#L11-L19) method for more details)

In your use case, depth 1 will output a feature map where `(h, w) = (300, 300)`, depth 2 will output `(h, w) = (150, 150)`, and depth 3 will output `(h, w) = (75, 75)`. Following depth 3, the height and width are no longer divisible by 2 which I think is why the `RuntimeError` happens. 

Potential solutions are to update your segmentation model to only go to depth 3 (`encoder_depth` kwarg) or to resize your input images to a shape where the height and width are divisible by 2 up to 5 times.

**Comment by Praful932** [comment]
@backdoorbreaker You are right, It worked for me when I resized my input to a power of 2(512)
