### ISSUE TITLE
AttributeError: 'MSELoss' object has no attribute '__name__'

### ISSUE THREAD

**Issue by bibinwils** [qubvel/segmentation_models.pytorch#399]
I was trying to use a regression approach using the segmentaion_models. For that, I need to use nn.MSEloss or nn.L1loss as the loss function. But when I try to do so, I'm getting the following error

> Epoch: 0
train:   0%|          | 0/175 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 12 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:528: UserWarning: Using a target size (torch.Size([8, 3, 320, 320])) that is different to the input size (torch.Size([8, 1, 320, 320])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
train:   0%|          | 0/175 [00:22<?, ?it/s]
---------------------------------------------------------------------------

> AttributeError                            Traceback (most recent call last)

> <ipython-input-27-0db0875a4c35> in <module>()

      6 
      7     print('\nEpoch: {}'.format(i))

> ----> 8     train_logs = train_epoch.run(train_loader)

      9     valid_logs = valid_epoch.run(valid_loader)
     10 

> 1 frames

> /usr/local/lib/python3.7/dist-packages/segmentation_models_pytorch/utils/train.py in run(self, dataloader)

     50                 loss_value = loss.cpu().detach().numpy()
     51                 loss_meter.add(loss_value)

> ---> 52                 loss_logs = {self.loss.__name__: loss_meter.mean}

     53                 logs.update(loss_logs)
     54 

> /usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)

    946                 return modules[name]
    947         raise AttributeError("'{}' object has no attribute '{}'".format(

> --> 948             type(self).__name__, name))

    949 
    950     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

> AttributeError: 'MSELoss' object has no attribute '__name__'

Please help me to resolve

**Comment by gregbugaj** [comment]
You can add  `loss.__name__ = 'MSELoss'`
