### ISSUE TITLE
How to use multi Losses? more than two

### ISSUE THREAD

**Issue by HXLH50K** [qubvel/segmentation_models.pytorch#401]
My code is
```
loss = smp.utils.losses.BCELoss() \
        + smp.utils.losses.NoiseRobustDiceLoss(eps=1e-7) \
        + smp.utils.losses.TverskyLoss(eps=1e-7, alpha=0.7, beta=0.7)
```
Losses all of above I have implemented and can run without error alone or two together, when I want to add 3 losses, it report:
```
Traceback (most recent call last):
  File "train.py", line 293, in <module>
    train_net(model=net,
  File "train.py", line 207, in train_net
    train_logs = train_epoch.run(train_loader)
  File "/home/xray/segmentation_models.pytorch/segmentation_models_pytorch/utils/train.py", line 47, in run
    loss, y_pred = self.batch_update(x, y)
  File "/home/xray/segmentation_models.pytorch/segmentation_models_pytorch/utils/train.py", line 88, in batch_update
    loss = self.loss(prediction, y)
  File "/home/xray/segmentation_models.pytorch/segmentation_models_pytorch/utils/base.py", line 53, in __call__
    return self.l1.forward(*inputs) + self.l2.forward(*inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 175, in _forward_unimplemented
    raise NotImplementedError
NotImplementedError
```

**Comment by MustfizurRahaman** [comment]
Hi, Can you tell me if this model FocalLoss Compatible?

**Comment by HXLH50K** [comment]
> Hi, Can you tell me if this model FocalLoss Compatible? Can you help me with TverskyLoss? Because it is not implemented at utils.losses .

```
class TverskyLoss(base.Loss):
    def __init__(self,
                 eps=1.,
                 activation=None,
                 alpha=0.5,
                 beta=0.5,
                 ignore_channles=None,
                 **kwargs):
        super().__init__(**kwargs)
        self.eps = eps
        self.activation = Activation(activation)
        self.alpha = alpha
        self.beta = beta
        self.ignore_channels = ignore_channles

    def forward(self, y_pr, y_gt):
        return 1 - F.tversky(
            y_pr,
            y_gt,
            eps=self.eps,
            threshold=None,
            alpha=self.alpha,
            beta=self.beta,
            ignore_channels=self.ignore_channels,
        )
```
```
def tversky(pr,
            gt,
            eps=1e-7,
            alpha=0.5,
            beta=0.5,
            threshold=None,
            ignore_channels=None):
    """Calculate tversky cofficient between ground truth and prediction
    Args:
        pr (torch.Tensor): predicted tensor
        gt (torch.Tensor):  ground truth tensor
        eps (float): epsilon to avoid zero division
        threshold: threshold for outputs binarization
    Returns:
        float: dice score
    """

    pr = _threshold(pr, threshold=threshold)
    pr, gt = _take_channels(pr, gt, ignore_channels=ignore_channels)

    tp = torch.sum(gt * pr)
    fp = torch.sum(pr) - tp
    fn = torch.sum(gt) - tp

    tversky = (tp + eps) / (tp + alpha * fn + beta * fp + eps)
    return tversky
```
And I have not try Focalloss, I don't know about it.

**Comment by MustfizurRahaman** [comment]
Is this loss added to the utills.losses folder? wherever we are trying to implement something on that file the main model could not find it. Did you face a similar type of problem?

**Comment by sugatoray** [comment]
Refer to [this stackoverflow answer](https://stackoverflow.com/a/63679664/8474894) and implement your requirement as a `pytorch.nn.Module` class.

### Custom Loss: `CustomLoss`

Your custom-loss class would look something like this.

```python
from typing import List

class CustomLoss(nn.Module):
    def __init__(self, weights: List[float]=None, loss_functions: List[torch.nn.Module]=None):
        super(CustomLoss, self).__init__()
        self.weights = weights
        self.loss_functions = loss_functions

    def forward(self, inputs, targets, smooth=1):
        
        #comment out if your model contains a sigmoid or equivalent activation layer
        inputs = F.sigmoid(inputs)       
        
        #flatten label and prediction tensors
        inputs = inputs.view(-1)
        targets = targets.view(-1)
        
        blend = ... # your blending logic goes here 
        
        return blend
```

**Comment by MustfizurRahaman** [comment]
this function is not compatible with this API

**Comment by MustfizurRahaman** [comment]
> > Hi, Can you tell me if this model FocalLoss Compatible? Can you help me with TverskyLoss? Because it is not implemented at utils.losses .
> 
> ```
> class TverskyLoss(base.Loss):
>     def __init__(self,
>                  eps=1.,
>                  activation=None,
>                  alpha=0.5,
>                  beta=0.5,
>                  ignore_channles=None,
>                  **kwargs):
>         super().__init__(**kwargs)
>         self.eps = eps
>         self.activation = Activation(activation)
>         self.alpha = alpha
>         self.beta = beta
>         self.ignore_channels = ignore_channles
> 
>     def forward(self, y_pr, y_gt):
>         return 1 - F.tversky(
>             y_pr,
>             y_gt,
>             eps=self.eps,
>             threshold=None,
>             alpha=self.alpha,
>             beta=self.beta,
>             ignore_channels=self.ignore_channels,
>         )
> ```
> 
> ```
> def tversky(pr,
>             gt,
>             eps=1e-7,
>             alpha=0.5,
>             beta=0.5,
>             threshold=None,
>             ignore_channels=None):
>     """Calculate tversky cofficient between ground truth and prediction
>     Args:
>         pr (torch.Tensor): predicted tensor
>         gt (torch.Tensor):  ground truth tensor
>         eps (float): epsilon to avoid zero division
>         threshold: threshold for outputs binarization
>     Returns:
>         float: dice score
>     """
> 
>     pr = _threshold(pr, threshold=threshold)
>     pr, gt = _take_channels(pr, gt, ignore_channels=ignore_channels)
> 
>     tp = torch.sum(gt * pr)
>     fp = torch.sum(pr) - tp
>     fn = torch.sum(gt) - tp
> 
>     tversky = (tp + eps) / (tp + alpha * fn + beta * fp + eps)
>     return tversky
> ```
> 
> And I have not try Focalloss, I don't know about it.

hi I have successfully implement you code. thanks for the response, To Implenment I need BCELoss. Can you give any help about how do you implement BCE and noise robust
 diceloss?

**Comment by HXLH50K** [comment]
> > > Hi, Can you tell me if this model FocalLoss Compatible? Can you help me with TverskyLoss? Because it is not implemented at utils.losses .
> > 
> > 
> > ```
> > class TverskyLoss(base.Loss):
> >     def __init__(self,
> >                  eps=1.,
> >                  activation=None,
> >                  alpha=0.5,
> >                  beta=0.5,
> >                  ignore_channles=None,
> >                  **kwargs):
> >         super().__init__(**kwargs)
> >         self.eps = eps
> >         self.activation = Activation(activation)
> >         self.alpha = alpha
> >         self.beta = beta
> >         self.ignore_channels = ignore_channles
> > 
> >     def forward(self, y_pr, y_gt):
> >         return 1 - F.tversky(
> >             y_pr,
> >             y_gt,
> >             eps=self.eps,
> >             threshold=None,
> >             alpha=self.alpha,
> >             beta=self.beta,
> >             ignore_channels=self.ignore_channels,
> >         )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > def tversky(pr,
> >             gt,
> >             eps=1e-7,
> >             alpha=0.5,
> >             beta=0.5,
> >             threshold=None,
> >             ignore_channels=None):
> >     """Calculate tversky cofficient between ground truth and prediction
> >     Args:
> >         pr (torch.Tensor): predicted tensor
> >         gt (torch.Tensor):  ground truth tensor
> >         eps (float): epsilon to avoid zero division
> >         threshold: threshold for outputs binarization
> >     Returns:
> >         float: dice score
> >     """
> > 
> >     pr = _threshold(pr, threshold=threshold)
> >     pr, gt = _take_channels(pr, gt, ignore_channels=ignore_channels)
> > 
> >     tp = torch.sum(gt * pr)
> >     fp = torch.sum(pr) - tp
> >     fn = torch.sum(gt) - tp
> > 
> >     tversky = (tp + eps) / (tp + alpha * fn + beta * fp + eps)
> >     return tversky
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And I have not try Focalloss, I don't know about it.
> 
> hi, I have successfully implement your code. thanks for the response, To implenment focal loss I need BCELoss. Can you give any help about how do you implement BCE and noise-robust
> diceless?

```
class NoiseRobustDiceLoss(base.Loss):
    def __init__(self,
                 eps=1.,
                 activation=None,
                 gamma=1.5,
                 ignore_channels=None,
                 **kwargs):
        super().__init__(**kwargs)
        self.eps = eps
        self.activation = Activation(activation)
        self.gamma = gamma
        self.ignore_channels = ignore_channels

    def forward(self, y_pr, y_gt):
        y_pr = self.activation(y_pr)
        return 1 - F.noise_robust_dice(
            y_pr,
            y_gt,
            eps=self.eps,
            threshold=None,
            gamma=self.gamma,
            ignore_channels=self.ignore_channels,
        )
```
```
def noise_robust_dice(pr,
                      gt,
                      eps=1e-7,
                      gamma=1.5,
                      threshold=None,
                      ignore_channels=None):
    """Calculate Noise Robust Dice cofficient between ground truth and prediction
    Args:
        pr (torch.Tensor): predicted tensor
        gt (torch.Tensor):  ground truth tensor
        eps (float): epsilon to avoid zero division
        gamma: scalar, [1.0, 2.0]. 
            When γ = 2.0, LNR-Dice equals to the Dice loss LDice. 
            When γ = 1.0, LNR-Dice becomes a weighted version of LMAE.
        threshold: threshold for outputs binarization
    Returns:
        float: dice score
    """

    pr = _threshold(pr, threshold=threshold)
    pr, gt = _take_channels(pr, gt, ignore_channels=ignore_channels)

    intersection = torch.sum(torch.pow(torch.abs(pr - gt), gamma))
    union = torch.sum(torch.square(gt)) + torch.sum(torch.square(pr)) + eps
    return 1 - intersection / union
```
BCE has implemented in original code, in losses.py
```
class BCELoss(nn.BCELoss, base.Loss):
    pass
```
just use it like other losses.
