### ISSUE TITLE
New segmentation models using transformers

### ISSUE THREAD

**Issue by isega24** [qubvel/segmentation_models.pytorch#402]
Are you thinking about implementing the new Vision Transformers models applied to semantic segmentation task?

**Comment by JulienMaille** [comment]
Maybe something can be done using https://github.com/qubvel/segmentation_models.pytorch/pull/374 ?

**Comment by JulienMaille** [comment]
Have you tried?

**Comment by isega24** [comment]
I have been trying before your comment to use the model from the official repository of swin transformers ( https://github.com/SwinTransformer/Swin-Transformer-Semantic-Segmentation ) and it also works for me. However, it is based on mmseg library.

**Comment by howtodowtle** [comment]
@isega24 You used the swin transformer direct from the SwinTransformer library, correct? Or did you somehow manage to use it within the `segmentation_models.pytorch` framework?
