### ISSUE TITLE
error when using fscore 

### ISSUE THREAD

**Issue by NIRVANALAN** [qubvel/segmentation_models.pytorch#41]
File "/home/lib/python3.7/site-packages/segmentation_models_pytorch/utils/functions.py", line 69, in f_score                                                     
tp = torch.sum(gt * pr)                                                                                                                                                       RuntimeError: expected backend CUDA and dtype Double but got backend CUDA and dtype Float

**Comment by NIRVANALAN** [comment]
my target is torch.double() so what's the problem?

**Comment by qubvel** [comment]
Cast your data to .float() (float32)

**Comment by NIRVANALAN** [comment]
Thanks, it works
