### ISSUE TITLE
ValueError: Model depth is 4, but you provide `decoder_channels` for 5 blocks.

### ISSUE THREAD

**Issue by sayakpaul** [qubvel/segmentation_models.pytorch#411]
I tried specifying the `encoder_depth` parameter as shown in README but met with the following error:

```
ValueError: Model depth is 4, but you provide `decoder_channels` for 5 blocks.
```

Here's how I tried to initialize the model:

```python
model = smp.Unet(
        encoder_name="resnet34",        
        encoder_weights=None, 
        encoder_depth=4
        in_channels=3,                  
        classes=1                      
)
```

Am I missing out on something?

**Comment by backdoorbreaker** [comment]
The default parameter for `decoder_channels` is a tuple of 5 values: `(256, 128, 64, 32, 16)`

You'll need to change that to a tuple of 4 values to match your encoder depth.

**Comment by sayakpaul** [comment]
Yes, right. Figured that out later. Maybe including this inside the docs would be more direct.
