### ISSUE TITLE
encoder outputs does not match with "out_channels" parameter

### ISSUE THREAD

**Issue by RedMoon32** [qubvel/segmentation_models.pytorch#412]
Hello! Can you please help, I am struggling to understand the following behaviour:

I want to create a new encoder based on effnet-b0 with reduced out channels size (to get a smaller but the same encoder model)

```
import segmentation_models_pytorch as smp
import torch

smp.encoders.encoders["enc_decreased"] =  smp.encoders.encoders["efficientnet-b0"].copy()
smp.encoders.encoders["enc_decreased"]["params"] = smp.encoders.encoders["efficientnet-b0"]["params"].copy()
smp.encoders.encoders["enc_decreased"]["pretrained_settings"] = None
smp.encoders.encoders["enc_decreased"]["params"]["out_channels"] = (3, 8, 12, 14, 16, 1280) # just as an example

for l in smp.Unet(
            encoder_name = "enc_decreased",
            encoder_weights = None,
            activation="softmax",
            in_channels=1,
            classes=3,
        ).encoder(torch.randn(1, 1, 224, 224)):

    print(l.shape)

```

It outputs default out_channels count of effnet-b0

```
torch.Size([1, 1, 224, 224])
torch.Size([1, 32, 112, 112])
torch.Size([1, 24, 56, 56])
torch.Size([1, 40, 28, 28])
torch.Size([1, 112, 14, 14])
torch.Size([1, 320, 7, 7])
```

but as I understand it should output 

```
torch.Size([1, 3, 224, 224])
torch.Size([1, 8, 112, 112])
torch.Size([1, 12, 56, 56])
torch.Size([1, 14, 28, 28])
torch.Size([1, 16, 14, 14])
torch.Size([1, 1280, 7, 7])
```

Can you please help with this?

**Comment by JulienMaille** [comment]
Should you give Unet an extra `decoder_channels` parameter?

**Comment by RedMoon32** [comment]
But in this example, I pass my tensor only through the encoder part, how the decoder channels are related to this?

**Comment by JulienMaille** [comment]
My bad, I misunderstood your issue.

**Comment by RedMoon32** [comment]
any update on this?

**Comment by qubvel** [comment]
Hi
It doesn't work that way, out_channels specific for each architecture. So you should identify out_channels for your encoder and provide it as attribute of encode. If you change just values in the list nothing happend except decoder will not work, because it relays on these values.
