### ISSUE TITLE
Bump up the timm version in the requirements.txt to the latest version of timm.

### ISSUE THREAD

**Issue by sugatoray** [qubvel/segmentation_models.pytorch#417]
Currently the version of `timm` for this library is `0.3.2`, but the latest version of `timm` is `0.4.9`. When I try installing `timm` and `segmentation-models-pytorch` using `conda`, since the latter can only be installed using `pip`, this effectively lowers the version of `timm` to `0.3.2`.

I assume that `timm` follows backward-compatibility and hence, `segmentation-models-pytorch` should work with later versions of `timm` as well.

So, is it possible to change the requirements from `timm==0.3.2` to `timm==0.4.9`?

```sh
# requirements.txt
torchvision>=0.3.0
pretrainedmodels==0.7.4
efficientnet-pytorch==0.6.3
timm==0.3.2
```

**Comment by psinger** [comment]
@qubvel 

Would it be possible to set it to

`timm >= 0.4.12`

Timm should be backwards compatible, and currently it breaks with any newer version of timm due to dependency conflicts.

**Comment by qubvel** [comment]
@psinger timm developing very fast, I am not sure it would be always backward compatible. 
It should be possible to force install a newer version

**Comment by psinger** [comment]
Problem is that if you put segmentation models in a `requirements.txt` and then try to install newer timm version it will fail due to dependency restrictions. But I see your point.
