### ISSUE TITLE
How do I use encoder and decoder separately

### ISSUE THREAD

**Issue by maxliubl** [qubvel/segmentation_models.pytorch#419]
model = smp.FPN('resnet34', in_channels=1)
feature = model.encoder(torch.ones([1, 1, 64, 64]))
masks = model.decoder(feature)

I got the following erro:
c2, c3, c4, c5 = features[-4:]
ValueError: not enough values to unpack (expected 4, got 0)
6

**Comment by nauyan** [comment]
@maxliubl have you been able to fix the issue?

**Comment by qubvel** [comment]
https://github.com/qubvel/segmentation_models.pytorch/blob/ad3e5c1273465e6a45f715a4852fdf76811e29f5/segmentation_models_pytorch/base/model.py#L13
