### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [64, 1, 7, 7], expected input[1, 3, 1278, 7087] to have 1 channels, but got 3 channels instead

### ISSUE THREAD

**Issue by ikonushok** [qubvel/segmentation_models.pytorch#442]
Павел, приветствую!
Запускаю на массивах npy и получаю вот такую ошибку: 
RuntimeError: Given groups=1, weight of size [64, 1, 7, 7], expected input[1, 3, 1278, 7087] to have 1 channels, but got 3 channels instead

При этом CHANNELS = 1, а исходные изображения с шейпом [1278, 7087], то есть, без канала
и ошибка где-то тут:
    _transform = [
        albu.Lambda(image=preprocessing_fn),
        albu.Lambda(image=to_tensor, mask=to_tensor),
    ]

Можете что-то посоветовать? Не могу понять где в Lambda из [1, 1, 1278, 7087] делается [1, 3, 1278, 7087]

Спасибо!

**Comment by gg22mm** [comment]
Me too. How to solve this problem?

install type :
pip install segmentation-models-pytorch
pip install dataclasses

**Comment by gg22mm** [comment]
Picture enhancement must be run

Data augmentation is a powerful technique to increase the amount of your data and prevent model overfitting.
If you not familiar with such trick read some of these articles:

**Comment by gg22mm** [comment]
必须要数据增强才能运行，我的就是这样的
