### ISSUE TITLE
set_in_channels() got an unexpected keyword argument 'pretrained'

### ISSUE THREAD

**Issue by woshisishen** [qubvel/segmentation_models.pytorch#451]
![Uploading 图片.png…]()
Hi,bro.I got this error but dont know how to fixed

**Comment by qubvel** [comment]
Could you provide a code example?

**Comment by woshisishen** [comment]
thanks，bro。I did not update torch 1.9
。 it is solved now

发自我的iPhone


------------------ Original ------------------
From: Pavel Yakubovskiy ***@***.***&gt;
Date: Thu,Jul 22,2021 1:08 PM
To: qubvel/segmentation_models.pytorch ***@***.***&gt;
Cc: woshisishen ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [qubvel/segmentation_models.pytorch] set_in_channels() got an unexpected keyword argument 'pretrained' (#451)





 
Could you provide a code example?

**Comment by woshisishen** [comment]
thanks，this issue can be solved by updating the ersion of pytorch



发自我的iPhone


------------------ Original ------------------
From: github-actions[bot] ***@***.***&gt;
Date: Thu,Mar 10,2022 10:02 AM
To: qubvel/segmentation_models.pytorch ***@***.***&gt;
Cc: woshisishen ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [qubvel/segmentation_models.pytorch] set_in_channels() got an unexpected keyword argument 'pretrained' (#451)





 
Closed #451.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
