### ISSUE TITLE
How can I use model.encoder and model.decoder alone?

### ISSUE THREAD

**Issue by bolgxh** [qubvel/segmentation_models.pytorch#455]
I tried the flollowing code, but get error when I use model.decoder .    head = features[0] IndexError: tuple index out of range

import segmentation_models_pytorch as smp
model = smp.Unet(
    encoder_name="resnet34",        # choose encoder, e.g. mobilenet_v2 or efficientnet-b7
    encoder_weights="imagenet",     # use `imagenet` pre-trained weights for encoder initialization
    in_channels=3,                  # model input channels (1 for gray-scale images, 3 for RGB, etc.)
    classes=3,                      # model output channels (number of classes in your dataset)
    decoder_channels = [256, 128, 64, 32, 16],
)
x = torch.randn((10, 3, 512, 512))
e = model.encoder(x)
e = e[-1].detach().numpy()
d = model.decoder(e)
print(d.shape)

**Comment by qubvel** [comment]
Decoder expects all features from the encoder. It doesn't work the way you try to use it.

**Comment by air-y** [comment]
I want to do the same, the same mistake

**Comment by air-y** [comment]
@qubvel Hello, is there a way to enable the output of the encoder to be correctly input into the decoder without error?

**Comment by zk-fmf** [comment]
> @qubvel Hello, is there a way to enable the output of the encoder to be correctly input into the decoder without error?

@qubvel I am trying to solve a different problem (add dropout layers to Unet) and I am having the same problem. Is there an elegant workaround? Thanks for help.

````
class MyUnet(nn.Module):
    def __init__(self):
        super(MyUnet, self).__init__()
     self.backbone = smp.Unet(encoder_name="resnet18", encoder_weights="imagenet", in_channels=1, classes=3)
     self.dropout = nn.Dropout()
    def forward(self, x):
        
        x = self.backbone(x)
        
        x = self.backbone.encoder.conv1(x)
        x = self.backbone.encoder.bn1(x)
        x = self.backbone.encoder.relu(x)
        x = self.backbone.encoder.maxpool(x)
        
        x = self.backbone.encoder.layer1(x)
        
        x = self.backbone.encoder.layer2(x)
        x = self.dropout(x)
        
        x = self.backbone.encoder.layer3(x)
        x = self.dropout(x)
        
        x = self.backbone.encoder.layer4(x)
        x = self.dropout(x)
        
        x = self.backbone.decoder.center(x)
        x = self.backbone.decoder.blocks[0](x)
        x = self.dropout(x)
        x = self.backbone.decoder.blocks[1](x)
        x = self.dropout(x)
        x = self.backbone.decoder.blocks[2](x)
        x = self.dropout(x)
        x = self.backbone.decoder.blocks[3](x)
        x = self.backbone.decoder.blocks[4](x)
        
        x = self.backbone.segmentation_head(x)
        
        return x
```

**Comment by qubvel** [comment]
```python
features = model.encoder(x)
features = [self.dropout(f) for f in features]
out = self.decoder(*features)
out = self.segmentation_head(out)
```
