### ISSUE TITLE
Dice Loss default eps should not be 1

### ISSUE THREAD

**Issue by CharlesNord** [qubvel/segmentation_models.pytorch#456]
The equation of Dice loss is

<img src="https://render.githubusercontent.com/render/math?math=1-\frac{2TP}{2TP %2B FN %2B FP}">

https://github.com/qubvel/segmentation_models.pytorch/blob/ec807040a580b6c5cb01240bf1fd275100c1858d/segmentation_models_pytorch/utils/losses.py#L28

in the DiceLoss class above, the default value of parameter `eps` is 1, it is passed to the following `f_score` function, 
https://github.com/qubvel/segmentation_models.pytorch/blob/ec807040a580b6c5cb01240bf1fd275100c1858d/segmentation_models_pytorch/utils/functional.py#L42

and the score is calculated as :
```
score = ((1 + beta ** 2) * tp + eps) \
            / ((1 + beta ** 2) * tp + beta ** 2 * fn + fp + eps)
```

where beta is 1.

So the score in the code is actually

```(2*tp+1)/(2*tp+fn+fp+1)```

the numerator and the denominator are both added one, although it won't affect the training, the value will differ from the "real" dice loss. So, maybe the default value of `eps` in the following line should be identical to it's default value in the function `f_score`, i.e., `1e-7`.

 https://github.com/qubvel/segmentation_models.pytorch/blob/ec807040a580b6c5cb01240bf1fd275100c1858d/segmentation_models_pytorch/utils/losses.py#L28

**Comment by sequoiagrove** [comment]
I noticed this too, but I got better results with eps = 1 than with e-7.
