### ISSUE TITLE
[Feature request] Add Unet3+

### ISSUE THREAD

**Issue by adnan33** [qubvel/segmentation_models.pytorch#458]
Hi there, Thank you for this great library and for making our life a whole lot easier.  I was wondering will you be adding unet 3+ to the library?
https://github.com/ZJUGiveLab/UNet-Version
@qubvel

**Comment by Namangarg110** [comment]
Hey @qubvel,
I would like to contribute to this feature

**Comment by qubvel** [comment]
Hi @Namangarg110 

It would be cool! Please look at the example of any network, e.g. Unet or Unet++ in smp. And, please, dont forget to add information in the docs and readme. Feel free to ask if anything is not clear. 
Thanks in advance!

**Comment by Namangarg110** [comment]
Cool then, I will start working on it. 
Do you have any resources to understand your repo structure and data flow better?

**Comment by qubvel** [comment]
Architecture is similar to Unet++, so you could take its code as a reference. #279

**Comment by Namangarg110** [comment]
Okay thanks,
also, is there a requirement for stacked Unet?
