### ISSUE TITLE
dice loss cannot work 

### ISSUE THREAD

**Issue by wwjwy** [qubvel/segmentation_models.pytorch#462]
When i use diceloss to train my dataset(4 classes), i meet error.

y_true = F.one_hot(y_true, num_classes)  # N,H*W -> N,H*W, C
RuntimeError: one_hot is only applicable to index tensor.

can you help me? 

Thanks!

**Comment by qubvel** [comment]
I assume your target should be type `long`

**Comment by wwjwy** [comment]
> I assume your target should be type `long`

I used the example provided by you, can you tell me where can i change the type of my target to ''long''? Thanks a lot!

**Comment by marcomameli1992** [comment]
The problem is not solved. I have the same problem with the actual version of the pack. How Can I solve it?

**Comment by Billy-ZTB** [comment]
Just edit the code of forward in dice.py :        
if self.mode == MULTICLASS_MODE:
            y_true = y_true.view(bs, -1)
            y_pred = y_pred.view(bs, num_classes, -1)
            if self.ignore_index is not None:
                mask = y_true != self.ignore_index
                print('mask size original:', mask.size())
                y_pred = y_pred * mask.unsqueeze(1)  
                y_true = F.one_hot((y_true * mask).to(torch.long), num_classes)  # N,H*W -> N,H*W, C
                y_true = y_true.permute(0, 2, 1) * mask.unsqueeze(1)  # N, C, H*W'''
            else:
                print('1: y_true size：',y_true.size())
                y_true = F.one_hot(y_true.to(torch.long), num_classes)  # N,H*W -> N,H*W, C     **add to(torch.long) here**
                print('2: y_true size：', y_true.size())
                y_true = y_true.permute(0, 2, 1)  # N, C, H*W
                print('3: y_true size：', y_true.size())

**Comment by Billy-ZTB** [comment]
> The problem is not solved. I have the same problem with the actual version of the pack. How Can I solve it?
> 
> If I try to use the target converted to long I receive th AssertionError that both the input has to be of the same type

Just edit the code of forward in dice.py :
if self.mode == MULTICLASS_MODE:
y_true = y_true.view(bs, -1)
y_pred = y_pred.view(bs, num_classes, -1)
if self.ignore_index is not None:
mask = y_true != self.ignore_index
print('mask size original:', mask.size())
y_pred = y_pred * mask.unsqueeze(1)
y_true = F.one_hot((y_true * mask).to(torch.long), num_classes) # N,HW -> N,HW, C
y_true = y_true.permute(0, 2, 1) * mask.unsqueeze(1) # N, C, HW'''
else:
print('1: y_true size：',y_true.size())
y_true = F.one_hot(y_true.to(torch.long), num_classes) # N,HW -> N,HW, C add to(torch.long) here
print('2: y_true size：', y_true.size())
y_true = y_true.permute(0, 2, 1) # N, C, HW
print('3: y_true size：', y_true.size())
