### ISSUE TITLE
ImportError: cannot import name 'ByoModelCfg'

### ISSUE THREAD

**Issue by onlinehuazai** [qubvel/segmentation_models.pytorch#464]
----> 1 from timm.models import ByoModelCfg, ByoBlockCfg, ByobNet
      2 
      3 from ._base import EncoderMixin
      4 import torch.nn as nn
      5 

ImportError: cannot import name 'ByoModelCfg'

**Comment by qubvel** [comment]
Looks like smp and timm versions does not match, please install proper versions according to requirements
