### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size, but got [3, 1088, 773] at entry 0 and [3, 384, 480] 

### ISSUE THREAD

**Issue by gg22mm** [qubvel/segmentation_models.pytorch#472]
I use my own datagram for the following errors

```bash
/usr/local/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py in default_collate(batch)
     53             storage = elem.storage()._new_shared(numel)
     54             out = elem.new(storage)
---> 55         return torch.stack(batch, 0, out=out)
     56     elif elem_type.__module__ == 'numpy' and elem_type.__name__ != 'str_' \
     57             and elem_type.__name__ != 'string_':

RuntimeError: stack expects each tensor to be equal size, but got [3, 1088, 773] at entry 0 and [3, 384, 480] at entry 1
```
down images:  https://github.com/gg22mm/python_resnet/blob/master/data.zip

**Comment by SteampunkIslande** [comment]
Hello ! I already saw this kind of errors, this is most likely because your images are not the same size in your dataset.

When pytorch creates a batch, it stacks `batch_size` images from your training set into one tensor. Pytorch has no way to tell how to stack images with different sizes.

One workaround would be to set `batch_size` to 1 (in your loader) and stack the images yourself in the __getitem__ method.

Using this method, you will likely have to pad the tensor to fit the largest image size.

**Comment by PooyanRezaeipour** [comment]
> Hello ! I already saw this kind of errors, this is most likely because your images are not the same size in your dataset.
> 
> When pytorch creates a batch, it stacks `batch_size` images from your training set into one tensor. Pytorch has no way to tell how to stack images with different sizes.
> 
> One workaround would be to set `batch_size` to 1 (in your loader) and stack the images yourself in the **getitem** method.
> 
> Using this method, you will likely have to pad the tensor to fit the largest image size.

Thank you so much sir!
I got my answer

**Comment by PooyanRezaeipour** [comment]
> Hello ! I already saw this kind of errors, this is most likely because your images are not the same size in your dataset.
> 
> When pytorch creates a batch, it stacks `batch_size` images from your training set into one tensor. Pytorch has no way to tell how to stack images with different sizes.
> 
> One workaround would be to set `batch_size` to 1 (in your loader) and stack the images yourself in the **getitem** method.
> 
> Using this method, you will likely have to pad the tensor to fit the largest image size.

My images weren't the same size.
I got my answer.
Thank you so much sir!
