### ISSUE TITLE
how to use TverskyLoss?

### ISSUE THREAD

**Issue by 775397252** [qubvel/segmentation_models.pytorch#482]
hello，I am a new user, i want to know how to use TverskyLoss?
```
loss = smp.losses.TverskyLoss('binary', eps=1e-6, alpha=0.3, beta=0.7)
```
but it made a mistake.
![截图_20211209011206](https://user-images.githubusercontent.com/7972945/132554227-df8f89e1-7d8e-4bcd-920c-b4b5532fa7b1.png)

**Comment by sequoiagrove** [comment]
All the losses under smp.losses.* do that. they changed the framework to use smp.utils.losses.* that don't have the "mode" (binary,multi*) but they have the __name__. tversky isnt in that losses package though.

**Comment by 775397252** [comment]
> All the losses under smp.losses.* do that. they changed the framework to use smp.utils.losses.* that don't have the "mode" (binary,multi*) but they have the **name**. tversky isnt in that losses package though.

so ，can you tell me how to solve it?

**Comment by swarmt** [comment]
See issue #399 

```python
loss.__name__ = 'TverskyLoss'
```
