### ISSUE TITLE
Loss functions not working

### ISSUE THREAD

**Issue by apournaras** [qubvel/segmentation_models.pytorch#496]
Do loss functions other than Dice and Jaccard work? For FocalLoss I get:
AttributeError: module 'segmentation_models_pytorch.utils.losses' has no attribute 'FocalLoss'

The same goes for every other loss in the documentation except Dice and Jaccard

**Comment by jeffreyscholz** [comment]
It has to be accessed with segmentation_models_pytorch.losses.Dice, but the behavior seems to have changed though...
