### ISSUE TITLE
Abou how to build from source

### ISSUE THREAD

**Issue by soon-will** [qubvel/segmentation_models.pytorch#5]
Thanks for your effort.
Could you please show how to build it from source?

**Comment by qubvel** [comment]
Hi @soon-will 
Use `pip install git+https://github.com/qubvel/segmentation_models.pytorch`

**Comment by soon-will** [comment]
Hi, @qubvel , thanks for your reply.
I try to install it offline. 

First, I download the file `segmentation_models.pytorch-master.zip`. And then, use `pip install segmentation_models.pytorch-master.zip` to install it, but there is an error:
`No matching distribution found for torchvision==0.2.2 (from segmentation-models-pytorch==0.0.1)`

In fact, I have installed the torchvision==0.2.2.

**Comment by qubvel** [comment]
use `--no-deps` flag for `pip install`

**Comment by soon-will** [comment]
Thank you. It works.
