### ISSUE TITLE
Question about activation in example

### ISSUE THREAD

**Issue by VSydorskyy** [qubvel/segmentation_models.pytorch#50]
In your [example](https://github.com/qubvel/segmentation_models.pytorch/blob/master/examples/cars%20segmentation%20(camvid).ipynb) you use Sigmoid activation at the end of the Unet. But at the same time all your losses and metrics are counted using one more sigmoid activation. Is it appropriate to use sigmoid activation twice?

**Comment by qubvel** [comment]
Hi, if you read README carefully, you will see that activation is used only for `.predict` method 😀

**Comment by VSydorskyy** [comment]
Got it. Thank you
