### ISSUE TITLE
Cannot open link in README.md

### ISSUE THREAD

**Issue by Seyoung9304** [qubvel/segmentation_models.pytorch#501]
Hi! 
During reading README.md, I found out that the URL linked at the end of **_"Training SMP model with Catalyst, TTAch, and Albumentation"_** is not working. 

I marked the part where the problem occurred in red. I'd appreciate it if you could check it out.

***

![image](https://user-images.githubusercontent.com/50132040/138093783-a2b0aea9-4a52-4778-84a2-d5c6910994bf.png)

**Comment by qubvel** [comment]
Fixed
