### ISSUE TITLE
How do I apply Timm Encoders?

### ISSUE THREAD

**Issue by hellojun12** [qubvel/segmentation_models.pytorch#504]
I'm trying to use xception65 with deeplabv3+.
Can't quite figure out how to use one.

**Comment by JulienMaille** [comment]
Have you tried `tu-xception65`?

**Comment by hellojun12** [comment]
@JulienMaille  Yes but I got `KeyError: 'tu-xception65'`.  But I'm not sure I put it in the right space. 
My code is like:
`    model = smp.DeepLapV3Plus(
        encoder_name="tu-xception65", 
        encoder_weights="imagenet",
        in_channels=3,
        classes=11
    )
`

**Comment by qubvel** [comment]
Install from package master branch

**Comment by December2018** [comment]
Can you give us a specific example?Thank you

**Comment by December2018** [comment]
> 

Can you give us a specific example?Thank you

**Comment by December2018** [comment]
> Install from package master branch

Can you give us a specific example?Thank you

**Comment by qubvel** [comment]
timm encoders already in pypi, just update wiith "pip install -U segmentation-models-pytorch==0.2.1" to use it

**Comment by December2018** [comment]
> timm encoders already in pypi, just update wiith "pip install -U segmentation-models-pytorch==0.2.1" to use it

I have updated to the new version and can use it successfully, thank you very much
