### ISSUE TITLE
Feature request: U-Net 3+

### ISSUE THREAD

**Issue by AKMourato** [qubvel/segmentation_models.pytorch#506]
Greetings.

First, congrats on this great library!

I believe U-Net 3+ would be a nice add-on to your available architectures.
Info:
[https://arxiv.org/abs/2004.08790](url)
repo:
https://github.com/ZJUGiveLab/UNet-Version
Is it in your plans?

Thanks.

**Comment by JulienMaille** [comment]
There is already one PR #474 and also these recent commits https://github.com/gregbugaj/segmentation_models.pytorch/commit/1264e1eb4194a79252c250dbbda30b0ebd51a244
