### ISSUE TITLE
Grayscale issues

### ISSUE THREAD

**Issue by antonino-tocco** [qubvel/segmentation_models.pytorch#508]
Hi, I have an issue using the library. I tried to doing training based on gray scale images and with binary mask (0, 255) values with 255 as foreground. If I specified channels = 1 an exception was raised for broadcast operands issue.
If I specify 3 channels and work on image like RGB image, I got mask with negative values before training.

Could you help me, please?

**Comment by Shawn94** [comment]
I`ve found out the solution to this problem:

You will need to expand dims to 1 of your mask images. ex: (512,640,1)
Normalize your mask image values. Normally in a single class, the values are either 255 or 0, so you should change it to 1 and 0, respectively.

**Comment by antonino-tocco** [comment]
Thanks a lot
