### ISSUE TITLE
how can i unfreeze the layers of vgg16/vgg11 encoder used with unet decoder?

### ISSUE THREAD

**Issue by mobassir94** [qubvel/segmentation_models.pytorch#51]
how can i unfreeze the layers of vgg16? i see your solution of this problem in segmentation model keras repository but not here for pytorch layer.trainable doesn't work here,any example please? and how many layers of vgg16 can be unfreezed while training with unet decoder for segmentation task? thanks a ton in advance

**Comment by qubvel** [comment]
Layers dont freeze by default, see example.
You can not update weights or set `require_grad=False` for all encoder layers (if you really need).
