### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by HasnainKhanNiazi** [qubvel/segmentation_models.pytorch#511]
I am trying to train DeepLabV3 with efficientnet-b7 and I am getting this error when trying to train the model. I am following the notebook provided in the examples. Please have a look at it and let me know what I am doing wrong. Thanks

`
Epoch: 0
train:   0%|          | 0/494 [00:00<?, ?it/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-0db0875a4c35> in <module>
      6 
      7     print('\nEpoch: {}'.format(i))
----> 8     train_logs = train_epoch.run(train_loader)
      9     valid_logs = valid_epoch.run(valid_loader)
     10 

~/anaconda3/envs/vedaseg/lib/python3.6/site-packages/segmentation_models_pytorch/utils/train.py in run(self, dataloader)
     43 
     44         with tqdm(dataloader, desc=self.stage_name, file=sys.stdout, disable=not (self.verbose)) as iterator:
---> 45             for x, y in iterator:
     46                 x, y = x.to(self.device), y.to(self.device)
     47                 loss, y_pred = self.batch_update(x, y)

~/anaconda3/envs/vedaseg/lib/python3.6/site-packages/tqdm/std.py in __iter__(self)
   1178 
   1179         try:
-> 1180             for obj in iterable:
   1181                 yield obj
   1182                 # Update and possibly print the progressbar.

~/anaconda3/envs/vedaseg/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    519             if self._sampler_iter is None:
    520                 self._reset()
--> 521             data = self._next_data()
    522             self._num_yielded += 1
    523             if self._dataset_kind == _DatasetKind.Iterable and \

~/anaconda3/envs/vedaseg/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _next_data(self)
   1201             else:
   1202                 del self._task_info[idx]
-> 1203                 return self._process_data(data)
   1204 
   1205     def _try_put_index(self):

~/anaconda3/envs/vedaseg/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
   1227         self._try_put_index()
   1228         if isinstance(data, ExceptionWrapper):
-> 1229             data.reraise()
   1230         return data
   1231 

~/anaconda3/envs/vedaseg/lib/python3.6/site-packages/torch/_utils.py in reraise(self)
    423             # have message field
    424             raise self.exc_type(message=msg)
--> 425         raise self.exc_type(msg)
    426 
    427 

ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/dual3080/anaconda3/envs/vedaseg/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/dual3080/anaconda3/envs/vedaseg/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dual3080/anaconda3/envs/vedaseg/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "<ipython-input-6-3957266c72ea>", line 48, in __getitem__
    sample = self.augmentation(image=image, mask=mask)
  File "/home/dual3080/.local/lib/python3.6/site-packages/albumentations/core/composition.py", line 182, in __call__
    data = t(force_apply=force_apply, **data)
  File "/home/dual3080/.local/lib/python3.6/site-packages/albumentations/core/transforms_interface.py", line 89, in __call__
    return self.apply_with_params(params, **kwargs)
  File "/home/dual3080/.local/lib/python3.6/site-packages/albumentations/core/transforms_interface.py", line 102, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))
  File "/home/dual3080/.local/lib/python3.6/site-packages/albumentations/augmentations/transforms.py", line 687, in apply_to_mask
    return F.shift_scale_rotate(img, angle, scale, dx, dy, cv2.INTER_NEAREST, self.border_mode, self.mask_value)
  File "/home/dual3080/.local/lib/python3.6/site-packages/albumentations/augmentations/functional.py", line 70, in wrapped_function
    result = func(img, *args, **kwargs)
  File "/home/dual3080/.local/lib/python3.6/site-packages/albumentations/augmentations/functional.py", line 225, in shift_scale_rotate
    height, width = img.shape[:2]
ValueError: not enough values to unpack (expected 2, got 1)
`

**Comment by maxfreu** [comment]
This is with high certainty a fault in your code and not in this library. Check your augmentation pipeline and boil the error down to a minimum failing example. Also, use backticks to format your code properly so that one can read it better :)

**Comment by HasnainKhanNiazi** [comment]
Thanks, I found the error, it was certainly in the CamVid notebook.
