### ISSUE TITLE
Which  dataset  do you  use  in  example.ipynb?

### ISSUE THREAD

**Issue by heartInsert** [qubvel/segmentation_models.pytorch#52]
Hi,  friend ,  I'm   new  to  `semantic segmentation` ,  so  I   have  to  understand   and test   every    step  in  your    example  code  ` cars segmentation (camvid).ipynb`,  
Can  you  tell  me  the  dataset's   name ,  so  I  can  download  it   and  run  this  example   convenient.
Thanks  for  your  help.

**Comment by laol777** [comment]
http://mi.eng.cam.ac.uk/research/projects/VideoRec/CamVid/

**Comment by heartInsert** [comment]
Thanks ,friend
