### ISSUE TITLE
Model breaking after changes that were made overnight 

### ISSUE THREAD

**Issue by ssnirgudkar** [qubvel/segmentation_models.pytorch#529]
Hello, 

My image segmentation model is breaking after the code changes that were pushed overnight. I am running pspnet on pytorch. 

Errors - 
loss function - modules utils has no attribute loss. To overcome that (based on your release notes that smp.utils.loss will be deprecated soon), i modified my code to use smp.losses instead 

But now it's failing in even loading the model - 
model = torch.load() 
Error - ModuleNotFoundError: No module named 'segmentation_models_pytorch.fpn'

**Comment by qubvel** [comment]
Hello, could you provide full traceback messages please?

**Comment by qubvel** [comment]
to load model and you can install stable version using PyPI `pip install segmentation-models-pytorch==0.2.1`

**Comment by ssnirgudkar** [comment]
thank you for your feedback. I already had 0.2.1, so that didnt help. here's the error. I also don't see init.py in decoders.
-------------

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-15-b0e8800e1aab> in <module>()
      2 #from segmentation_models_pytorch import decoders
      3 
----> 4 best_model = torch.load('abc')
      5 
      

2 frames
/usr/local/lib/python3.7/dist-packages/torch/serialization.py in find_class(self, mod_name, name)
    873         def find_class(self, mod_name, name):
    874             mod_name = load_module_mapping.get(mod_name, mod_name)
--> 875             return super().find_class(mod_name, name)
    876 
    877     # Load the data (which may in turn use `persistent_load` to load tensors)

ModuleNotFoundError: No module named 'segmentation_models_pytorch.fpn'

**Comment by qubvel** [comment]
You have the version installed from source code, but pypi version does not have breaking changes yet

Use -U flag to force install
`pip install -U segmentation-models-pytorch==0.2.1`

**Comment by ssnirgudkar** [comment]
Sorry, i misunderstood. 0.2.1 works technically, i don't get those errors anymore. However, is 0.2.1 - the backup package version right before the new changes were introduced? Reason being, when i run my model, the loss and IOU score is completely incorrect. Last night my model ran and completed around 2:30 AM - with 
train - dice_loss - 0.007814, iou_score - 0.9847
val - dice_loss - 0.0185, iou_score - 0.9642. Today after I run with 0.2.1, my inference has a val stats of - loss = 0.9 and IOU of 0.03. Is 0.2.1 - package right before the new code changes -because it's performance is completely different.

**Comment by qubvel** [comment]
You could check the commit history, but nothing was changed since the last release, check your pipeline once again please.

**Comment by qubvel** [comment]
You could even install version from previous commit (before overnight changes) to check
`pip install -U git+https://github.com/qubvel/segmentation_models.pytorch@<commit_hash>`

**Comment by ssnirgudkar** [comment]
I have finally been able to get the model to work with 0.2.1. Closing this issue.
