### ISSUE TITLE
TypeError: make_dilated() missing 1 required positional argument: 'dilation_list'

### ISSUE THREAD

**Issue by OneDirection67** [qubvel/segmentation_models.pytorch#535]
when I use DeepLabV3plus which use vgg16 or Xception as encoder,I met the error :
ypeError                                 Traceback (most recent call last)
<ipython-input-11-0da076f0c3cd> in <module>()
     35     classes=3,
     36     activation=None,
---> 37     in_channels=3,
     38 )
segmentation_models_pytorch/deeplabv3/model.py in __init__(self, encoder_name, encoder_depth, encoder_weights, encoder_output_stride, decoder_channels, decoder_atrous_rates, in_channels, classes, activation, upsampling, aux_params)
    144             depth=encoder_depth,
    145             weights=encoder_weights,
--> 146             output_stride=encoder_output_stride,
    147         )
    148 
segmentation_models_pytorch/encoders/__init__.py in get_encoder(name, in_channels, depth, weights, output_stride, **kwargs)
     78     encoder.set_in_channels(in_channels, pretrained=weights is not None)
     79     if output_stride != 32:
---> 80         encoder.make_dilated(output_stride)
     81 
     82     return encoder
TypeError: make_dilated() missing 1 required positional argument: 'dilation_list'
i don't konw how to solve it and what cause the problem.

**Comment by qubvel** [comment]
Sorry, those encoders are not supported. Try using some encoders from `timm` package with `support dilation` option, e.g. 
`tu-gluon_xception65` or `xception41`
see table here https://smp.readthedocs.io/en/latest/encoders_timm.html

**Comment by Cc-Hy** [comment]
@qubvel 
Hello， when I use the encoders with 'Support dilation' tag, like timm-resnest, timm-res2net, I still meet the error
`TypeError: make_dilated() missing 1 required positional argument: 'dilation_list'`
How can I fix the problem?

**Comment by thinkinds** [comment]
@qubvel 
I came across the same issue when trying to build a model of DeepLabV3Plus + timm-res2next50. 
Any solutions?
