### ISSUE TITLE
Efficientnet-unet did not improve compared with unet

### ISSUE THREAD

**Issue by wangshaonian666** [qubvel/segmentation_models.pytorch#543]
The mIoU of efficientnet-unet did not improve, but decreased compared with unet(backbone is vgg16). The efficientnet-unet can hardly detect some small defects. Can someone tell me why?  Thanks

**Comment by qubvel** [comment]
Not always a change of encoder will give you any boost, It depends on many factors, such as quality and size of the dataset, training pipeline, metric used, etc.
