### ISSUE TITLE
Unet: Handle arbitrarily sized input images.

### ISSUE THREAD

**Issue by jenkspt** [qubvel/segmentation_models.pytorch#545]
Currently the Unet model doesn't handle arbitrary input image sizes.

For example:
Here the spatial dimensions of the output don't match the input
```python
>>> import segmentation_models_pytorch as smp
>>> model = smp.Unet()
>>> img = torch.rand(1, 3, 127, 127)
>>> model(img).shape
torch.Size([1, 1, 128, 128])    # Spatial dims don't match input
```

And this input throws an error
```python
>>> img = torch.rand(1, 3, 129, 129)
>>> model(img).shape
RuntimeError                              Traceback (most recent call last)
...
...
.../decoder.py in forward(self, x, skip)
     36         x = F.interpolate(x, scale_factor=2, mode="nearest")
     37         if skip is not None:
---> 38             x = torch.cat([x, skip], dim=1)
     39             x = self.attention1(x)
     40         x = self.conv1(x)

RuntimeError: torch.cat(): Sizes of tensors must match except in dimension 1. Got 10 and 9 in dimension 2 (The offending index is 1)
```

**The Problem:**
When the spatial dims of the input to an encoder downsampling layer isn't a divisible by 2, there is a round-off of 1 pixel. When this feature is upsampled in the decoder using `F.interpolate`, the spatial dims won't match the skip connection.

**The Fix:**
The fix here is to replace `F.interpolate` with an upsampling layer that takes an additional (optional) argument `output_size`. It could look as follows:

```python

class Upsample
    def __init__(...)
        ...

    def forward(self, input, output_size)
        upsampled = F.interpolate(...)
        if upsampled.shape != output_size:
            # pad accordingly
        return upsampled
```

This is however a breaking change for any users (probably near zero) that rely on the current behavior (i.e when the output size doesn't match the input size)

I'm happy to create a pull request for this if it is agreed that this fix should be added

**Comment by qubvel** [comment]
Hi @jenkspt 
Thanks a lot for the suggestion, it may be a great feature!
However, as far as I know, interpolation with `scale_factor` is more friendly with exporting to other formats. It is a long time since I heard about these issues, maybe ONNX and jit trace are supporting dynamic shapes? It would be nice to investigate this question before changing current behavior.

**Comment by jenkspt** [comment]
Thanks for the quick feedback @qubvel!
The goal here isn't necessarily to support dynamic input image sizes --- but to support static input images with arbitrary (but known ahead of time) shape. As noted in the example above -- you an't use images that are 129 x 129 pixels (same goes images with dimensions 130, 131, 132, ... ect.).

The fix here is similar to what pytorch already does with ConvTranspose modules: see https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/conv.py#L765

I created a pull request for updating the `nn.Upsample` module in pytorch with the additional argument: see https://github.com/pytorch/pytorch/issues/71877 Maybe we wait for this to get resolved -- and use the updated `nn.Upsample` module here if it gets approved

I'm not familiar with how ONNX works -- but as far as torch.jit goes -- I don't see there being any problems with this feature -- I don't think it would behave any differently than ConvTranspose modules do currently. But perhaps I can contribute some additional jit script tests just to make sure.

**Comment by Fritskee** [comment]
> 

Could you actually provide me this fix already? I'm dealing with an issue that has a very similar error message.

**Comment by jenkspt** [comment]
@Fritskee linking your issue #548
