### ISSUE TITLE
ignore_index option in metrics

### ISSUE THREAD

**Issue by mrugnivenko** [qubvel/segmentation_models.pytorch#546]
I think that the ignore_index option in the metrics calculation isn't working right. 

Suppose I have 4 indexes - 0,1,2,3 and I wan't to ignore index 0 at metric calculation, then true positive output of smp.metrics.get_stats function with ignore_index=0 gives me [0, tp_for_index_1, tp_for_index_2, tp_for_index_3], so than futher calculation of dice score with "macro" averaging will account for that zero:

dice = (0 + dice_for_index_1 + dice_for_index_2 + dice_for_index_3)/4 - that isn't right assesment of dice, since I want to ignore the contribution of index=0 

The right way to calculate "macro" dice will be 

dice = (dice_for_index_1 + dice_for_index_2 + dice_for_index_3)/3

**Comment by qubvel** [comment]
Hi, thanks for the comment, you are right. 
I will think how to fix it. If you have any suggestions, you are welcome 😊

**Comment by qubvel** [comment]
Not the best fix, however, it will prevent unpredicted behavior
