### ISSUE TITLE
Unable to extract Metrics

### ISSUE THREAD

**Issue by pranavsinghps1** [qubvel/segmentation_models.pytorch#553]
I am currently using segmentation-models-pytorch 0.2.1, and tried installing from source as mentioned on the website(https://smp.readthedocs.io/en/latest/metrics.html#module-segmentation_models_pytorch.metrics.functional), But I am unable to use the get_status function, 

```
import segmentation_models_pytorch as smp
dir(smp)
>>output
['DeepLabV3',
 'DeepLabV3Plus',
 'FPN',
 'Linknet',
 'MAnet',
 'Optional',
 'PAN',
 'PSPNet',
 'Unet',
 'UnetPlusPlus',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'base',
 'create_model',
 'deeplabv3',
 'encoders',
 'fpn',
 'linknet',
 'losses',
 'manet',
 'pan',
 'pspnet',
 'torch',
 'unet',
 'unetplusplus',
 'utils'] 
```

When I go in Utils, I see Metrics, but within Metrics, there seems to be no "get_status" as elucidated in the Examples.

```
dir(smp.utils.metrics)
['Accuracy',
 'Activation',
 'F',
 'Fscore',
 'IoU',
 'Precision',
 'Recall',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'base']
```

**Comment by qubvel** [comment]
Try uninstall package and install it again, it is not updated.

**Comment by StevenLu1204** [comment]
I still cannot see the get_stats function. The metrics dir is not included in dir(smp).

**Comment by qubvel** [comment]
What is the command you execute to install/reinstall?

**Comment by qubvel** [comment]
I have bumped the version in source, its now should be 0.3.0-dev

**Comment by 2649** [comment]
Just install from the repo directly: pip install git+https://github.com/qubvel/segmentation_models.pytorch

**Comment by odkken** [comment]
@2649 @qubvel uninstalling and reinstalling from source worked for me.
