### ISSUE TITLE
is there any notebook for multiclass segmentation with pytorch lighning

### ISSUE THREAD

**Issue by johnahjohn** [qubvel/segmentation_models.pytorch#558]

**Comment by davodogster** [comment]
@qubvel please reopen it :) 
@johnahjohn

**Comment by JulienMaille** [comment]
There's an example using `pytorch_lightning` now: https://github.com/qubvel/segmentation_models.pytorch/blob/master/examples/binary_segmentation_intro.ipynb

**Comment by davodogster** [comment]
@JulienMaille Thanks but no, that is for binary not multiclass seg. The two are quite different to implement. Please let me know if you have a multiclass example! Cheers, Sam
