### ISSUE TITLE
KeyError: 'resnext50_32x4d'

### ISSUE THREAD

**Issue by hktxt** [qubvel/segmentation_models.pytorch#56]
what's wrong with resnext50_32x4d?
`model = smp.Unet("resnext50_32x4d", encoder_weights="imagenet", classes=4, activation='sigmoid')`
error:
KeyError: 'resnext50_32x4d' 
However, it's defined here:
https://github.com/qubvel/segmentation_models.pytorch/blob/master/segmentation_models_pytorch/encoders/resnet.py#L85

**Comment by qubvel** [comment]
Install from source, this have been added recently.
