### ISSUE TITLE
Custom encoder

### ISSUE THREAD

**Issue by noushinquazi** [qubvel/segmentation_models.pytorch#563]
Reposting from the discussions area as I am unsure where this is most relevant:

Is there a recommended approach to plugging in our own custom encoder into your architectures? For example, say I wanted to keep your decoder and specified a new custom encoder, is it possible for the decoder to adapt to this new encoder?

**Comment by qubvel** [comment]
Try this
https://smp.readthedocs.io/en/latest/insights.html#creating-your-own-encoder

**Comment by noushinquazi** [comment]
I need to have a resize transformation as the last operation in my custom encoder, but I get the following error: 

`ModuleAttributeError: 'Resize' object has no attribute 'weight'`

Do you know a clever way to side-step this weight check?

**Comment by noushinquazi** [comment]
> I need to have a resize transformation as the last operation in my custom encoder, but I get the following error:
> 
> `ModuleAttributeError: 'Resize' object has no attribute 'weight'`
> 
> Do you know a clever way to side-step this weight check?

Full stack trace below
```
ModuleAttributeError                      Traceback (most recent call last)
<ipython-input-4-7f303c3cb826> in <module>
     27 
     28 if MODEL == 'PSPNet':
---> 29     model = smp.PSPNet(
     30         encoder_name=ENCODER,        # choose encoder, e.g. mobilenet_v2 or efficientnet-b7
     31         encoder_weights=PRETRAINED_MODE,     # use `imagenet` pre-trained weights for encoder initialization

/usr/local/lib/python3.8/dist-packages/segmentation_models_pytorch/pspnet/model.py in __init__(self, encoder_name, encoder_weights, encoder_depth, psp_out_channels, psp_use_batchnorm, psp_dropout, in_channels, classes, activation, upsampling, aux_params)
     64         super().__init__()
     65 
---> 66         self.encoder = get_encoder(
     67             encoder_name,
     68             in_channels=in_channels,

/usr/local/lib/python3.8/dist-packages/segmentation_models_pytorch/encoders/__init__.py in get_encoder(name, in_channels, depth, weights, output_stride, **kwargs)
     76         encoder.load_state_dict(model_zoo.load_url(settings["url"]))
     77 
---> 78     encoder.set_in_channels(in_channels, pretrained=weights is not None)
     79     if output_stride != 32:
     80         encoder.make_dilated(output_stride)

/usr/local/lib/python3.8/dist-packages/segmentation_models_pytorch/encoders/_base.py in set_in_channels(self, in_channels, pretrained)
     27             self._out_channels = tuple([in_channels] + list(self._out_channels)[1:])
     28 
---> 29         utils.patch_first_conv(model=self, new_in_channels=in_channels, pretrained=pretrained)
     30 
     31     def get_stages(self):

/usr/local/lib/python3.8/dist-packages/segmentation_models_pytorch/encoders/_utils.py in patch_first_conv(model, new_in_channels, default_in_channels, pretrained)
     15             break
     16 
---> 17     weight = module.weight.detach()
     18     module.in_channels = new_in_channels
     19 

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
    776             if name in modules:
    777                 return modules[name]
--> 778         raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
    779             type(self).__name__, name))
    780 

ModuleAttributeError: 'Resize' object has no attribute 'weight'
```

**Comment by qubvel** [comment]
What is the number of input channels in your encoder?

**Comment by noushinquazi** [comment]
> What is the number of input channels in your encoder?

It expects grayscale images, so single channel. It outputs a feature map of shape (553, 22, 50) which I need to reshape to something where the width and height are divisible by 32 in order to work with your architectures

**Comment by noushinquazi** [comment]
temporarily, i've come up with a workaround in which i 'fool' the encoder initialization by providing a dummy Conv2d layer that my model does not actually use. of course this is pretty rough and a more elegant workaround is desired, but i will close this issue for now. thanks.
