### ISSUE TITLE
How to get class-specific metrics such as IOU score?

### ISSUE THREAD

**Issue by sarmientoj24** [qubvel/segmentation_models.pytorch#568]
Is there a way to have a class specific metric?

**Comment by noushinquazi** [comment]
https://smp.readthedocs.io/en/latest/losses.html

**Comment by sarmientoj24** [comment]
Hi. I am talking about the metrics and not losses. The metrics I can use
already but they are not class specific

**Comment by noushinquazi** [comment]
well you can use 1 - loss for some of them like IoU
