### ISSUE TITLE
UNet with no deep encoder

### ISSUE THREAD

**Issue by petksand** [qubvel/segmentation_models.pytorch#571]
Hi,

I wanted to know if it's possible to train the UNet model as it's described in its original paper, with no deep encoder. I'm not able to pass in `encoder_name=None`.

Thanks

**Comment by petksand** [comment]
I created my own encoder following the instructions from [here](https://smp.readthedocs.io/en/latest/insights.html#creating-your-own-encoder):

```py
class TestEncoder(nn.Module, EncoderMixin):
    def __init__(self):
        super().__init__()
        self._out_channels = [3,64,128,256,512,1024]
        self._depth = 5
        self._in_channels: int = 3

        ...
     
    
    def forward(self, x):
        ftrs = []
        for block in self.enc_blocks:
            x = block(x)
            ftrs.append(x)
            x = self.pool(x)
        return ftrs
```

and am registering it with:

```py
smp.encoders.encoders["test"] = {
    "encoder": TestEncoder, # encoder class here
    "pretrained_settings": {...}
     "params": {},
},
```
However, I get this error when I run `model = smp.Unet(encoder_name="test")`:

```py
[/usr/local/lib/python3.7/dist-packages/segmentation_models_pytorch/encoders/__init__.py](https://localhost:8080/#) in get_encoder(name, in_channels, depth, weights, output_stride, **kwargs)
     60 
     61     try:
---> 62         Encoder = encoders[name]["encoder"]
     63     except KeyError:
     64         raise KeyError("Wrong encoder name `{}`, supported encoders: {}".format(name, list(encoders.keys())))

TypeError: tuple indices must be integers or slices, not str
```

Was the encoder not properly registered?

**Comment by noushinquazi** [comment]
ah, is it possible that the pesky comma left at the end of the smp.encoders.encoders... right outside the last curly brace is leading python to interpret it as a tuple? happened to me once.

**Comment by petksand** [comment]
omg yes, that was the issue. Thank you! The docs included the comma, so I thought it was necessary.
