### ISSUE TITLE
torchvision 0.4

### ISSUE THREAD

**Issue by ternaus** [qubvel/segmentation_models.pytorch#58]
Why do we have a constraint on the torchvision version?

https://github.com/qubvel/segmentation_models.pytorch/blob/master/requirements.txt#L1

**Comment by phillies** [comment]
This was needed when torchvision renamed a variable which broke an import. @qubvel has fixed this in the current git version as far as I can see. I ran the tests and they looked fine. I created a pull request to change the requirements. You can should be able to use it with torchvision 0.4.0.

**Comment by qubvel** [comment]
Should work fine, @phillies thanks for request, I have update torchvision requirements in #63

**Comment by phillies** [comment]
Thanks @qubvel! Im not sure, however, if you need to restrict the requirements to torchvision<=0.4.0? I find reverting to a prior version easier than having to update the requirements.txt on every minor version update.

**Comment by qubvel** [comment]
It is not always clear for users that you have to revert to previous version, so it is better to fix and update later, than resolve issues.
