### ISSUE TITLE
Why does the ignore_index has to be outside the class range?

### ISSUE THREAD

**Issue by Legor** [qubvel/segmentation_models.pytorch#582]
When calculating smp.metrics.get_stats and using the ignore_index, why does the given index have to be outside the class value range? To me, this is kind of counterintuitive, since one would expect that you use this parameter to define the class that you want to ignore during the stats calculation. Hence you would provide the label of the class you would like to ignore.

https://github.com/qubvel/segmentation_models.pytorch/blob/8bf52c7e862af006e76a23aae6aa17977d7f9a79/segmentation_models_pytorch/metrics/functional.py#L144-L150

**Comment by americanexplorer13** [comment]
sorry, late answer, but here's the reason: https://github.com/qubvel/segmentation_models.pytorch/issues/546
