### ISSUE TITLE
ModuleNotFoundError: No module named 'segmentation_models_pytorch.datasets'

### ISSUE THREAD

**Issue by rohan-paul** [qubvel/segmentation_models.pytorch#587]
Line from the [official example](https://github.com/qubvel/segmentation_models.pytorch/blob/master/examples/binary_segmentation_intro.ipynb) giving error 

```py
from segmentation_models_pytorch.datasets import SimpleOxfordPetDataset
```
Produces

```
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-f85748ad8193>](https://localhost:8080/#) in <module>()
----> 1 from segmentation_models_pytorch.datasets import SimpleOxfordPetDataset

ModuleNotFoundError: No module named 'segmentation_models_pytorch.datasets'
```

**Comment by Khalaf90** [comment]
Install latest version from github:

!pip install -U git+https://github.com/qubvel/segmentation_models.pytorch

**Comment by Khalaf90** [comment]
Install latest version from github:

`!pip install -U git+https://github.com/qubvel/segmentation_models.pytorch`

**Comment by FrontierQ** [comment]
Hello,I ran this command '!pip install -U git+https://github.com/qubvel/segmentation_models.pytorch'，but it's still didn't work,can you help me?

**Comment by Khalaf90** [comment]
Hi, could you post the error you get ?
