### ISSUE TITLE
Model is extremely memory-consuming.

### ISSUE THREAD

**Issue by Cc-Hy** [qubvel/segmentation_models.pytorch#601]
Hello, I use the model to construct a efficentnet-b3 DeepLabV3 model with
`model = smp.DeepLabV3(encoder_name='efficientnet-b3', encoder_depth=5, encoder_weights='imagenet', decoder_channels=256, in_channels=3, classes=121, activation=None, upsampling=1, aux_params=None).cuda()`
With a batch of images (5,3,640,960),  I use
`feat= self.model.encoder(images)`
Then my device is out of memory ( 3090 with 24 G memory )
I did not even use backward, and the memory is used up.
Is there anything wrong? Or is a memory cost like it usual?

**Comment by neo133** [comment]
hi...did you solve this issue?
