### ISSUE TITLE
ONNX export problem with Unet

### ISSUE THREAD

**Issue by BEEugene** [qubvel/segmentation_models.pytorch#604]
Hi!

Sorry for reporting this as an issue, but maybe you have some clues on it.
I've tried to export a Unet with a ResNet encoder to onnx, but got really strange output.
Here is the example 
![example](https://user-images.githubusercontent.com/35495675/169700960-99b65d24-06fd-4cdc-9fb6-7999304d6754.png)

What am I doing wrong?
The full code is available [here](https://github.com/BEEugene/pytorch_onnx_oakd/blob/master/main.py) .

Best,
Evgeny

**Comment by BEEugene** [comment]
Seems, the problem is bigger than I thought as each time I receive different output

**Comment by OZOOOOOH** [comment]
@BEEugene hi I am faced with same issue. Did you solve it?

**Comment by BEEugene** [comment]
@OZOOOOOH, no I didn't. Could you also send the info about your issue.

**Comment by OZOOOOOH** [comment]
@BEEugene, Actually I solved it by changing the opset_version.
