### ISSUE TITLE
Many attributes have gone in version 0.3.0?

### ISSUE THREAD

**Issue by Shima-shoki** [qubvel/segmentation_models.pytorch#619]
Hi, thank you for the every efforts on the development of this great library!
I've been using it for a couple of days for segmentation tasks, and there were almost no problem of running the codes.
However, since the version 0.3.0, which was released several hours ago, I noticed that lots of attributes have gone to somewhere.
For example, the "utils" attribute is not found in the "segmentation_models_pytorch" if I install the version 0.3.0, while it is accessible in the version 0.2.1. 
I couldn't find this kind of changes in the release note of the version 0.3.0 but sorry if this is an intended change of the current version.
Screenshots from Google Colab are attached here to show the differences.

![Untitled](https://user-images.githubusercontent.com/47880765/181782273-57b604ec-0366-4b9e-8bd2-84672b1a3d3d.png)
![Untitled2](https://user-images.githubusercontent.com/47880765/181782312-ab9cda7d-df58-4a09-b55a-416638b79f7e.png)

**Comment by qubvel** [comment]
Utils are still here but should be imported manually
`import segmentation_models_pytorch.utils`

I am preparing for removing this module

**Comment by qubvel** [comment]
Added this to release notes, thanks

**Comment by qubvel** [comment]
Should probably update example notebook also

**Comment by Shima-shoki** [comment]
Thank you for the kind comments!
I am generally following the example code (since I'm quite new to this module), so it would be very much helpful if the changes are reflected in the example notebooks! For example, utils.lossess, utils.metrics, and utils.train are still very much needed for my segmentation pipeline...😅
