### ISSUE TITLE
Locked version of `timm` dependency

### ISSUE THREAD

**Issue by ligaz** [qubvel/segmentation_models.pytorch#620]
Is there a reason to depend on specific version of PyTorch Image Models `timm==0.4.12` instead of using something like `>=0.4.12` as a version specifier?

The context for the question is [this issue](https://github.com/Lightning-AI/lightning-flash/issues/1408).

**Comment by qubvel** [comment]
The reason is that API tends to change, especially in such quick-developing libraries as timm! In one day you can appear with not working code because of that, I prefer to fix the version, but you can always update it after installing.

**Comment by adamjstewart** [comment]
Would it be possible to lock it based on [semver](https://semver.org/) to something like `>=0.4.12,<0.7`? Also, would it be possible to update the locked version so we can use newer timm? In [TorchGeo](https://github.com/microsoft/torchgeo), we use dependabot to check to see if new versions break compatibility and use semver pins for all dependencies. This has proven to be extremely stable for us.

I've noticed that this isn't exactly the first issue to request support for modern versions of timm...

* #562
* #429
* #424
* #418
* #417
* #308
* #295
* #271

Given that one of the most popular feature requests in this library is upgrading the version of timm, I think it's safe to say that the current solution is problematic.

**Comment by qubvel** [comment]
I have updated timm version, but a new version, unfortunately, breaks the code 
https://github.com/qubvel/segmentation_models.pytorch/runs/7586507780?check_suite_focus=true

**Comment by qubvel** [comment]
I will fix and update it later, there are some changes, not seeing a quick fix for it

**Comment by adamjstewart** [comment]
Yeah, looks like TorchGeo doesn't work with segmentation_models_pytorch 0.3 either: https://github.com/microsoft/torchgeo/pull/692. Hoping we can figure out how to support both 0.2 and 0.3 so we don't have to pin to a specific version.

**Comment by JulienMaille** [comment]
On my side I add to change `_model_default_cfgs` to `_model_pretrained_cfgs` in:
https://github.com/qubvel/segmentation_models.pytorch/blob/c98c88d13481c956b232dec6fc13609859838d7a/segmentation_models_pytorch/encoders/__init__.py#L100
