### ISSUE TITLE
Colab notebook not found

### ISSUE THREAD

**Issue by robmarkcole** [qubvel/segmentation_models.pytorch#628]
https://github.com/googlecolab/colabtools/blob/master/examples/binary_segmentation_intro.ipynb linked on readme returns Notebook not found

**Comment by qubvel** [comment]
https://colab.research.google.com/drive/1ciyJPh5YWcC4-AHbMdtkkFWB2Fw-3aeC?usp=sharing

Check thi one, please

**Comment by robmarkcole** [comment]
Yes that one works

**Comment by robmarkcole** [comment]
Warning there appears to be an issue with the imports in the notebook:
```

ModuleNotFoundError: No module named 'torchtext.legacy'
```
