### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by TalhaOmi** [qubvel/segmentation_models.pytorch#629]
module 'segmentation_models_pytorch' has no attribute 'utils'

**Comment by qubvel** [comment]
Utils is deprecated, but in case you need it:

`from segmentation_models_pytorch import utils

**Comment by JulienMaille** [comment]
> Utils is deprecated, but in case you need it:
> 
> `from segmentation_models_pytorch import utils`

What's the replacement for `utils.train` ?

**Comment by qubvel** [comment]
Pytorch lightning ⚡ 
New example https://github.com/qubvel/segmentation_models.pytorch/blob/master/examples/binary_segmentation_intro.ipynb
