### ISSUE TITLE
Cannot import trained model

### ISSUE THREAD

**Issue by NyanSwanAung** [qubvel/segmentation_models.pytorch#630]
I have trained two unet++ models and the model format is in **.pth**.  A few days ago I can load the model but now I cannot load it anymore.

I used `torch.save(model, model_full_path)` to save the model and` torch.load(model_full_path)` to load the model.

It is giving me two errors for each model.

1st model 
name - unetplusplus-1.pth
error - `RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`

2nd model 
name - unetplusplus-2.pth
error -` ModuleNotFoundError: No module named 'segmentation_models_pytorch.unetplusplus'`

**Versions**
Pytorch - 1.12.1+cu102
SMP - 0.3.0

Here's the [link](https://drive.google.com/drive/folders/18ggY_ANjO-ld7dW-SBOiIKQlsKdNEEs8?usp=sharing) for model weights.

**Comment by ppm3012** [comment]
I am also facing this error, may be because of new release 0.3.0?

**Comment by qubvel** [comment]
Yes, downgrade to previous version please to load the model.
You can save weights only, and it will work across different versions

**Comment by ppm3012** [comment]
@qubvel downgrading to the previous version solved the ModuleNotFoundError but I'm still facing the RuntimeError.

**Comment by giorgionicola** [comment]
I am reopening since the error is still occuring while loadind trained model

`ModuleNotFoundError: No module named 'segmentation_models_pytorch.unet'`

SMP: 0.3.2
Pytorch: 1.10
