### ISSUE TITLE
Runtime Error on dice loss But model calculating loss while training

### ISSUE THREAD

**Issue by MUKILAN-2003** [qubvel/segmentation_models.pytorch#634]
RuntimeError: cannot reshape tensor of 0 elements into shape [0, 1, -1] because the unspecified dimension size -1 can be any value and is ambiguous

![image](https://user-images.githubusercontent.com/65155327/184580923-40cb57be-2583-4f01-9480-f682d8dfa6dd.png)

But how the loss is calculated while the 1st epoch training !? Is this a bug or I done any mistake ?

**Comment by i-aki-y** [comment]
The message suggests that the batch size of `y_true` is zero (`bs == 0`)
The `bs` is defined in dice.py in the following way:
`bs == y_true.size(0)`
So I think you should confirm that the condition `y_true.size(0) > 0` is satisfied.

**Comment by MUKILAN-2003** [comment]
@i-aki-y Thank You
Yeah I checked it too. and also I double checked the train and valid loader which return the y_true shape as (512,512)

**Comment by i-aki-y** [comment]
I see. But it seems weird because dataloader returns batched labels, so the shape of y_true would be (batch_size, 512, 512).
Can the dataloaders (train and validation) pass the following test?

```py
for batch in data_loader: 
    x, y = batch
    assert len(y.shape) == 3
    assert y.shape[0] > 0
```

**Comment by MUKILAN-2003** [comment]
@i-aki-y Sure I will check

**Comment by i-aki-y** [comment]
Hi @MUKILAN-2003 . Unfortunately, I could not reproduce the error. I think it is difficult to identify the problem from current information.
If you can reproduce the error, you can get more information by running the `%pdb` magic before the training code and seeing what is happening in the data in debug mode.

**Comment by MUKILAN-2003** [comment]
Sure @i-aki-y I will update Once I have done
