### ISSUE TITLE
AttributeError: module 'segmentation_models_pytorch' has no attribute 'metrics'

### ISSUE THREAD

**Issue by MirandaLv** [qubvel/segmentation_models.pytorch#635]
Running the binary example, and received the errors when running this line of code. 

tp, fp, fn, tn = smp.metrics.functional.ts(pred_mask.long(), mask.long(), mode="binary")

When add the "from segmentation_models_pytorch import metrics", received the below error.

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/3970350/184689630-f3623500-9269-4503-ad27-2f55db5e92e4.png">

**Comment by t110368027** [comment]
Hi [MirandaLv](https://github.com/MirandaLv)
I had this problem too, 
I tried to package the smp.metrics into a separate python file like this below,
[segmentation_models_pytorch/metrics/functional.py](https://github.com/qubvel/segmentation_models.pytorch/blob/master/segmentation_models_pytorch/metrics/functional.py) to  smp_metrics.py.
and import it, this solved the problem.

`import smp_metrics`

**Comment by MirandaLv** [comment]
> 

Thanks! Did you download the entire github repo and import the smp_metrics from segmentation_models_pytorch? I installed the segmentation_models_pytorch through pip, and once I import smp_metrics, it shows that "No module named 'smp_metrics'", if I change the import to "from segmentation_models_pytorch import smp_metrics", I got below errors:

![image](https://user-images.githubusercontent.com/3970350/184917692-11c16011-a261-43e5-801e-5a6ba86cd588.png)

**Comment by t110368027** [comment]
Hi [MirandaLv](https://github.com/MirandaLv),

I think i didn't explain my method clearly, sorry.

That means you need to create a new python file, name as what you want for example is `smp_metrics.py` or `new_metrics.py`
then copy all pyhton code from here [segmentation_models_pytorch/metrics/functional.py](https://github.com/qubvel/segmentation_models.pytorch/blob/master/segmentation_models_pytorch/metrics/functional.py) to your new python file .

And you can `import smp_metrics` or `import new_metrics` call all metrics method.

```python=3.7
import smp_metrics
tp, fp, fn, tn = smp_metrics.functional.ts(pred_mask.long(), mask.long(), mode="binary")
```
or
```python=3.7
import new_metrics
tp, fp, fn, tn = new_metrics.functional.ts(pred_mask.long(), mask.long(), mode="binary")
```

**Comment by MirandaLv** [comment]
Thank you, it works!

**Comment by KudoKhang** [comment]
`
import segmentation_models_pytorch.utils.metrics
`

**Comment by toralero** [comment]
thanks i was stuck on this point forever trying to get DeepLabV3 to work on this kaggle notebook
https://www.kaggle.com/code/balraj98/deepglobe-land-cover-classification-deeplabv3/notebook
