### ISSUE TITLE
No module named 'timm'

### ISSUE THREAD

**Issue by minhson1411** [qubvel/segmentation_models.pytorch#636]
please help me fix this bug
<img width="1159" alt="Screen Shot 2022-08-16 at 13 54 49" src="https://user-images.githubusercontent.com/76195341/184818001-5a77f7a7-e3b9-430a-a0ca-117a9e7bd75f.png">

**Comment by t110368027** [comment]
hi minhson1411,
It's probably not a bug, you need this package
https://github.com/qubvel/segmentation_models.pytorch/blob/792c2735aa0e926afa17d1105eace63ef2dcc624/requirements.txt#L4
`pip install timm==0.4.12
`

**Comment by minhson1411** [comment]
> hi minhson1411, It's probably not a bug, you need this package
> 
> https://github.com/qubvel/segmentation_models.pytorch/blob/792c2735aa0e926afa17d1105eace63ef2dcc624/requirements.txt#L4
> 
> 
> `pip install timm==0.4.12 `

Thanks, it worked!
