### ISSUE TITLE
ModuleNotFoundError: No module named 'torchtext.legacy' in colab

### ISSUE THREAD

**Issue by lappemic** [qubvel/segmentation_models.pytorch#639]
When i tried to follow the notebook in [Training model for pets binary segmentation with Pytorch-Lightning](https://colab.research.google.com/github/qubvel/segmentation_models.pytorch/blob/master/examples/binary_segmentation_intro.ipynb#scrollTo=H4RKHF535Twz) i encountered the problem that when the line 
```python 
import pytorch_lightning as pl
```
is executed, the ModuleNotFoundError in the title appears. Just installing torchtext.legacy with 
```python
!pip install torchtext.legacy
```
did not solve the problem.

**Comment by Z4HRA-S** [comment]
I have this issue too!

**Comment by maxogden** [comment]
I also have this issue
