### ISSUE TITLE
examples folder is out of date

### ISSUE THREAD

**Issue by FlorinAndrei** [qubvel/segmentation_models.pytorch#645]
Binary segmentation works, with some warnings.

Cars segmentation flat out refuses to work. The smp API has changed quite a lot and the example uses the old API. That's unfortunate, because it's an example of using smp with plain Pytorch, which would be very useful.

Would be great to have a basic example, using only Pytorch, no Lightning, no preprocessing, nothing except pure smp with the current API, showing all the steps from model creation, to training, to testing and visualization.

**Comment by schnuri-schnuri** [comment]
First, I also had problems with Cars segmentation.
Using a Linux system, a Cuda-compatible GPU, and manually downloading the file that refuses to download on its own fixed it for me.

**Comment by chefkrym** [comment]
> Binary segmentation works, with some warnings.
> 
> Cars segmentation flat out refuses to work. The smp API has changed quite a lot and the example uses the old API. That's unfortunate, because it's an example of using smp with plain Pytorch, which would be very useful.
> 
> Would be great to have a basic example, using only Pytorch, no Lightning, no preprocessing, nothing except pure smp with the current API, showing all the steps from model creation, to training, to testing and visualization.

Hi @FlorinAndrei did you ever manage to do this, on just plain smp?

**Comment by FlorinAndrei** [comment]
@chefkrym no, I gave up on it.
