### ISSUE TITLE
issue generating models with mix vision transformer encoders

### ISSUE THREAD

**Issue by K-D-Gallagher** [qubvel/segmentation_models.pytorch#646]
I noticed that Mix Vision Transformer encoders are now listed as available. I was trying to generate a unet model with one of these encoders, but have been getting an error that it's not a supported encoder. I tried mit_b0, 3, and 5. Is there a particular prefix to use with these, like with the timm encoders? Thanks.

**Comment by qubvel** [comment]
Hi, it is not release to pypi, please install latest version from github repo to use these encoders

**Comment by qubvel** [comment]
`$ pip install -U git+https://github.com/qubvel/segmentation_models.pytorch`

**Comment by K-D-Gallagher** [comment]
Ah yes it worked, thank you so much! Looking forward to seeing how these encoders perform

**Comment by qubvel** [comment]
Let me know if you find it useful for your task)

**Comment by K-D-Gallagher** [comment]
It definitely boosted performance a bit! Maybe ~2% over my previously best optimized architecture/encoder combo. Thanks!
