### ISSUE TITLE
SSL error when trying to load ImageNet weights for se_resnext101_32x4d encoder with any backbone.

### ISSUE THREAD

**Issue by jphdotam** [qubvel/segmentation_models.pytorch#653]
As above - this pretrained model's weights do not work. This seems to be an isolated problem for this encoder.

**Comment by tr31zh** [comment]
Not sure if same error

While following [The CamVid tutorial](https://github.com/qubvel/segmentation_models.pytorch/blob/master/examples/cars%20segmentation%20(camvid).ipynb) 

I get this error after: 
`URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>`

`
ENCODER = 'se_resnext50_32x4d'
ENCODER_WEIGHTS = 'imagenet'
CLASSES = ['car']
ACTIVATION = 'sigmoid' # could be None for logits or 'softmax2d' for multiclass segmentation
DEVICE = 'cuda'

#create segmentation model with pretrained encoder
model = smp.FPN(
    encoder_name=ENCODER, 
    encoder_weights=ENCODER_WEIGHTS, 
    classes=len(CLASSES), 
    activation=ACTIVATION,
)

preprocessing_fn = smp.encoders.get_preprocessing_fn(ENCODER, ENCODER_WEIGHTS)`

**Comment by jphdotam** [comment]
Yep same error.

**Comment by DavidTorpey** [comment]
Same error

**Comment by TolgaBkm** [comment]
This solution worked for me:
[https://github.com/qubvel/segmentation_models.pytorch/issues/144#issuecomment-585754975](url)

**Comment by tteresi7** [comment]
While the above solution would work, it's not safe.  It appears the problem is that the host servers certificates expired in July and have not been updated.  If you have access to the host it's better to update the ssl certificate on the host, otherwise I'd suggest changing hosts.

**Comment by aneeqahazmat** [comment]
Just change the encoder name to resnet50 will work

**Comment by khozaimi** [comment]
same error for densenet201

**Comment by qubvel** [comment]
Hey @khozaimi! I gonna move all weight to HF Hub to avoid this error
