### ISSUE TITLE
Metric calculation for multiclass

### ISSUE THREAD

**Issue by H1ghSpeed** [qubvel/segmentation_models.pytorch#661]
Hello, I have 8 classes. On some images, some masks are missing, the metric considers such classes as 100%, which affects the final result of the metric calculation. Tell us how you can cut off classes that do not have masks when calculating the final metric.
![image](https://user-images.githubusercontent.com/105350275/193216967-6ccce7e1-3d35-4f4e-99b1-a688459d2c1a.png)

**Comment by davodogster** [comment]
Hi @H1ghSpeed did you train multiclass using Segmentation models with pytorch lightning? or just segmentation models pytorch?
