### ISSUE TITLE
Questions on Dilated Convolution on U-Net Encoder

### ISSUE THREAD

**Issue by sarmientoj24** [qubvel/segmentation_models.pytorch#662]
I saw that there is a function `make_dilated` somewhere in the ResNet encoder code.

Does this mean that this ResNet has Dilated Convolutions by default or do I need to turn it on/off?

Moreover, can you point me a diagram that is exactly what your U-Net code follows?

**Comment by qubvel** [comment]
Hi, dilated convolutions not used in Unet, make_dilated function called for Deeplab and Manet decoders

**Comment by sarmientoj24** [comment]
@qubvel do you have any link for a diagram that is the nearest with this U-Net implementation?

I saw that the UNet Decoder doesnt seem to have a Bottleneck/Center block layer here for backbones like ResNet, 
https://github.com/sarmientoj24/segmentation_models.pytorch/blob/1fa49d0953708c0a61ab11c5cc4052d20909a9bc/segmentation_models_pytorch/decoders/unet/decoder.py#L95-L96
