### ISSUE TITLE
How to Exactly Create a New Encoder without Copying the Whole Repo

### ISSUE THREAD

**Issue by sarmientoj24** [qubvel/segmentation_models.pytorch#663]
Is it possible to just add a `.py` file somewhere in my code and do this? 
https://smp.readthedocs.io/en/latest/insights.html#creating-your-own-encoder

Or do I need to fork this repo, add a new encoder, do this, and use that?

Also, how do you create a modified version of a Decoder?

**Comment by qubvel** [comment]
You don't need to fork repo to create new encoder, just  write your code and register it

**Comment by sarmientoj24** [comment]
@qubvel 
Do you register the model within the same `.py` as the custom encoder?

Extra question: Does the SCSE Attention Module only happen in the decoder?
