### ISSUE TITLE
Converting to TorchScript using scripting.

### ISSUE THREAD

**Issue by hgaiser** [qubvel/segmentation_models.pytorch#669]
Currently the models from this repository cannot be converted to TorchScript using scripting. Ie. the following fails:

```python
import torch.jit
import segmentation_models_pytorch as smp

model = smp.Unet()
script = torch.jit.script(model)
```

With this error:

```
RuntimeError: 
tuple slice indices must be integer constants:
  File "/tmp/2022-10-10-13-30-03/venv/lib/python3.10/site-packages/segmentation_models_pytorch/encoders/_base.py", line 20
    def out_channels(self):
        """Return channels dimensions for each tensor of forward output of encoder"""
        return self._out_channels[: self._depth + 1]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
```

Converting models using scripting has a huge benefit of preserving dynamic logic. I can look into making this conversion possible, but I thought I'd discuss this change first. Perhaps this has already been attempted in the past?

ps. if you opt-in for [Hacktoberfest](https://hacktoberfest.com/) it also helps my progress there ;p

**Comment by qubvel** [comment]
Hi @hgaiser 

It would be great to have this feature, I personally use model tracing, because it works for such cases.
There were some discussions about that feature previously, but I don't remember any PR or suggestions on how to solve this, just issues
