### ISSUE TITLE
What is the commonly used reduction for metrics using multiclass segmentation?

### ISSUE THREAD

**Issue by sarmientoj24** [qubvel/segmentation_models.pytorch#674]
I am unsure what reduction (e.g. micro, macro, micro-imagewise, etc.) are used in literature for the metrics.

**Comment by jistiak** [comment]
Hi @sarmientoj24, have you already gone though the documentations? I guess you will find your answer here - 

https://smp.readthedocs.io/en/latest/metrics.html

**Comment by sarmientoj24** [comment]
@jistiak i did, so these are the "reduction" that is commonly used in literatures?

```
# then compute metrics with required reduction (see metric docs)
iou_score = smp.metrics.iou_score(tp, fp, fn, tn, reduction="micro")
f1_score = smp.metrics.f1_score(tp, fp, fn, tn, reduction="micro")
f2_score = smp.metrics.fbeta_score(tp, fp, fn, tn, beta=2, reduction="micro")
accuracy = smp.metrics.accuracy(tp, fp, fn, tn, reduction="macro")
recall = smp.metrics.recall(tp, fp, fn, tn, reduction="micro-imagewise")
```

**Comment by newzealandpaul** [comment]
@sarmientoj24 I think you are wanting mIoU with macro reduction if you are wanting to compare with, for example, Cityscape benchmarks:

https://paperswithcode.com/sota/semantic-segmentation-on-cityscapes
