### ISSUE TITLE
Compute Tp,Tn,Fp,Fn for Multiclass Classification following the Cars segmantation example

### ISSUE THREAD

**Issue by hanshassler** [qubvel/segmentation_models.pytorch#682]
I am unsure where to get  Tp,Tn,Fp,Fn from when following the cars segmentation example. I Created my own multiclass dataset, but when calling the metrics i need those variables from above. I just dont know how to receive them ?

**Comment by AlexDs20** [comment]
Hi,

This function https://github.com/qubvel/segmentation_models.pytorch/blob/6bcf28733df20076f1f4e380728cf2167856ce85/segmentation_models_pytorch/metrics/functional.py#L61

returns the tp, tn, fp, fn
