### ISSUE TITLE
AttributeError: module 'segmentation_models_pytorch' has no attribute 'utils'

### ISSUE THREAD

**Issue by santurini** [qubvel/segmentation_models.pytorch#688]
I was following the cars example but I keep getting this error. I installed the module with pip in both suggested ways but I keep getting this error even if I checked the presence of utils in the repo. What am I doing wrong?

This is the code:

```
!pip install git+https://github.com/qubvel/segmentation_models.pytorch
# !pip install -q segmentation-models-pytorch

train_epoch = smp.utils.train.TrainEpoch(
    model, 
    loss=loss, 
    metrics=metrics, 
    optimizer=optimizer,
    device=DEVICE,
    verbose=True,
)
```

**Comment by qubvel** [comment]
try this, but basically utils is deprecated
```
from segmentation_models_pytorch import utils as  smp_utils

train_epoch = smp_utils.train.TrainEpoch(
    model, 
    loss=loss, 
    metrics=metrics, 
    optimizer=optimizer,
    device=DEVICE,
    verbose=True,
)
```

**Comment by santurini** [comment]
Thank you! 
While regarding the DiceLoss in utils.losses, is it already multilabel? And can I pass directly the output of the 'softmax2d'?
