### ISSUE TITLE
MixVisionTransformer in combination with PAN fails with "encoder does not support dilated mode"

### ISSUE THREAD

**Issue by Daniel451** [qubvel/segmentation_models.pytorch#695]
```
import segmentation_models_pytorch as smp

smp.PAN(encoder_name="mit_b0")
```
raises the exception:
```
ValueError: MixVisionTransformer encoder does not support dilated mode
```

Since the default PAN uses dilation, this config is uncompatible atm?

If we use a configuration of PAN that does not use dilation the error, of course, does not apper:
```
smp.PAN(encoder_name="mit_b0", encoder_output_stride=32)
```
I did not test yet though if output strides of 32 still deliver comparable results. My guess would be that the default stride of 16 should encode a lot more of information that might be beneficial for better performence.

Is there any way to get it to work with dilation?

**Comment by qubvel** [comment]
Hi, MIT does not support dilated mode, because it does not have convolution layers

**Comment by Daniel451** [comment]
@qubvel then I would like to propose this PR https://github.com/qubvel/segmentation_models.pytorch/pull/697 to raise an exception. Otherwise the code would execute and fail later during PyTorch attempting to do a forward run and users have to debug why this fail happens.
