### ISSUE TITLE
Not possible to pass encoder_weights='None' for ResNet18, ResNet34 or ResNet50 (Unet)

### ISSUE THREAD

**Issue by sbj028** [qubvel/segmentation_models.pytorch#701]
As mentioned in #574 and #420 it is not possible to use neither a ResNet18, ResNet34 or ResNet50 with   #encoder_weights='None'. I have only tested for the Unet architecture and the Pytorch implementation. 

While the documentation says that we can pass either encoder_weights='imagenet' or encoder_weights='None', see https://segmentation-modelspytorch.readthedocs.io/en/latest/docs/api.html#unet, passing encoder_weights='None' results in the following errors. (listed ### after enocoder_name): 

- ResNet18: 
`unet18 =  smp.Unet(encoder_name='resnet18', encoder_depth=5, encoder_weights='None', decoder_use_batchnorm=True, decoder_channels=(256, 128, 64, 32, 16), decoder_attention_type=None, in_channels=3, classes=1, activation='sigmoid')` 
returns: 
```
raise KeyError("Wrong pretrained weights `{}` for encoder `{}`. Available options are: {}".format(
KeyError: "Wrong pretrained weights `None` for encoder `resnet18`. Available options are: ['imagenet', 'ssl', 'swsl']"

```
- ResNet34: 
`unet34 =  smp.Unet(encoder_name='resnet34', encoder_depth=5, encoder_weights='None', decoder_use_batchnorm=True, decoder_channels=(256, 128, 64, 32, 16), decoder_attention_type=None, in_channels=3, classes=1, activation='sigmoid')` 
returns: 
```
   raise KeyError("Wrong pretrained weights `{}` for encoder `{}`. Available options are: {}".format(
KeyError: "Wrong pretrained weights `None` for encoder `resnet34`. Available options are: ['imagenet']"
```
- ResNet50 
`unet50 =  smp.Unet(encoder_name='resnet50', encoder_depth=5, encoder_weights='None', decoder_use_batchnorm=True, decoder_channels=(256, 128, 64, 32, 16), decoder_attention_type=None, in_channels=3, classes=1, activation='sigmoid')` 
returns: 
```
raise KeyError("Wrong pretrained weights `{}` for encoder `{}`. Available options are: {}".format(
KeyError: "Wrong pretrained weights `None` for encoder `resnet50`. Available options are: ['imagenet', 'ssl', 'swsl']"
```

The documentation for UNet should at least be modified so that it doesn't say that 'None' is an option.

**Comment by JulienMaille** [comment]
Try `None` instead of `'None'`

**Comment by sbj028** [comment]
Off course, thanks! It works.
