### ISSUE TITLE
Issue new release for timm upgrade

### ISSUE THREAD

**Issue by chrisjkuch** [qubvel/segmentation_models.pytorch#704]
Hey @qubvel!

Might you consider issuing a new release to reflect the upgrade on `main` to `timm==0.6.12`? As a sub-dependency of the image/video extras in [lightning-flash](https://github.com/Lightning-AI/lightning-flash) this would help me with some compatibility issues.

Many thanks,
Chris

**Comment by qubvel** [comment]
Hi @chrisjkuch 
Yes, sure, I will do it tomorrow 👍

**Comment by qubvel** [comment]
Updated (#705)
