### ISSUE TITLE
Feature request: make optional second output in the middle of the network.

### ISSUE THREAD

**Issue by ternaus** [qubvel/segmentation_models.pytorch#71]
It would be nice to have an option to add output in the middle of the network for downsampled mask.

Should help with convergence.

**Comment by qubvel** [comment]
What kind of output woud you like? Is encoder output ok or somewhere from decoder?

**Comment by cswwp** [comment]
How should i change the model output? for instance add a classify output, Inherit the EncoderDecoder class and rewrite ?

**Comment by qubvel** [comment]
@cswwp look at readme (auxiliary classification output already implemented)

**Comment by ternaus** [comment]
The same mask as an output, but possibly downscaled.

**Comment by cswwp** [comment]
> @cswwp look at readme (auxiliary classification output already implemented)

Thanks, got it
