### ISSUE TITLE
Modify minimum python version in readme

### ISSUE THREAD

**Issue by semaphore-egg** [qubvel/segmentation_models.pytorch#711]
The minimum python version has been updated in `v0.3.2`:
`Minimum Python version 3.6 -> 3.7`

The readme page might be updated as well:
`[![Python - Version](https://img.shields.io/badge/PYTHON-3.6+-red?style=for-the-badge&logo=python&logoColor=white)](https://pepy.tech/project/segmentation-models-pytorch)`

**Comment by qubvel** [comment]
Thanks
