### ISSUE TITLE
Dice Losses computed for the whole batch

### ISSUE THREAD

**Issue by lassefschmidt** [qubvel/segmentation_models.pytorch#712]
Hello there!

First of all, thank you for this great package!  

Maybe I am mistaken, but when looking into the implementation of the dice loss I noticed that it computes the loss across the whole batch rather than over each image. At least for me this lead to extremely bouncy gradients when running loss.backward(). After going over some literature, I also always found that the loss should be computed across each image and then reduced (e.g. in most cases just the mean). In fact, computing it for the whole batch vs. for each image and then average gives very different results.

Luckily, the fix is very easy. In this [script](https://github.com/qubvel/segmentation_models.pytorch/blob/master/segmentation_models_pytorch/losses/dice.py), change within the code of class DiceLoss the forward function line 72 to dims = (2) instead of dims = (0,2).

At least this gives the desired outputs for multiclass problems, no matter the batchsize (tested batch sizes 1 and 3 and 32 and all worked perfectly fine). I didn't test other cases though.

Best,
Lasse

**Comment by rafikoham** [comment]
hey, I don't know if you also have witnessed a certain error like : 
-----------------------------------
 y_true = F.one_hot(y_true, num_classes)  # N,H*W -> N,H*W, C
RuntimeError: one_hot is only applicable to index tensor.
-----------------------------------

I've investigated a little bit, and I think it better to calculate the indices before doing one_hot and permuting like this : 

` indices = torch.clamp(
 torch.round(y_true) + 1, min=0, max=num_classes - 1 ).long()
 y_true = F.one_hot(indices, num_classes)  # N,H*W -> N,H*W, C
  y_true = y_true.permute(0, 2, 1)  # N, C, H*W`

instead
