### ISSUE TITLE
Error in Reading annotations in Custom dataset: Object is read as background 

### ISSUE THREAD

**Issue by aymanaboghonim** [qubvel/segmentation_models.pytorch#716]
I am trying to replicate cars segmentation (camvid) example but using my own datatset with single class.
While I am reading the annotations, it reads the object (building) as background, background as object.
![image](https://user-images.githubusercontent.com/62246708/218303408-b8d3a68d-a6de-404a-9e68-99312790d3ab.png)
how to handle this issue ?
I checked my original mask/ annotation and there is no issue, here is an example 
![image](https://user-images.githubusercontent.com/62246708/218303564-3234c4aa-1797-4c46-9587-56e0a3ca02e9.png)

**Comment by aymanaboghonim** [comment]
in the original example : object should be in yellow color while background is in violet color.
![image](https://user-images.githubusercontent.com/62246708/218304971-baf4d84b-dbcd-4fa3-bb48-b9fa669ed5fd.png)

**Comment by aliman80** [comment]
Thanks for such a great contribution . I am also trying to use it for segmentation task , can you guide how can i use it for my dataset, my dataset comprised of train and validation images and masks with .json files for labels
