### ISSUE TITLE
How would one add Unet3+ and Unet3+wDS to the repository?

### ISSUE THREAD

**Issue by mjr1ch** [qubvel/segmentation_models.pytorch#719]
I am more than willing to give it a go if I new how you did it. Do you have any tips or general guidlines how to link those frameworks to the encoders as you did for Unet and Unet++

**Comment by JulienMaille** [comment]
Have a look here: https://github.com/qubvel/segmentation_models.pytorch/issues/506

**Comment by mjr1ch** [comment]
@JulienMaille 
Thank you for the prompt reply. I see discussion of the Unet3+ model but I do not see it in the Master branch on git. Is it being held out because of bugs? Also any work on the variation with Deep Supervision. I could maybe give it a try based on the 3+ version.
