### ISSUE TITLE
Pretrained Download Error

### ISSUE THREAD

**Issue by Junhyuk93** [qubvel/segmentation_models.pytorch#723]
hello.!

I am receiving the mit_b3 pretrained model, but the speed is too slow and I am getting disconnected while receiving it. Any solution?
(I checked and the mix vision Transformer model pretrained are all the same issue.)

I appreciate your time and assistance. Thank you.

**Comment by qubvel** [comment]
Hi, weights are hosted by GitHub, check your internet connection is stable, Thanks

**Comment by Junhyuk93** [comment]
It worked out fine. thank you! 👍

**Comment by Junhyuk93** [comment]
It worked out fine. thank you! 👍
