### ISSUE TITLE
Extract the features latent space  of encoder in DeeplabV3+ with ResNet101

### ISSUE THREAD

**Issue by Sarmadfismael** [qubvel/segmentation_models.pytorch#725]
Hi all 
I used the following definition to implement the semantic segmentation model: 

model = smp.DeepLabV3Plus(encoder_name='resnet101', 
                          encoder_depth=5,
                          encoder_weights='imagenet',
                          encoder_output_stride=16, 
                          decoder_channels=256,
                          decoder_atrous_rates=(12, 24, 36), 
                          in_channels=3,
                          classes=6, 
                          activation=None,
                          upsampling=4,
                          aux_params=None) 

Now i want to find the feature maps of the encoder part only, 
i do the following:

y = model. Encoder(x) # x in size: 8,3,256,256

i find the wrong size in y, which is list with Len = 6  

How can i read the feature of encoder part only? which should be 2048 features based on ResNet101 architecture. 

can you help me?

**Comment by qubvel** [comment]
Hi, encoder returns all the feature maps, you can take only the last one
```python
features = model.encoder(x)
y = features[-1]  # torch tensor with shape [N, 2048, H / 32, W / 32]
```

**Comment by Sarmadfismael** [comment]
Thank you for your replying 
Can i use features [-2:0] as a multi-layer feature map?

**Comment by qubvel** [comment]
`model.encoder(x)` returns a list of features with different spatial and channel dimensions, you could use any of them

**Comment by Sarmadfismael** [comment]
Thank you so much, i appreciate that.
