### ISSUE TITLE
SyntaxWarning: "is" with a literal. Did you mean "=="?

### ISSUE THREAD

**Issue by IgnatovD** [qubvel/segmentation_models.pytorch#728]
Hi all!

If I install python>=3.8.1 and segmentation-models-pytorch==0.32.2, then an warning occurs on import `import segmentation_models_pytorch as smp`. The warning appears in library `pretrainedmodels`.

```
Python 3.9.15 (main, Mar 13 2023, 09:18:54) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import segmentation_models_pytorch as smp
/home/jovyan/.cache/pypoetry/virtualenvs/s-outer-seg-sem-facade-mvp280223smp-82NsP1dj-py3.9/lib/python3.9/site-packages/pretrainedmodels/models/dpn.py:255: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if block_type is 'proj':
/home/jovyan/.cache/pypoetry/virtualenvs/s-outer-seg-sem-facade-mvp280223smp-82NsP1dj-py3.9/lib/python3.9/site-packages/pretrainedmodels/models/dpn.py:258: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif block_type is 'down':
/home/jovyan/.cache/pypoetry/virtualenvs/s-outer-seg-sem-facade-mvp280223smp-82NsP1dj-py3.9/lib/python3.9/site-packages/pretrainedmodels/models/dpn.py:262: SyntaxWarning: "is" with a literal. Did you mean "=="?
  assert block_type is 'normal'
```

The warning disappears when I install python 3.7.5.

In segmentation version 0.3.1 updated `Codebase refactoring and style checks (black, flake8)`. I think the problem is in the flake8. And in python 3.7.5. maybe flake8 is being ignored.

Is there a way to disable flake8? To turn off the warning python >= 3.8.

**Comment by qubvel** [comment]
Hi, flake8 is not integrated into the package itself, it is just a check code for each commit in CI/CD GitHub actions

**Comment by qubvel** [comment]
I guess it might be a native python warning that has been introduced in 3.9

**Comment by TCherici** [comment]
This is an issue stemming from the dependency on the `pretrainedmodels` package, which seems to be effectively unmaintained since ~2018.
A fix for this issue [was already presented in 2020](https://github.com/Cadene/pretrained-models.pytorch/pull/195), but is yet to be reviewed and merged.

I'm not too sure of how easy it would be to drop this dependency, as I'm not familiar with this repository's codebase, but I'd be willing to help out

**Comment by qubvel** [comment]
This would be not so easy to drop, but the warning could be just caught with `warnings.filterwarnings`. You could try it in your code and propose PR to smp. Thanks.

**Comment by rusmux** [comment]
@qubvel Any progress on this?

**Comment by TCherici** [comment]
@rusmux What version of segmentation_models_pytorch are you running? I can't seem to reproduce the issue with the latest version (0.3.3)

**Comment by rusmux** [comment]
Yeah, sorry, seems like I was using outdated version
