### ISSUE TITLE
encoders do not support "dilated mode" but which ones do support?

### ISSUE THREAD

**Issue by GrigoriiTarasov** [qubvel/segmentation_models.pytorch#730]
Such error occurs when used
Decoder in at least [DeepLabV3, DeepLabV3PlusPlus]
Encoder family in at least [Resnet, VGG]

It there a method to find the list of encoders supported by particular decoder?

**Comment by dulicui742** [comment]
Is there a problem with the decoder processing of dilated mode?

**Comment by GrigoriiTarasov** [comment]
New update seem to bring such information on the page https://smp.readthedocs.io/en/latest/encoders_timm.html

**Comment by bipulneupane** [comment]
Hi there, is there any pre-trained vgg19 weight that works with DeepLabv3+? I could not find them on the timm encoder list [https://smp.readthedocs.io/en/latest/encoders_timm.html](url). I could not be sure if these are VGG encoders:
repvgg_a2,r epvgg_b0, repvgg_b1, repvgg_b1g4, repvgg_b2, repvgg_b2g4, repvgg_b3, repvgg_b3g4.
