### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by adamjstewart** [qubvel/segmentation_models.pytorch#731]
PyTorch 2.0 was released this week, adding Python 3.11 support. We're trying to update TorchGeo to add Python 3.11 support: https://github.com/microsoft/torchgeo/pull/1180

I'm not sure if segmentation-models-pytorch has Python 3.11 support yet, but it's pinned to timm 0.6.12, which definitely doesn't have Python 3.11 support. I'm hoping to get them to make a new timm 0.6.13 release in the near future: https://github.com/huggingface/pytorch-image-models/issues/1723

From your side, this issue is designed to track two feature requests:

1. Update, or preferably relax, the timm dependency version. Something like `timm>=0.6.12,<0.7` may be appropriate depending on how much we can trust timm to maintain backwards compatibility within minor releases.
2. Add Python 3.11 to the CI testing matrix. Hopefully there are no bugs in this repo and everything will work smoothly once the timm dependency version is updated.

**Comment by qubvel** [comment]
Hi, here is the pipeline (#736) with 
 - python 3.11
 - pytorch 2.0.0
 - torchvision 1.15.0
 
It fails due to timm currently. I will update dependencies once the new compatible timm version is released.

**Comment by adamjstewart** [comment]
New timm release is now out!

**Comment by adamjstewart** [comment]
Anything I can help with to make the next release happen?

**Comment by adamjstewart** [comment]
Ping @qubvel

**Comment by adamjstewart** [comment]
timm 0.9 has now been released...

**Comment by valhassan** [comment]
I am facing the same issues with Python 3.11 Pytorch 2.0 support. This is a bottleneck at the moment

**Comment by adamjstewart** [comment]
Confirmed that v0.3.3 now supports Python 3.11. Thanks for your help!
