### ISSUE TITLE
will you add Swin Transformer any time soon

### ISSUE THREAD

**Issue by almahdir1** [qubvel/segmentation_models.pytorch#732]

**Comment by qubvel** [comment]
Hi, the swin transformer encoder is available with "tu-" (timm) encoders

**Comment by almahdir1** [comment]
Any idea how to use swin as backbone with the available architectures in your library.

**Comment by qubvel** [comment]
Just checked, swin is not available yet with this timm version
You could try `mit-b0` .. `mit-b5` if you want to use transformer as a backbone (`mit` is segformer encoder)

**Comment by kamen007** [comment]
Does the latest version support swinv2?

**Comment by qubvel** [comment]
Btw it's supported with the latest version!
