### ISSUE TITLE
The focal Tversky loss is different from the paper

### ISSUE THREAD

**Issue by zifuwanggg** [qubvel/segmentation_models.pytorch#734]
In Eq (4). of the focal Tversky loss [paper](https://arxiv.org/pdf/1810.07842.pdf), the gamma term is applied per-class. 

Therefore,

https://github.com/qubvel/segmentation_models.pytorch/blob/8523324c116dcf7be6bddb73bf4eb1779ef6e611/segmentation_models_pytorch/losses/tversky.py#L56

should be `return torch.pow(loss, self.gamma).mean()`.

**Comment by qubvel** [comment]
Hi, thanks, would you mind making a PR?
