### ISSUE TITLE
Expired SSL certificate

### ISSUE THREAD

**Issue by rikyeahh** [qubvel/segmentation_models.pytorch#745]
`SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)`

when running

```
ENCODER = 'se_resnext50_32x4d'
ENCODER_WEIGHTS = 'imagenet'
CLASSES = ['car']
ACTIVATION = 'sigmoid' # could be None for logits or 'softmax2d' for multiclass segmentation
DEVICE = 'cuda'

# create segmentation model with pretrained encoder
model = smp.FPN(
    encoder_name=ENCODER, 
    encoder_weights=ENCODER_WEIGHTS, 
    classes=len(CLASSES), 
    activation=ACTIVATION,
)
```

from your examples files (car dataset). Indeed, the link Downloading: "http://data.lip6.fr/cadene/pretrainedmodels/se_resnext50_32x4d-a260b3a4.pth" I should be downloading the weights from, uses http and not https

**Comment by qubvel** [comment]
Hi, as a replacement you could use encoders from timm:
https://smp.readthedocs.io/en/latest/encoders_timm.html

I will try to fix it in a while

**Comment by 2xuexiao** [comment]
import  ssl
ssl._create_default_https_context = ssl._create_unverified_context
