### ISSUE TITLE
License for Mix Vision Transformer

### ISSUE THREAD

**Issue by vecxoz** [qubvel/segmentation_models.pytorch#747]
Thanks a lot for the Mix Vision Transformer implementation. It works great!
I wonder what is the license for its code/weights? Is it non-commercial (according to [SegFormer](https://github.com/NVlabs/SegFormer/blob/master/LICENSE))? 
Thanks in advance.

**Comment by qubvel** [comment]
Code is changed, and weights are changed too by fine-tuning. I am not sure how it works for such cases, it is better to consult with someone else.
