### ISSUE TITLE
AttributeError: 'Unet' object has no attribute 'in_channels'

### ISSUE THREAD

**Issue by ytl0623** [qubvel/segmentation_models.pytorch#753]
Hi, everyone! I was trying to print the model's in_channel, but something was wrong.

The code is like below.
`import segmentation_models_pytorch as smp

model = smp.Unet(
        encoder_name="resnet34",        # choose encoder, e.g. mobilenet_v2 or efficientnet-b7
        encoder_weights="imagenet",     # use `imagenet` pre-trained weights for encoder initialization
        in_channels=3,                  # model input channels (1 for gray-scale images, 3 for RGB, etc.)
        classes=2,                      # model output channels (number of classes in your dataset)
)

print(model.in_channels)`

And the error message.
`    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Unet' object has no attribute 'in_channels'`

How can I get the model channel correctly?

Thanks!

**Comment by lucasvw** [comment]
Which version are you running? I think the in_channels only came with 0.3.1
