### ISSUE TITLE
pip package install does not include utils folder. 

### ISSUE THREAD

**Issue by AndrewFalkowski** [qubvel/segmentation_models.pytorch#754]
Installing the package form pip into an anaconda environment does not appear to include files in the `utils` folder.

Calling `dir(smp)` returns the following:

```
['DeepLabV3',
 'DeepLabV3Plus',
 'FPN',
 'Linknet',
 'MAnet',
 'PAN',
 'PSPNet',
 'Unet',
 'UnetPlusPlus',
 '_Optional',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_torch',
 'base',
 'create_model',
 'datasets',
 'decoders',
 'encoders',
 'losses',
 'metrics']
```

**Comment by AndrewFalkowski** [comment]
Adding an update:

I was able to fix the issue by downloading the repo and adding the following import to `segmentation_models_pytorch/__init__.py`:

`from . import utils`

**Comment by datasith** [comment]
whelp, thank you for the timely fix @AndrewFalkowski! just ran into this myself
