### ISSUE TITLE
Include mAP as Evaluation Metric

### ISSUE THREAD

**Issue by Mirzyaaliii** [qubvel/segmentation_models.pytorch#766]
Hello,

First of all, thank you very much, for such an amazing package.

Can you include **mean Average Precision (mAP)** as an evaluation metric? 
Almost all segmentation-based papers show an evaluation on mAP.

-----------

I have a query regarding this -

I am also working on a segmentation task (specifically, binary segmentation) and I want to calculate mAP between mAP. However, I am not sure how to calculate mAP between 2 masks (i.e., ground truth and prediction), as shown example in the below image.

![Screenshot 2023-05-27 at 5 48 59 PM](https://github.com/qubvel/segmentation_models.pytorch/assets/46327378/3ec597d0-44ee-4e8b-8c66-32c5f648d928)

Also, we cannot use the [COCOeval script](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocoEvalDemo.ipynb) for that as it requires a [score](https://cocodataset.org/#format-results) given by the model. And segmentation models like U-Net and FPN only generate masks without predicting the score for each masked region. (Please let me know if I am missing anything for this part.)

It would be helpful if anyone can point out to useful implementation/code (to calculate mAP for segmentation) or give some insights.

**Comment by Rickylht** [comment]
I think you can use cv2.largestcomponent to first extract each segmented object. And then **the average value** (or maybe 0.8 quantile whatever) of pixels inside each object (the original predicted mask, not the binarized mask) can be regarded as the confident score.

**Comment by Mirzyaaliii** [comment]
Yes, I was doing the same. However, instead of considering any threshold or quantile, I took the average of the pixel values of the masked region before converting it to a binarized mask to get a score for that particular mask (predicted object).

Thanks for your response!!
