### ISSUE TITLE
ignore_index doesn't work for get_stats

### ISSUE THREAD

**Issue by americanexplorer13** [qubvel/segmentation_models.pytorch#769]
I have 3 classes + 1 background, so when I try to use:

`tp, fp, fn, tn = smp.metrics.get_stats(torch.argmax(pred, dim=1).unsqueeze(0).long(), mask.round().long(), num_classes=self.num_classes, mode=self.mode, ignore_index=-1)`

where num_classes = 4, 
it appears, that tp, fp, fn, tn still have 4 values with 0 as background. What am I doing wrong?

**Comment by HaoranTang** [comment]
i have the same question, did you figure out in the end..?

**Comment by americanexplorer13** [comment]
> i have the same question, did you figure out in the end..?

Hey @HaoranTang! Actually, I didn't find any solution for this... The only way to do this, just calculate it manually one by one and then drop a background. That's the only answer what I have. Good luck!
