### ISSUE TITLE
torch.load fails with "No module named 'segmentation_models_pytorch.unet'" in newer versions of Python

### ISSUE THREAD

**Issue by SixtyTrees** [qubvel/segmentation_models.pytorch#772]
I've installed smp on Anaconda env with Python 3.6 and it was very easy. Trained the model, loaded with torch.load("my_model.pth"). This worked. Now I try to convert it to onnx model. onnx doesn't support Python 3.6 (requires at least pep 517). 
I've created a new conda environment with Python 3.10 (and 3.11). onnx now installes, but torch.load returns "ModuleNotFoundError: No module named 'segmentation_models_pytorch.unet'".

Is there a good version of Python that works for both smp and onnx? Or is there an alternative way to import torch; torch.load(my_path)?

**Comment by qubvel** [comment]
You could downgrade just SMP version for your newer env with Python 3.10 in order to load model

**Comment by qubvel** [comment]
`pip install -U segmentation-models-pytorch==<version_model_was_trained_with>`
