### ISSUE TITLE
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1])

### ISSUE THREAD

**Issue by DhruvAwasthi** [qubvel/segmentation_models.pytorch#778]
I have a four gpu setup (24 GB each) where I am trying to train a DeepLabV3Plus model. I am experimenting with different encoders available. However with some encoders I am able to finetune it but with some (for example, `dpn131` with `imagenet` weights) I come across these errors:
> ValueError: Caught ValueError in replica 0 on device 0.
> ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1])

The batch size I am using is `8`. I am using all RGB images.

Can you please help me resolve this issue?
Thank you!

**Comment by qubvel** [comment]
Hi, probably your images are too small, try feeding images with larger spatial resolution

**Comment by DhruvAwasthi** [comment]
I have high resolution image ~1024x1024.

**Comment by GrigoriiTarasov** [comment]
The possible reason in error in nn.Parallel, try define model without it. If it works on 1 GPU then all you have to do is to tune batch parameter.

**Comment by DhruvAwasthi** [comment]
I tried that with one GPU, but it wasn't working either. Since it was not working, I stopped trying and went ahead with some SAM.
