### ISSUE TITLE
Feature request: Add an option to use concatenation in FPN

### ISSUE THREAD

**Issue by ternaus** [qubvel/segmentation_models.pytorch#78]
Right now we have summation in https://github.com/qubvel/segmentation_models.pytorch/blob/master/segmentation_models_pytorch/fpn/decoder.py#L103

it saves some memory, but in many cases people use concatenation. It would be nice to add such a feature.

**Comment by SiarheiFedartsou** [comment]
https://github.com/qubvel/segmentation_models.pytorch/pull/82
