### ISSUE TITLE
SSL certificate has expired error when using a pretrained model

### ISSUE THREAD

**Issue by gitaar9** [qubvel/segmentation_models.pytorch#797]
When trying to use a pretrained Unet with an se_resnext50_32x4d encoder, i get the following error:

    result = func(*args)
  File "/opt/conda/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/conda/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>

When I do not opt for a pretrained model everything works as expected.
Is this a problem on my side or are more people experiencing this error?

**Comment by jaswindersingh2** [comment]
This may help! https://github.com/qubvel/segmentation_models.pytorch/issues/745

**Comment by gitaar9** [comment]
Thank you
