### ISSUE TITLE
Update CamVid example

### ISSUE THREAD

**Issue by alexcjwei** [qubvel/segmentation_models.pytorch#814]
I tried following the example, but got `AttributeError: module 'segmentation_models_pytorch' has no attribute 'utils'` in the call `loss = smp.utils.losses.DiceLoss()`. I'm importing with `!pip install segmentation-models-pytorch` then `import segmentation_models_pytorch as smp`. I think it should be just `loss = smp.losses.DiceLoss()` now?

**Comment by alexcjwei** [comment]
Also was doing this from Kaggle, maybe that's why?

**Comment by SuperSecureHuman** [comment]
working on this
