### ISSUE TITLE
Mix ViT in_channels restriction

### ISSUE THREAD

**Issue by chrislfathom** [qubvel/segmentation_models.pytorch#823]
What's the reasoning behind limiting the Mix Visual Transformer encoder #632 to 3 input channels?

https://github.com/qubvel/segmentation_models.pytorch/blob/master/segmentation_models_pytorch/encoders/mix_transformer.py#L468

I couldn't spot anything in the paper or the original SegFormer implementation.

**Comment by lucasc896** [comment]
I've removed the restriction and the model appears to learn. Is there any argument for this restriction?

**Comment by kamen007** [comment]
How to remove the restriction? I want to train with 6 channels,but the program is throwing an error.

**Comment by qubvel** [comment]
Would appreciate a PR to fix it! It's basically to enable changing the number of channels in the first conv layer
