### ISSUE TITLE
EfficientNet-PyTorch eating Memory very fast

### ISSUE THREAD

**Issue by mobassir94** [qubvel/segmentation_models.pytorch#83]
please watch this and do the necessary changes : https://www.kaggle.com/c/rsna-intracranial-hemorrhage-detection/discussion/111292

thanks

**Comment by qubvel** [comment]
Thanks for proposal, it will be extremely useful!

**Comment by mobassir94** [comment]
you are welcome :)

**Comment by qubvel** [comment]
https://github.com/lukemelas/EfficientNet-PyTorch/pull/90
