### ISSUE TITLE
can't use efficientnet offline

### ISSUE THREAD

**Issue by mobassir94** [qubvel/segmentation_models.pytorch#84]
i downloaded the latest segmentation models pytorch whl file from this link : https://pypi.org/project/segmentation-models-pytorch/#files

also installed pretrained models,this one : https://pypi.org/project/pretrainedmodels/

but i don't see efficientnet there,is there any way to use efficientnet models offline with fpn,unet or linknet?

**Comment by mobassir94** [comment]
i wanted to use it offline but you are showing me installation guidiline which demands internet

**Comment by qubvel** [comment]
1) It is not clear from your question, pypi package does not have efficientnet, so you have to load it from source to be able to choose it as backbone
2) It is requred internet connection to load weights OR you can load it manually (look at url) and then use  `model.encoder.load_state_dict` OR use `encoder_weights=None`
