### ISSUE TITLE
How to correct contribute example with pt-lightning from my fork to original repo

### ISSUE THREAD

**Issue by IamSVP94** [qubvel/segmentation_models.pytorch#856]
I used this awesome repo for my own work and added pt-lightning for my work. Now I want to be usefull and add this example to orig repo. Should I do this? (Is it useful?) If "yes", how can I correct contribute my example to here?!
https://github.com/IamSVP94/segmentation_models.pytorch/tree/master/svp_customs - my custom work.

**Comment by JulienMaille** [comment]
You might want to submit a PR to this fork: https://github.com/isaaccorley/torchseg
