### ISSUE TITLE
data preproccessing : mask = to_tensor

### ISSUE THREAD

**Issue by raidanis** [qubvel/segmentation_models.pytorch#859]
my masks shape is (512, 512), when i start the fitting i get an error of miss matching axes , i think the problem is here : 

###  **def to_tensor(x, **kwargs):
    return x.transpose(2, 0, 1).astype('float32')**

the function expect input of 3 dimentions not 2 , any one can help ??

**Comment by qubvel** [comment]
Hi, you can just expand the last dim, `x[..., None]`

**Comment by raidanis** [comment]
I fix it but , I'm facing problems in deployment with flask , can you help
sir?

**Comment by qubvel** [comment]
You can ask a question, if I have an answer I will help :)
