### ISSUE TITLE
Why output of unet with activation 'sigmoid' not range from 0 to 1

### ISSUE THREAD

**Issue by cswwp** [qubvel/segmentation_models.pytorch#91]
![image](https://user-images.githubusercontent.com/11901683/67792930-f734ca00-fab4-11e9-9989-ef93c61a4bfe.png)
net with sigmoid should out value range from 0 to 1,  why?

**Comment by cswwp** [comment]
@qubvel

**Comment by vfdev-5** [comment]
@cswwp because activation is applied on `predict` method. See here: https://github.com/qubvel/segmentation_models.pytorch/blob/f5cf4b8683b4c2e5b1e7a7474e25646a8ed91de8/segmentation_models_pytorch/base/encoder_decoder.py#L45

**Comment by cswwp** [comment]
> @cswwp because activation is applied on `predict` method. See here:
> 
> https://github.com/qubvel/segmentation_models.pytorch/blob/f5cf4b8683b4c2e5b1e7a7474e25646a8ed91de8/segmentation_models_pytorch/base/encoder_decoder.py#L45

Thanks, got it.
