### ISSUE TITLE
if i use resnet18 as the backbone,the input channels must be 3?

### ISSUE THREAD

**Issue by AMSTLHX** [qubvel/segmentation_models.pytorch#92]

**Comment by qubvel** [comment]
Yes, but if you need another number of channels  you can install experimental branch `models-refactoring`

**Comment by AMSTLHX** [comment]
ok,thank you

**Comment by depshad** [comment]
@qubvel  Can you point me to an example using models-refactoring.I did not see an option to use different number of channels.
Thanks

**Comment by qubvel** [comment]
Just pass `in_channels=` argument in model constructor, e.g. `model=Unet(in_channels=4)`

**Comment by depshad** [comment]
Thank you!!

**Comment by JulienMaille** [comment]
Hello, I'm trying to work with grayscale image and passing `in_channels=1` is not enough.
I believe `get_preprocessing_fn` needs to know I'm not working with RGB, do you confirm?
