### ISSUE TITLE
What is the purpose of parameter "n" in AverageValueMeter 

### ISSUE THREAD

**Issue by VSydorskyy** [qubvel/segmentation_models.pytorch#94]
https://github.com/qubvel/segmentation_models.pytorch/blob/master/segmentation_models_pytorch/utils/meter.py#L44

As I understand: if I provide "n" parameter in AverageValueMeter, then my score is averaged over n?

**Comment by qubvel** [comment]
This is not my code, actually)  
It works, that was enough for me.
