### ISSUE TITLE
Amend the layers of encoder ?

### ISSUE THREAD

**Issue by PN12** [qubvel/segmentation_models.pytorch#96]
Are there any ways the layers can be amended while executing commands  sm.Unet (......)
 for example for **encoder resnet18** if I want to add a conv2d layer in the 1st block ?

**Comment by qubvel** [comment]
Here is a trick, replace first conv with a sequence of blocks:
```python
model.encoder.conv1 = nn.Sequential(<any layers here>)
```

**Comment by PN12** [comment]
Thanks, I will try.
