### ISSUE TITLE
I need HRNet

### ISSUE THREAD

**Issue by ShihuaiXu** [qubvel/segmentation_models.pytorch#97]

**Comment by ternaus** [comment]
Support this request. The architecture looks powerful.

https://github.com/HRNet/HRNet-Semantic-Segmentation

@qubvel

**Comment by qubvel** [comment]
Got it, will think about implementation, as far as I understand this is not usual encoder-decoder architecture

**Comment by qubvel** [comment]
btw @ternaus you could try bifpn implemetation in `bifpn` branch, but still have some doubs about this implementation, not everything is clear from paper

**Comment by ternaus** [comment]
Looks like @bloodaxe was also looking into this architecture.

https://github.com/BloodAxe/pytorch-toolbelt/blob/feature/0.3.0/pytorch_toolbelt/modules/backbone/hrnet.py

**Comment by seefun** [comment]
Looking forward to adding HRNet!

**Comment by bluesky314** [comment]
Has it been added? @qubvel @seefun

**Comment by ptklx** [comment]
how to run multi GPU,i use nn.DataParallel()  but error
